-- ============================================================================
-- return_tests_module.lua
-- Pre-serialized module_data for LuaJIT runtime
-- DO NOT EDIT - Generated by s_compile.lua v5.2
-- ============================================================================

local M = {}

M.name         = "return_tests"
M.name_hash    = 0xAF90FF75
M.pointer_size = 4
M.debug        = true

M.oneshot_funcs = {  }
M.main_funcs    = { "SE_RETURN_CONTINUE", "SE_RETURN_HALT", "SE_RETURN_TERMINATE", "SE_RETURN_RESET", "SE_RETURN_DISABLE", "SE_RETURN_SKIP_CONTINUE", "SE_RETURN_FUNCTION_CONTINUE", "SE_RETURN_FUNCTION_HALT", "SE_RETURN_FUNCTION_TERMINATE", "SE_RETURN_FUNCTION_RESET", "SE_RETURN_FUNCTION_DISABLE", "SE_RETURN_FUNCTION_SKIP_CONTINUE", "SE_RETURN_PIPELINE_CONTINUE", "SE_RETURN_PIPELINE_HALT", "SE_RETURN_PIPELINE_TERMINATE", "SE_RETURN_PIPELINE_RESET", "SE_RETURN_PIPELINE_DISABLE", "SE_RETURN_PIPELINE_SKIP_CONTINUE" }
M.pred_funcs    = {  }

M.string_table = {  }
M.string_index = {
}

M.tree_order = { "return_continue_test", "return_halt_test", "return_terminate_test", "return_reset_test", "return_disable_test", "return_skip_continue_test", "return_function_continue_test", "return_function_halt_test", "return_function_terminate_test", "return_function_reset_test", "return_function_disable_test", "return_function_skip_continue_test", "return_pipeline_continue_test", "return_pipeline_halt_test", "return_pipeline_terminate_test", "return_pipeline_reset_test", "return_pipeline_disable_test", "return_pipeline_skip_continue_test" }
M.trees = {}

M.trees["return_continue_test"] = {
  name          = "return_continue_test",
  name_hash     = 0x5BEA640A,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_CONTINUE",
      func_hash=0xB4243714,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_halt_test"] = {
  name          = "return_halt_test",
  name_hash     = 0x99EFDDC0,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_HALT",
      func_hash=0x056FB9EA,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_terminate_test"] = {
  name          = "return_terminate_test",
  name_hash     = 0x0F3DCDA4,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_TERMINATE",
      func_hash=0xDFE64C74,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_reset_test"] = {
  name          = "return_reset_test",
  name_hash     = 0xC20F4504,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_RESET",
      func_hash=0x70EAA030,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_disable_test"] = {
  name          = "return_disable_test",
  name_hash     = 0x381457B1,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_DISABLE",
      func_hash=0x02C11A13,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_skip_continue_test"] = {
  name          = "return_skip_continue_test",
  name_hash     = 0xA58DA842,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_SKIP_CONTINUE",
      func_hash=0xEAE5524E,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_function_continue_test"] = {
  name          = "return_function_continue_test",
  name_hash     = 0x92D5E4E9,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_FUNCTION_CONTINUE",
      func_hash=0xF7191B5B,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_function_halt_test"] = {
  name          = "return_function_halt_test",
  name_hash     = 0x1D7C493B,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_FUNCTION_HALT",
      func_hash=0x891F0675,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_function_terminate_test"] = {
  name          = "return_function_terminate_test",
  name_hash     = 0x1B509D29,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_FUNCTION_TERMINATE",
      func_hash=0x0A5B8A85,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_function_reset_test"] = {
  name          = "return_function_reset_test",
  name_hash     = 0xA4CD827D,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_FUNCTION_RESET",
      func_hash=0xF6027E85,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_function_disable_test"] = {
  name          = "return_function_disable_test",
  name_hash     = 0x275F0EE0,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_FUNCTION_DISABLE",
      func_hash=0x7E3D3A4A,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_function_skip_continue_test"] = {
  name          = "return_function_skip_continue_test",
  name_hash     = 0x09EC0E57,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_FUNCTION_SKIP_CONTINUE",
      func_hash=0x338AC3DB,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_pipeline_continue_test"] = {
  name          = "return_pipeline_continue_test",
  name_hash     = 0x50222FFB,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_PIPELINE_CONTINUE",
      func_hash=0x5A902F85,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_pipeline_halt_test"] = {
  name          = "return_pipeline_halt_test",
  name_hash     = 0xEB5C011D,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_PIPELINE_HALT",
      func_hash=0x4AC84487,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_pipeline_terminate_test"] = {
  name          = "return_pipeline_terminate_test",
  name_hash     = 0x824A77DF,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_PIPELINE_TERMINATE",
      func_hash=0x0933AC9B,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_pipeline_reset_test"] = {
  name          = "return_pipeline_reset_test",
  name_hash     = 0x338090A3,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_PIPELINE_RESET",
      func_hash=0x8CD80263,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_pipeline_disable_test"] = {
  name          = "return_pipeline_disable_test",
  name_hash     = 0x2D614786,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_PIPELINE_DISABLE",
      func_hash=0x6B7AA500,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.trees["return_pipeline_skip_continue_test"] = {
  name          = "return_pipeline_skip_continue_test",
  name_hash     = 0x3A917129,
  node_count    = 1,
  pointer_count = 0,
  record_name   = nil,
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_RETURN_PIPELINE_SKIP_CONTINUE",
      func_hash=0xD3A0766D,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={},
    },
  },
}

M.record_order = {  }
M.records      = {}
M.const_order = {  }
M.constants   = {}

M.events      = {}
M.event_names = {}
return M
