-- drone_control_ffi.lua
-- Generated by avro_dsl.lua GENERATE_FFI - DO NOT EDIT
local ffi = require("ffi")
local M = {}

ffi.cdef[[
// Wire header (16 bytes)
typedef struct __attribute__((packed)) {
    double      timestamp;
    uint32_t    schema_hash;
    uint16_t    seq;
    uint16_t    source_node;
} drone_control_wire_header_t;

// Pointers (wire: fixed 8-byte uint64_t)
typedef struct { uint64_t ptr; } finalize_data_t;

// Wire records (packed data only)
typedef struct __attribute__((packed)) {
    float distance;
    float final_altitude;
    float final_speed;
    float heading;
    uint64_t finalize;
} fly_straight_request_wire_t;

typedef struct __attribute__((packed)) {
    float distance;
    float final_altitude;
    float final_speed;
    float heading;
    bool success;
    int32_t error_code;
} fly_straight_response_wire_t;

typedef struct __attribute__((packed)) {
    float distance;
    float final_altitude;
    float final_speed;
    float heading;
    uint64_t finalize;
} fly_arc_request_wire_t;

typedef struct __attribute__((packed)) {
    float distance;
    float final_altitude;
    float final_speed;
    float heading;
    bool success;
    int32_t error_code;
} fly_arc_response_wire_t;

typedef struct __attribute__((packed)) {
    float final_altitude;
    float final_speed;
    uint64_t finalize;
} fly_up_request_wire_t;

typedef struct __attribute__((packed)) {
    float final_altitude;
    float final_speed;
    bool success;
    int32_t error_code;
} fly_up_response_wire_t;

typedef struct __attribute__((packed)) {
    float final_altitude;
    float final_speed;
    uint64_t finalize;
} fly_down_request_wire_t;

typedef struct __attribute__((packed)) {
    float final_altitude;
    float final_speed;
    bool success;
    int32_t error_code;
} fly_down_response_wire_t;

// Packets (header + wire data)
typedef struct __attribute__((packed)) {
    drone_control_wire_header_t header;
    fly_straight_request_wire_t        data;
} fly_straight_request_packet_t;

typedef struct __attribute__((packed)) {
    drone_control_wire_header_t header;
    fly_straight_response_wire_t        data;
} fly_straight_response_packet_t;

typedef struct __attribute__((packed)) {
    drone_control_wire_header_t header;
    fly_arc_request_wire_t        data;
} fly_arc_request_packet_t;

typedef struct __attribute__((packed)) {
    drone_control_wire_header_t header;
    fly_arc_response_wire_t        data;
} fly_arc_response_packet_t;

typedef struct __attribute__((packed)) {
    drone_control_wire_header_t header;
    fly_up_request_wire_t        data;
} fly_up_request_packet_t;

typedef struct __attribute__((packed)) {
    drone_control_wire_header_t header;
    fly_up_response_wire_t        data;
} fly_up_response_packet_t;

typedef struct __attribute__((packed)) {
    drone_control_wire_header_t header;
    fly_down_request_wire_t        data;
} fly_down_request_packet_t;

typedef struct __attribute__((packed)) {
    drone_control_wire_header_t header;
    fly_down_response_wire_t        data;
} fly_down_response_packet_t;

]]

-- Record metadata
M.records = {
    ["fly_straight_request"] = {
        schema_hash  = 0xA084479F,
        wire_size    = 24,
        packet_size  = 40,
        packet_ct    = ffi.typeof("fly_straight_request_packet_t"),
        wire_ct      = ffi.typeof("fly_straight_request_wire_t"),
    },
    ["fly_straight_response"] = {
        schema_hash  = 0xFEADC6A5,
        wire_size    = 21,
        packet_size  = 37,
        packet_ct    = ffi.typeof("fly_straight_response_packet_t"),
        wire_ct      = ffi.typeof("fly_straight_response_wire_t"),
    },
    ["fly_arc_request"] = {
        schema_hash  = 0xC7919983,
        wire_size    = 24,
        packet_size  = 40,
        packet_ct    = ffi.typeof("fly_arc_request_packet_t"),
        wire_ct      = ffi.typeof("fly_arc_request_wire_t"),
    },
    ["fly_arc_response"] = {
        schema_hash  = 0x6E4B05B1,
        wire_size    = 21,
        packet_size  = 37,
        packet_ct    = ffi.typeof("fly_arc_response_packet_t"),
        wire_ct      = ffi.typeof("fly_arc_response_wire_t"),
    },
    ["fly_up_request"] = {
        schema_hash  = 0x6E4B294C,
        wire_size    = 16,
        packet_size  = 32,
        packet_ct    = ffi.typeof("fly_up_request_packet_t"),
        wire_ct      = ffi.typeof("fly_up_request_wire_t"),
    },
    ["fly_up_response"] = {
        schema_hash  = 0x92D4ED60,
        wire_size    = 13,
        packet_size  = 29,
        packet_ct    = ffi.typeof("fly_up_response_packet_t"),
        wire_ct      = ffi.typeof("fly_up_response_wire_t"),
    },
    ["fly_down_request"] = {
        schema_hash  = 0xF9FCDFD9,
        wire_size    = 16,
        packet_size  = 32,
        packet_ct    = ffi.typeof("fly_down_request_packet_t"),
        wire_ct      = ffi.typeof("fly_down_request_wire_t"),
    },
    ["fly_down_response"] = {
        schema_hash  = 0x1CD40DC7,
        wire_size    = 13,
        packet_size  = 29,
        packet_ct    = ffi.typeof("fly_down_response_packet_t"),
        wire_ct      = ffi.typeof("fly_down_response_wire_t"),
    },
}

-- Hash to record name lookup
M.hash_to_name = {
    [0xA084479F] = "fly_straight_request",
    [0xFEADC6A5] = "fly_straight_response",
    [0xC7919983] = "fly_arc_request",
    [0x6E4B05B1] = "fly_arc_response",
    [0x6E4B294C] = "fly_up_request",
    [0x92D4ED60] = "fly_up_response",
    [0xF9FCDFD9] = "fly_down_request",
    [0x1CD40DC7] = "fly_down_response",
}

--- Initialise a packet header for the given record.
-- @param pkt        cdata packet (e.g. from M.new_packet)
-- @param record_name string key into M.records
-- @param source_node uint16 originating node id
function M.packet_init(pkt, record_name, source_node)
    local info = M.records[record_name]
    assert(info, "unknown record: " .. tostring(record_name))
    pkt.header.schema_hash = info.schema_hash
    pkt.header.timestamp   = 0.0
    pkt.header.seq         = 0
    pkt.header.source_node = source_node or 0
    return pkt.data
end

--- Verify a packet's schema_hash matches the expected record.
-- @return pkt.data on success, nil on mismatch
function M.packet_verify(pkt, record_name)
    local info = M.records[record_name]
    if not info then return nil end
    if pkt.header.schema_hash ~= info.schema_hash then return nil end
    return pkt.data
end

--- Allocate a new zero-initialised packet for the given record.
function M.new_packet(record_name)
    local info = M.records[record_name]
    assert(info, "unknown record: " .. tostring(record_name))
    return ffi.new(info.packet_ct)
end

return M
