-- stream_test_1_ffi.lua
-- Generated by avro_dsl.lua GENERATE_FFI - DO NOT EDIT
local ffi = require("ffi")
local M = {}

ffi.cdef[[
// Wire header (16 bytes)
typedef struct __attribute__((packed)) {
    double      timestamp;
    uint32_t    schema_hash;
    uint16_t    seq;
    uint16_t    source_node;
} stream_test_1_wire_header_t;

// Wire records (packed data only)
typedef struct __attribute__((packed)) {
    float x;
    float y;
    float z;
} accelerometer_reading_wire_t;

typedef struct __attribute__((packed)) {
    float x;
    float y;
    float z;
} accelerometer_reading_filtered_wire_t;

// Packets (header + wire data)
typedef struct __attribute__((packed)) {
    stream_test_1_wire_header_t header;
    accelerometer_reading_wire_t        data;
} accelerometer_reading_packet_t;

typedef struct __attribute__((packed)) {
    stream_test_1_wire_header_t header;
    accelerometer_reading_filtered_wire_t        data;
} accelerometer_reading_filtered_packet_t;

]]

-- Record metadata
M.records = {
    ["accelerometer_reading"] = {
        schema_hash  = 0x29A015D4,
        wire_size    = 12,
        packet_size  = 28,
        packet_ct    = ffi.typeof("accelerometer_reading_packet_t"),
        wire_ct      = ffi.typeof("accelerometer_reading_wire_t"),
    },
    ["accelerometer_reading_filtered"] = {
        schema_hash  = 0x90C9FC22,
        wire_size    = 12,
        packet_size  = 28,
        packet_ct    = ffi.typeof("accelerometer_reading_filtered_packet_t"),
        wire_ct      = ffi.typeof("accelerometer_reading_filtered_wire_t"),
    },
}

-- Hash to record name lookup
M.hash_to_name = {
    [0x29A015D4] = "accelerometer_reading",
    [0x90C9FC22] = "accelerometer_reading_filtered",
}

--- Initialise a packet header for the given record.
-- @param pkt        cdata packet (e.g. from M.new_packet)
-- @param record_name string key into M.records
-- @param source_node uint16 originating node id
function M.packet_init(pkt, record_name, source_node)
    local info = M.records[record_name]
    assert(info, "unknown record: " .. tostring(record_name))
    pkt.header.schema_hash = info.schema_hash
    pkt.header.timestamp   = 0.0
    pkt.header.seq         = 0
    pkt.header.source_node = source_node or 0
    return pkt.data
end

--- Verify a packet's schema_hash matches the expected record.
-- @return pkt.data on success, nil on mismatch
function M.packet_verify(pkt, record_name)
    local info = M.records[record_name]
    if not info then return nil end
    if pkt.header.schema_hash ~= info.schema_hash then return nil end
    return pkt.data
end

--- Allocate a new zero-initialised packet for the given record.
function M.new_packet(record_name)
    local info = M.records[record_name]
    assert(info, "unknown record: " .. tostring(record_name))
    return ffi.new(info.packet_ct)
end

-- ============ CONST PACKETS ============
M.const_packets = {}

do
    local pkt = ffi.new("accelerometer_reading_packet_t")
    pkt.header.schema_hash = 0x29A015D4
    pkt.header.timestamp   = 0.0
    pkt.header.seq         = 0
    pkt.header.source_node = 0
    pkt.data.x = 0.0
    pkt.data.y = 0.0
    pkt.data.z = 9.81
    M.const_packets["default_accel_reading"] = pkt
end

return M
