// ============================================================================
// door_window_controller_dump_32.h
// DEBUG PARAMETER DUMP for door_window_controller
// Mode: 32-bit
// Generated by s_expr_dsl v5.2
// ============================================================================

#ifndef DOOR_WINDOW_CONTROLLER_DUMP_32_H
#define DOOR_WINDOW_CONTROLLER_DUMP_32_H

/*
 * PARAMETER TYPE CODES:
 *   0x00 INT          0x01 UINT         0x02 FLOAT        0x03 STR_HASH
 *   0x04 SLOT         0x05 OPEN         0x06 CLOSE        0x07 OPEN_CALL
 *   0x08 ONESHOT      0x09 MAIN         0x0A PRED         0x0B FIELD
 *   0x0C RESULT       0x0D STR_IDX      0x0E CONST_REF    0x0F RESERVED
 *   0x10 OPEN_DICT    0x11 CLOSE_DICT   0x12 OPEN_KEY     0x13 CLOSE_KEY
 *   0x14 OPEN_ARRAY   0x15 CLOSE_ARRAY  0x16 OPEN_TUPLE   0x17 CLOSE_TUPLE
 *
 * FLAGS:
 *   0x40 SURVIVES_RESET (io_call, p_call_composite)
 *   0x80 POINTER        (pt_m_call)
 */

/*
 * Module: door_window_controller
 * Hash:   0x5CAB5C2F
 * Trees:  1
 * Records: 1
 * Strings: 28
 * Constants: 1
 * Param size: 8 bytes (32-bit)
 */

// ============================================================================
// STRING TABLE
// ============================================================================
/*
 * [0x0000] (  0) hash=0x5B2664D4 "Door window controller started"
 * [0x0001] (  1) hash=0x08C82D9F "CMD: Open window"
 * [0x0002] (  2) hash=0xEB18404D "CMD: Close window"
 * [0x0003] (  3) hash=0x51DA3F29 "CMD: Stop"
 * [0x0004] (  4) hash=0x451DCF16 "CMD: Status request"
 * [0x0005] (  5) hash=0x7EA11679 "CMD: Emergency stop!"
 * [0x0006] (  6) hash=0x0E39E3E6 "CMD: Unknown serial command"
 * [0x0007] (  7) hash=0xB292C77A "MOTOR: Idle"
 * [0x0008] (  8) hash=0x8CC4C814 "MOTOR: Opening window"
 * [0x0009] (  9) hash=0x42CE6813 "FAULT: Over-current detected"
 * [0x000A] ( 10) hash=0x74419C19 "FAULT: Obstruction detected"
 * [0x000B] ( 11) hash=0x21F66713 "TIMEOUT: Opening exceeded 30s"
 * [0x000C] ( 12) hash=0x4D424E6A "DOOR_OPEN"
 * [0x000D] ( 13) hash=0x2E8F65C5 "MOTOR: Closing window"
 * [0x000E] ( 14) hash=0x065584E1 "FAULT: Obstruction - auto-reversing"
 * [0x000F] ( 15) hash=0xBB780616 "TIMEOUT: Closing exceeded 30s"
 * [0x0010] ( 16) hash=0x4D9EEA2E "DOOR_CLOSED"
 * [0x0011] ( 17) hash=0x1827E7AC "MOTOR: Auto-reverse after obstruction"
 * [0x0012] ( 18) hash=0x20565728 "OBSTRUCTION_DETECTED"
 * [0x0013] ( 19) hash=0x22F02E7F "MOTOR: Auto-reverse complete"
 * [0x0014] ( 20) hash=0x7131F937 "MOTOR: EMERGENCY STOP"
 * [0x0015] ( 21) hash=0xB9D06524 "EMERGENCY_STOPPED"
 * [0x0016] ( 22) hash=0xC37E1700 "MOTOR: Manual reset received"
 * [0x0017] ( 23) hash=0x60CA2984 "MOTOR: Invalid state - entering emergency"
 * [0x0018] ( 24) hash=0x9A1D23DB "STATUS: Report sent"
 * [0x0019] ( 25) hash=0xD148E802 "DIAG: Thermal shutdown!"
 * [0x001A] ( 26) hash=0x269DA3C1 "DIAG: Voltage out of range!"
 * [0x001B] ( 27) hash=0xB02C9E52 "DIAG: TLE7269G fault detected"
 */

// ============================================================================
// FUNCTION TABLES
// ============================================================================
/*
 * ONESHOT FUNCTIONS (type=0x08, with 0x40=io_call):
 *   [0x0000] ( 0) hash=0xFFF84A15 SE_SET_FIELD
 *   [0x0001] ( 1) hash=0xCEBBEFA4 SE_LOG
 *   [0x0002] ( 2) hash=0x21F70576 READ_SERIAL_MESSAGE
 *   [0x0003] ( 3) hash=0x2294BEC5 PARSE_MESSAGE_TYPE
 *   [0x0004] ( 4) hash=0xCF729BCE SE_QUEUE_EVENT
 *   [0x0005] ( 5) hash=0x9A0D92FA DISABLE_MOTOR_TLE7269G
 *   [0x0006] ( 6) hash=0x5C071EC1 SET_BRIDGE_MODE
 *   [0x0007] ( 7) hash=0x3572046E SET_MOTOR_PWM
 *   [0x0008] ( 8) hash=0x1F90BFFD ENABLE_MOTOR_TLE7269G
 *   [0x0009] ( 9) hash=0x080C2B37 SE_NOP
 *   [0x000A] (10) hash=0x462235D6 SEND_STATUS_MESSAGE
 *   [0x000B] (11) hash=0xD1C8709B READ_DIAGNOSTICS_TLE7269G
 *   [0x000C] (12) hash=0xB62BA5BB READ_CURRENT_POSITION
 *   [0x000D] (13) hash=0x3DADDF65 READ_MOTOR_CURRENT
 *   [0x000E] (14) hash=0x0B55B0E4 READ_TEMPERATURE
 *   [0x000F] (15) hash=0x199FBF58 ASSEMBLE_STATUS_MESSAGE
 *   [0x0010] (16) hash=0x5EA6EF23 SEND_SERIAL_STATUS
 *   [0x0011] (17) hash=0xE057BF86 READ_FAULT_STATUS_TLE7269G
 *
 * MAIN FUNCTIONS (type=0x09, with 0x80=pt_m_call):
 *   [0x0000] ( 0) hash=0xC7FEA7F6 SE_FUNCTION_INTERFACE
 *   [0x0001] ( 1) hash=0x0A24332A SE_FORK
 *   [0x0002] ( 2) hash=0xFFC1FAA4 SE_CHAIN_FLOW
 *   [0x0003] ( 3) hash=0xDD7F6663 SE_WAIT
 *   [0x0004] ( 4) hash=0xA1C11B35 SE_FIELD_DISPATCH
 *   [0x0005] ( 5) hash=0x8CD80263 SE_RETURN_PIPELINE_RESET
 *   [0x0006] ( 6) hash=0x4AC84487 SE_RETURN_PIPELINE_HALT
 *   [0x0007] ( 7) hash=0x5EEDA8E9 SE_STATE_MACHINE
 *   [0x0008] ( 8) hash=0xCE0831A2 SE_COND
 *   [0x0009] ( 9) hash=0xEC3EE7BF SE_SEQUENCE
 *   [0x000A] (10) hash=0xA08B6DD3 SE_WHILE
 *   [0x000B] (11) hash=0xE404E1CF SE_FORK_JOIN
 *   [0x000C] (12) hash=0x1E860193 SE_IF_THEN_ELSE
 *   [0x000D] (13) hash=0x0D3E0C4F SE_VERIFY_AND_CHECK_ELAPSED_TIME
 *   [0x000E] (14) hash=0x0C3460EB SE_TICK_DELAY
 *
 * PRED FUNCTIONS (type=0x0A, with 0x40=p_call_composite):
 *   [0x0000] ( 0) hash=0x0C125BC2 SE_TRUE
 *   [0x0001] ( 1) hash=0x10F63374 SE_FIELD_GT
 *   [0x0002] ( 2) hash=0x2B37E8C9 CHECK_LIMIT_SWITCH_OPEN
 *   [0x0003] ( 3) hash=0x772EDA2C CHECK_MOTOR_STALL
 *   [0x0004] ( 4) hash=0x0CF6212F SE_PRED_OR
 *   [0x0005] ( 5) hash=0xD9FBED0D SE_FIELD_EQ
 *   [0x0006] ( 6) hash=0xECBB0205 CHECK_LIMIT_SWITCH_CLOSED
 *   [0x0007] ( 7) hash=0x80659F81 SE_CHECK_EVENT
 *   [0x0008] ( 8) hash=0xD2EA98E7 SE_FIELD_LT
 */

// ============================================================================
// RECORD DEFINITIONS
// ============================================================================
/*
 * RECORD[0x0000]: door_controller_bb (size=136, align=8, hash=0xF73EE1BF)
 *   [ 0] off=0x0000 size= 4 hash=0x7EFCE2D8 motor_state
 *   [ 1] off=0x0004 size= 4 hash=0x03BEC4CA bridge_mode
 *   [ 2] off=0x0008 size= 4 hash=0x392C6161 motor_pwm
 *   [ 3] off=0x000C size= 4 hash=0x6BDC382C motor_enabled
 *   [ 4] off=0x0010 size= 4 hash=0x34A7FD08 motor_current
 *   [ 5] off=0x0014 size= 4 hash=0x58983273 max_current
 *   [ 6] off=0x0018 size= 4 hash=0x934F4E0A position
 *   [ 7] off=0x001C size= 4 hash=0xE9F2A935 temperature
 *   [ 8] off=0x0020 size= 4 hash=0xE1935F65 voltage
 *   [ 9] off=0x0024 size= 4 hash=0x46D7BAF5 open_speed
 *   [10] off=0x0028 size= 4 hash=0x3826D73F close_speed
 *   [11] off=0x002C size= 4 hash=0x123B7090 thermal_threshold
 *   [12] off=0x0030 size= 4 hash=0x1BC6C7BE min_voltage
 *   [13] off=0x0034 size= 4 hash=0xF80640E0 max_voltage
 *   [14] off=0x0038 size= 4 hash=0x81F715A8 fully_open
 *   [15] off=0x003C size= 4 hash=0x52AE64E0 fully_closed
 *   [16] off=0x0040 size= 4 hash=0x75463942 emergency
 *   [17] off=0x0044 size= 4 hash=0x1998554D obstruction
 *   [18] off=0x0048 size= 4 hash=0x37F0CAB5 over_current
 *   [19] off=0x004C size= 4 hash=0x7015068F system_shutdown
 *   [20] off=0x0050 size= 4 hash=0x8E34B593 manual_reset
 *   [21] off=0x0054 size= 4 hash=0x3EB5C79A fault_pin_active
 *   [22] off=0x0058 size= 4 hash=0x39BCAB0F open_request
 *   [23] off=0x005C size= 4 hash=0x2C02810D close_request
 *   [24] off=0x0060 size= 4 hash=0x97F05C03 stop_request
 *   [25] off=0x0064 size= 4 hash=0xDCC3E951 status_request
 *   [26] off=0x0068 size= 4 hash=0x74D06EC8 auto_reverse_req
 *   [27] off=0x006C size= 4 hash=0x62B07F42 serial_data_avail
 *   [28] off=0x0070 size= 4 hash=0x698D9E40 serial_msg_type
 *   [29] off=0x0078 size= 8 hash=0xFC6A9852 config_ptr PTR64
 *   [30] off=0x0080 size= 8 hash=0xF703176F diag_ptr PTR64
 *
 */

// ============================================================================
// CONSTANTS
// ============================================================================
/*
 * CONST[0x0000]: door_defaults (record=door_controller_bb, hash=0xC9F74114)
 *   bytes: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
 *          00 00 00 00 00 00 A0 40 00 00 00 00 00 00 C8 41 
 *          CD CC 5C 41 C8 00 00 00 B4 00 00 00 00 00 AA 42 
 *          00 00 10 41 00 00 80 41 00 00 00 00 01 00 00 00 
 *          00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
 *          00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
 *          00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
 *          00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
 *          00 00 00 00 00 00 00 00 
 */

// ============================================================================
// TREE PARAMETERS
// ============================================================================
/*
 * TREE: door_controller
 *   hash=0xE463049A nodes=265 ptrs=6
 *   record=door_controller_bb (hash=0xF73EE1BF)
 *   defaults=door_defaults (idx=0x0000)
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]   1064      0  SE_FUNCTION_INTERFACE hash=0xC7FEA7F6
 *    1  MAIN      [0x09]      0      0  idx_to_ptr=0
 *    2    OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *    3    ONESHOT+SR[0x48]      2      0  idx_to_ptr=0
 *    4      FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *    5      UINT[0x01]           -      -  0 (0x00000000)
 *    6    CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *    7    OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *    8    ONESHOT   [0x08]      7      1  idx_to_ptr=0
 *    9      STR_IDX[0x0D]        0     30  "Door window controller started"
 *   10    CLOSE[0x06]          0      -  (end SE_LOG)
 *   11    OPEN_CALL[0x07]   1052      0  SE_FORK hash=0x0A24332A
 *   12    MAIN      [0x09]     11      1  idx_to_ptr=0
 *   13      OPEN_CALL[0x07]    136      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   14      MAIN      [0x09]     13      2  idx_to_ptr=0
 *   15        OPEN_CALL[0x07]      2      0  SE_WAIT hash=0xDD7F6663
 *   16        MAIN      [0x09]     15      3  idx_to_ptr=0
 *   17        CLOSE[0x06]          0      -  (end SE_WAIT)
 *   18        OPEN_CALL[0x07]      2      0  READ_SERIAL_MESSAGE hash=0x21F70576
 *   19        ONESHOT   [0x08]     18      2  idx_to_ptr=0
 *   20        CLOSE[0x06]          0      -  (end READ_SERIAL_MESSAGE)
 *   21        OPEN_CALL[0x07]      2      0  PARSE_MESSAGE_TYPE hash=0x2294BEC5
 *   22        ONESHOT   [0x08]     21      3  idx_to_ptr=0
 *   23        CLOSE[0x06]          0      -  (end PARSE_MESSAGE_TYPE)
 *   24        OPEN_CALL[0x07]    124      0  SE_FIELD_DISPATCH hash=0xA1C11B35
 *   25        MAIN      [0x09]     24      4  idx_to_ptr=0
 *   26          FIELD[0x0B]        112      4  serial_msg_type (off=0x0070, hash=0x698D9E40)
 *   27          INT[0x00]            -      -  1 (0x00000001)
 *   28          OPEN_CALL[0x07]     20      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   29          MAIN      [0x09]     28      2  idx_to_ptr=0
 *   30            OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   31            ONESHOT   [0x08]     30      0  idx_to_ptr=0
 *   32              FIELD[0x0B]         88      4  open_request (off=0x0058, hash=0x39BCAB0F)
 *   33              UINT[0x01]           -      -  1 (0x00000001)
 *   34            CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   35            OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *   36            ONESHOT   [0x08]     35      4  idx_to_ptr=0
 *   37              UINT[0x01]           -      -  0 (0x00000000)
 *   38              UINT[0x01]           -      -  1 (0x00000001)
 *   39              FIELD[0x0B]         88      4  open_request (off=0x0058, hash=0x39BCAB0F)
 *   40            CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *   41            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   42            ONESHOT   [0x08]     41      1  idx_to_ptr=0
 *   43              STR_IDX[0x0D]        1     16  "CMD: Open window"
 *   44            CLOSE[0x06]          0      -  (end SE_LOG)
 *   45            OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *   46            MAIN      [0x09]     45      5  idx_to_ptr=0
 *   47            CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *   48          CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   49          INT[0x00]            -      -  2 (0x00000002)
 *   50          OPEN_CALL[0x07]     20      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   51          MAIN      [0x09]     50      2  idx_to_ptr=0
 *   52            OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   53            ONESHOT   [0x08]     52      0  idx_to_ptr=0
 *   54              FIELD[0x0B]         92      4  close_request (off=0x005C, hash=0x2C02810D)
 *   55              UINT[0x01]           -      -  1 (0x00000001)
 *   56            CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   57            OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *   58            ONESHOT   [0x08]     57      4  idx_to_ptr=0
 *   59              UINT[0x01]           -      -  0 (0x00000000)
 *   60              UINT[0x01]           -      -  2 (0x00000002)
 *   61              FIELD[0x0B]         92      4  close_request (off=0x005C, hash=0x2C02810D)
 *   62            CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *   63            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   64            ONESHOT   [0x08]     63      1  idx_to_ptr=0
 *   65              STR_IDX[0x0D]        2     17  "CMD: Close window"
 *   66            CLOSE[0x06]          0      -  (end SE_LOG)
 *   67            OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *   68            MAIN      [0x09]     67      5  idx_to_ptr=0
 *   69            CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *   70          CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   71          INT[0x00]            -      -  3 (0x00000003)
 *   72          OPEN_CALL[0x07]     20      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   73          MAIN      [0x09]     72      2  idx_to_ptr=0
 *   74            OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   75            ONESHOT   [0x08]     74      0  idx_to_ptr=0
 *   76              FIELD[0x0B]         96      4  stop_request (off=0x0060, hash=0x97F05C03)
 *   77              UINT[0x01]           -      -  1 (0x00000001)
 *   78            CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   79            OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *   80            ONESHOT   [0x08]     79      4  idx_to_ptr=0
 *   81              UINT[0x01]           -      -  0 (0x00000000)
 *   82              UINT[0x01]           -      -  3 (0x00000003)
 *   83              FIELD[0x0B]         96      4  stop_request (off=0x0060, hash=0x97F05C03)
 *   84            CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *   85            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   86            ONESHOT   [0x08]     85      1  idx_to_ptr=0
 *   87              STR_IDX[0x0D]        3      9  "CMD: Stop"
 *   88            CLOSE[0x06]          0      -  (end SE_LOG)
 *   89            OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *   90            MAIN      [0x09]     89      5  idx_to_ptr=0
 *   91            CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *   92          CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   93          INT[0x00]            -      -  4 (0x00000004)
 *   94          OPEN_CALL[0x07]     20      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   95          MAIN      [0x09]     94      2  idx_to_ptr=0
 *   96            OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   97            ONESHOT   [0x08]     96      0  idx_to_ptr=0
 *   98              FIELD[0x0B]        100      4  status_request (off=0x0064, hash=0xDCC3E951)
 *   99              UINT[0x01]           -      -  1 (0x00000001)
 *  100            CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  101            OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  102            ONESHOT   [0x08]    101      4  idx_to_ptr=0
 *  103              UINT[0x01]           -      -  0 (0x00000000)
 *  104              UINT[0x01]           -      -  4 (0x00000004)
 *  105              FIELD[0x0B]        100      4  status_request (off=0x0064, hash=0xDCC3E951)
 *  106            CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  107            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  108            ONESHOT   [0x08]    107      1  idx_to_ptr=0
 *  109              STR_IDX[0x0D]        4     19  "CMD: Status request"
 *  110            CLOSE[0x06]          0      -  (end SE_LOG)
 *  111            OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  112            MAIN      [0x09]    111      5  idx_to_ptr=0
 *  113            CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  114          CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  115          INT[0x00]            -      -  5 (0x00000005)
 *  116          OPEN_CALL[0x07]     20      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  117          MAIN      [0x09]    116      2  idx_to_ptr=0
 *  118            OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  119            ONESHOT   [0x08]    118      0  idx_to_ptr=0
 *  120              FIELD[0x0B]         64      4  emergency (off=0x0040, hash=0x75463942)
 *  121              UINT[0x01]           -      -  1 (0x00000001)
 *  122            CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  123            OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  124            ONESHOT   [0x08]    123      4  idx_to_ptr=0
 *  125              UINT[0x01]           -      -  0 (0x00000000)
 *  126              UINT[0x01]           -      -  5 (0x00000005)
 *  127              FIELD[0x0B]         64      4  emergency (off=0x0040, hash=0x75463942)
 *  128            CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  129            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  130            ONESHOT   [0x08]    129      1  idx_to_ptr=0
 *  131              STR_IDX[0x0D]        5     20  "CMD: Emergency stop!"
 *  132            CLOSE[0x06]          0      -  (end SE_LOG)
 *  133            OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  134            MAIN      [0x09]    133      5  idx_to_ptr=0
 *  135            CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  136          CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  137          INT[0x00]            -      -  -1 (0xFFFFFFFF)
 *  138          OPEN_CALL[0x07]      9      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  139          MAIN      [0x09]    138      2  idx_to_ptr=0
 *  140            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  141            ONESHOT   [0x08]    140      1  idx_to_ptr=0
 *  142              STR_IDX[0x0D]        6     27  "CMD: Unknown serial command"
 *  143            CLOSE[0x06]          0      -  (end SE_LOG)
 *  144            OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_HALT hash=0x4AC84487
 *  145            MAIN      [0x09]    144      6  idx_to_ptr=0
 *  146            CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_HALT)
 *  147          CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  148        CLOSE[0x06]          0      -  (end SE_FIELD_DISPATCH)
 *  149      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  150      OPEN_CALL[0x07]    738      0  SE_STATE_MACHINE hash=0x5EEDA8E9
 *  151      MAIN      [0x09]    150      7  idx_to_ptr=0
 *  152        FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *  153        INT[0x00]            -      -  0 (0x00000000)
 *  154        OPEN_CALL[0x07]     63      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  155        MAIN      [0x09]    154      2  idx_to_ptr=0
 *  156          OPEN_CALL[0x07]      2      0  DISABLE_MOTOR_TLE7269G hash=0x9A0D92FA
 *  157          ONESHOT   [0x08]    156      5  idx_to_ptr=0
 *  158          CLOSE[0x06]          0      -  (end DISABLE_MOTOR_TLE7269G)
 *  159          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  160          ONESHOT   [0x08]    159      0  idx_to_ptr=0
 *  161            FIELD[0x0B]         12      4  motor_enabled (off=0x000C, hash=0x6BDC382C)
 *  162            UINT[0x01]           -      -  0 (0x00000000)
 *  163          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  164          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  165          ONESHOT   [0x08]    164      0  idx_to_ptr=0
 *  166            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  167            UINT[0x01]           -      -  0 (0x00000000)
 *  168          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  169          OPEN_CALL[0x07]      3      0  SET_BRIDGE_MODE hash=0x5C071EC1
 *  170          ONESHOT   [0x08]    169      6  idx_to_ptr=0
 *  171            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  172          CLOSE[0x06]          0      -  (end SET_BRIDGE_MODE)
 *  173          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  174          ONESHOT   [0x08]    173      1  idx_to_ptr=0
 *  175            STR_IDX[0x0D]        7     11  "MOTOR: Idle"
 *  176          CLOSE[0x06]          0      -  (end SE_LOG)
 *  177          OPEN_CALL[0x07]     39      0  SE_COND hash=0xCE0831A2
 *  178          MAIN      [0x09]    177      8  idx_to_ptr=0
 *  179            OPEN_CALL[0x07]     12      0  SE_SEQUENCE hash=0xEC3EE7BF
 *  180            MAIN      [0x09]    179      9  idx_to_ptr=0
 *  181              OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  182              ONESHOT   [0x08]    181      0  idx_to_ptr=0
 *  183                FIELD[0x0B]         88      4  open_request (off=0x0058, hash=0x39BCAB0F)
 *  184                UINT[0x01]           -      -  0 (0x00000000)
 *  185              CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  186              OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  187              ONESHOT   [0x08]    186      0  idx_to_ptr=0
 *  188                FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *  189                UINT[0x01]           -      -  1 (0x00000001)
 *  190              CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  191            CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 *  192            OPEN_CALL[0x07]     12      0  SE_SEQUENCE hash=0xEC3EE7BF
 *  193            MAIN      [0x09]    192      9  idx_to_ptr=0
 *  194              OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  195              ONESHOT   [0x08]    194      0  idx_to_ptr=0
 *  196                FIELD[0x0B]         92      4  close_request (off=0x005C, hash=0x2C02810D)
 *  197                UINT[0x01]           -      -  0 (0x00000000)
 *  198              CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  199              OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  200              ONESHOT   [0x08]    199      0  idx_to_ptr=0
 *  201                FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *  202                UINT[0x01]           -      -  2 (0x00000002)
 *  203              CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  204            CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 *  205            OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  206            ONESHOT   [0x08]    205      0  idx_to_ptr=0
 *  207              FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *  208              UINT[0x01]           -      -  4 (0x00000004)
 *  209            CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  210            OPEN_CALL[0x07]      2      0  SE_TRUE hash=0x0C125BC2
 *  211            PRED      [0x0A]    210      0  idx_to_ptr=0
 *  212            CLOSE[0x06]          0      -  (end SE_TRUE)
 *  213            OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_HALT hash=0x4AC84487
 *  214            MAIN      [0x09]    213      6  idx_to_ptr=0
 *  215            CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_HALT)
 *  216          CLOSE[0x06]          0      -  (end SE_COND)
 *  217        CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  218        INT[0x00]            -      -  1 (0x00000001)
 *  219        OPEN_CALL[0x07]    238      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  220        MAIN      [0x09]    219      2  idx_to_ptr=0
 *  221          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  222          ONESHOT   [0x08]    221      1  idx_to_ptr=0
 *  223            STR_IDX[0x0D]        8     21  "MOTOR: Opening window"
 *  224          CLOSE[0x06]          0      -  (end SE_LOG)
 *  225          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  226          ONESHOT   [0x08]    225      0  idx_to_ptr=0
 *  227            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  228            UINT[0x01]           -      -  1 (0x00000001)
 *  229          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  230          OPEN_CALL[0x07]      3      0  SET_BRIDGE_MODE hash=0x5C071EC1
 *  231          ONESHOT   [0x08]    230      6  idx_to_ptr=0
 *  232            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  233          CLOSE[0x06]          0      -  (end SET_BRIDGE_MODE)
 *  234          OPEN_CALL[0x07]      3      0  SET_MOTOR_PWM hash=0x3572046E
 *  235          ONESHOT   [0x08]    234      7  idx_to_ptr=0
 *  236            FIELD[0x0B]         36      4  open_speed (off=0x0024, hash=0x46D7BAF5)
 *  237          CLOSE[0x06]          0      -  (end SET_MOTOR_PWM)
 *  238          OPEN_CALL[0x07]      2      0  ENABLE_MOTOR_TLE7269G hash=0x1F90BFFD
 *  239          ONESHOT   [0x08]    238      8  idx_to_ptr=0
 *  240          CLOSE[0x06]          0      -  (end ENABLE_MOTOR_TLE7269G)
 *  241          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  242          ONESHOT   [0x08]    241      0  idx_to_ptr=0
 *  243            FIELD[0x0B]         12      4  motor_enabled (off=0x000C, hash=0x6BDC382C)
 *  244            UINT[0x01]           -      -  1 (0x00000001)
 *  245          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  246          OPEN_CALL[0x07]     99      0  SE_FORK hash=0x0A24332A
 *  247          MAIN      [0x09]    246      1  idx_to_ptr=0
 *  248            OPEN_CALL[0x07]     34      0  SE_WHILE hash=0xA08B6DD3
 *  249            MAIN      [0x09]    248     10  idx_to_ptr=0
 *  250              OPEN_CALL[0x07]     31      0  SE_FORK_JOIN hash=0xE404E1CF
 *  251              MAIN      [0x09]    250     11  idx_to_ptr=0
 *  252                OPEN_CALL[0x07]     28      0  SE_IF_THEN_ELSE hash=0x1E860193
 *  253                MAIN      [0x09]    252     12  idx_to_ptr=0
 *  254                  OPEN_CALL[0x07]      4      0  SE_FIELD_GT hash=0x10F63374
 *  255                  PRED      [0x0A]    254      1  idx_to_ptr=0
 *  256                    FIELD[0x0B]         16      4  motor_current (off=0x0010, hash=0x34A7FD08)
 *  257                    UINT[0x01]           -      -  5 (0x00000005)
 *  258                  CLOSE[0x06]          0      -  (end SE_FIELD_GT)
 *  259                  OPEN_CALL[0x07]     17      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  260                  MAIN      [0x09]    259      2  idx_to_ptr=0
 *  261                    OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  262                    ONESHOT   [0x08]    261      0  idx_to_ptr=0
 *  263                      FIELD[0x0B]         72      4  over_current (off=0x0048, hash=0x37F0CAB5)
 *  264                      UINT[0x01]           -      -  1 (0x00000001)
 *  265                    CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  266                    OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  267                    ONESHOT   [0x08]    266      4  idx_to_ptr=0
 *  268                      UINT[0x01]           -      -  0 (0x00000000)
 *  269                      UINT[0x01]           -      -  16 (0x00000010)
 *  270                      FIELD[0x0B]         72      4  over_current (off=0x0048, hash=0x37F0CAB5)
 *  271                    CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  272                    OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  273                    ONESHOT   [0x08]    272      1  idx_to_ptr=0
 *  274                      STR_IDX[0x0D]        9     28  "FAULT: Over-current detected"
 *  275                    CLOSE[0x06]          0      -  (end SE_LOG)
 *  276                  CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  277                  OPEN_CALL[0x07]      2      0  SE_NOP hash=0x080C2B37
 *  278                  ONESHOT   [0x08]    277      9  idx_to_ptr=0
 *  279                  CLOSE[0x06]          0      -  (end SE_NOP)
 *  280                CLOSE[0x06]          0      -  (end SE_IF_THEN_ELSE)
 *  281              CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *  282            CLOSE[0x06]          0      -  (end SE_WHILE)
 *  283            OPEN_CALL[0x07]     28      0  SE_WHILE hash=0xA08B6DD3
 *  284            MAIN      [0x09]    283     10  idx_to_ptr=0
 *  285              OPEN_CALL[0x07]     25      0  SE_FORK_JOIN hash=0xE404E1CF
 *  286              MAIN      [0x09]    285     11  idx_to_ptr=0
 *  287                OPEN_CALL[0x07]     22      0  SE_IF_THEN_ELSE hash=0x1E860193
 *  288                MAIN      [0x09]    287     12  idx_to_ptr=0
 *  289                  OPEN_CALL[0x07]      2      0  CHECK_LIMIT_SWITCH_OPEN hash=0x2B37E8C9
 *  290                  PRED      [0x0A]    289      2  idx_to_ptr=0
 *  291                  CLOSE[0x06]          0      -  (end CHECK_LIMIT_SWITCH_OPEN)
 *  292                  OPEN_CALL[0x07]     13      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  293                  MAIN      [0x09]    292      2  idx_to_ptr=0
 *  294                    OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  295                    ONESHOT   [0x08]    294      0  idx_to_ptr=0
 *  296                      FIELD[0x0B]         56      4  fully_open (off=0x0038, hash=0x81F715A8)
 *  297                      UINT[0x01]           -      -  1 (0x00000001)
 *  298                    CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  299                    OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  300                    ONESHOT   [0x08]    299      4  idx_to_ptr=0
 *  301                      UINT[0x01]           -      -  0 (0x00000000)
 *  302                      UINT[0x01]           -      -  18 (0x00000012)
 *  303                      FIELD[0x0B]         56      4  fully_open (off=0x0038, hash=0x81F715A8)
 *  304                    CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  305                  CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  306                  OPEN_CALL[0x07]      2      0  SE_NOP hash=0x080C2B37
 *  307                  ONESHOT   [0x08]    306      9  idx_to_ptr=0
 *  308                  CLOSE[0x06]          0      -  (end SE_NOP)
 *  309                CLOSE[0x06]          0      -  (end SE_IF_THEN_ELSE)
 *  310              CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *  311            CLOSE[0x06]          0      -  (end SE_WHILE)
 *  312            OPEN_CALL[0x07]     32      0  SE_WHILE hash=0xA08B6DD3
 *  313            MAIN      [0x09]    312     10  idx_to_ptr=0
 *  314              OPEN_CALL[0x07]     29      0  SE_FORK_JOIN hash=0xE404E1CF
 *  315              MAIN      [0x09]    314     11  idx_to_ptr=0
 *  316                OPEN_CALL[0x07]     26      0  SE_IF_THEN_ELSE hash=0x1E860193
 *  317                MAIN      [0x09]    316     12  idx_to_ptr=0
 *  318                  OPEN_CALL[0x07]      2      0  CHECK_MOTOR_STALL hash=0x772EDA2C
 *  319                  PRED      [0x0A]    318      3  idx_to_ptr=0
 *  320                  CLOSE[0x06]          0      -  (end CHECK_MOTOR_STALL)
 *  321                  OPEN_CALL[0x07]     17      0  SE_SEQUENCE hash=0xEC3EE7BF
 *  322                  MAIN      [0x09]    321      9  idx_to_ptr=0
 *  323                    OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  324                    ONESHOT   [0x08]    323      0  idx_to_ptr=0
 *  325                      FIELD[0x0B]         68      4  obstruction (off=0x0044, hash=0x1998554D)
 *  326                      UINT[0x01]           -      -  1 (0x00000001)
 *  327                    CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  328                    OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  329                    ONESHOT   [0x08]    328      4  idx_to_ptr=0
 *  330                      UINT[0x01]           -      -  0 (0x00000000)
 *  331                      UINT[0x01]           -      -  17 (0x00000011)
 *  332                      FIELD[0x0B]         68      4  obstruction (off=0x0044, hash=0x1998554D)
 *  333                    CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  334                    OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  335                    ONESHOT   [0x08]    334      1  idx_to_ptr=0
 *  336                      STR_IDX[0x0D]       10     27  "FAULT: Obstruction detected"
 *  337                    CLOSE[0x06]          0      -  (end SE_LOG)
 *  338                  CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 *  339                  OPEN_CALL[0x07]      2      0  SE_NOP hash=0x080C2B37
 *  340                  ONESHOT   [0x08]    339      9  idx_to_ptr=0
 *  341                  CLOSE[0x06]          0      -  (end SE_NOP)
 *  342                CLOSE[0x06]          0      -  (end SE_IF_THEN_ELSE)
 *  343              CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *  344            CLOSE[0x06]          0      -  (end SE_WHILE)
 *  345          CLOSE[0x06]          0      -  (end SE_FORK)
 *  346          OPEN_CALL[0x07]     42      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  347          MAIN      [0x09]    346      2  idx_to_ptr=0
 *  348            OPEN_CALL[0x07]      8      0  SE_VERIFY_AND_CHECK_ELAPSED_TIME hash=0x0D3E0C4F
 *  349            MAIN+PTR  [0x89]    348     13  idx_to_ptr=0
 *  350              FLOAT[0x02]          -      -  30
 *  351              INT[0x00]            -      -  0 (0x00000000)
 *  352              OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  353              ONESHOT   [0x08]    352      1  idx_to_ptr=0
 *  354                STR_IDX[0x0D]       11     29  "TIMEOUT: Opening exceeded 30s"
 *  355              CLOSE[0x06]          0      -  (end SE_LOG)
 *  356            CLOSE[0x06]          0      -  (end SE_VERIFY_AND_CHECK_ELAPSED_TIME)
 *  357            OPEN_CALL[0x07]     30      0  SE_WAIT hash=0xDD7F6663
 *  358            MAIN      [0x09]    357      3  idx_to_ptr=0
 *  359              OPEN_CALL[0x07]     27      0  SE_PRED_OR hash=0x0CF6212F
 *  360              PRED+SR   [0x4A]    359      4  idx_to_ptr=0
 *  361                OPEN_CALL[0x07]      4      0  SE_FIELD_EQ hash=0xD9FBED0D
 *  362                PRED      [0x0A]    361      5  idx_to_ptr=0
 *  363                  FIELD[0x0B]         56      4  fully_open (off=0x0038, hash=0x81F715A8)
 *  364                  UINT[0x01]           -      -  1 (0x00000001)
 *  365                CLOSE[0x06]          0      -  (end SE_FIELD_EQ)
 *  366                OPEN_CALL[0x07]      4      0  SE_FIELD_EQ hash=0xD9FBED0D
 *  367                PRED      [0x0A]    366      5  idx_to_ptr=0
 *  368                  FIELD[0x0B]         96      4  stop_request (off=0x0060, hash=0x97F05C03)
 *  369                  UINT[0x01]           -      -  1 (0x00000001)
 *  370                CLOSE[0x06]          0      -  (end SE_FIELD_EQ)
 *  371                OPEN_CALL[0x07]      4      0  SE_FIELD_EQ hash=0xD9FBED0D
 *  372                PRED      [0x0A]    371      5  idx_to_ptr=0
 *  373                  FIELD[0x0B]         72      4  over_current (off=0x0048, hash=0x37F0CAB5)
 *  374                  UINT[0x01]           -      -  1 (0x00000001)
 *  375                CLOSE[0x06]          0      -  (end SE_FIELD_EQ)
 *  376                OPEN_CALL[0x07]      4      0  SE_FIELD_EQ hash=0xD9FBED0D
 *  377                PRED      [0x0A]    376      5  idx_to_ptr=0
 *  378                  FIELD[0x0B]         68      4  obstruction (off=0x0044, hash=0x1998554D)
 *  379                  UINT[0x01]           -      -  1 (0x00000001)
 *  380                CLOSE[0x06]          0      -  (end SE_FIELD_EQ)
 *  381                OPEN_CALL[0x07]      4      0  SE_FIELD_EQ hash=0xD9FBED0D
 *  382                PRED      [0x0A]    381      5  idx_to_ptr=0
 *  383                  FIELD[0x0B]         64      4  emergency (off=0x0040, hash=0x75463942)
 *  384                  UINT[0x01]           -      -  1 (0x00000001)
 *  385                CLOSE[0x06]          0      -  (end SE_FIELD_EQ)
 *  386              CLOSE[0x06]          0      -  (end SE_PRED_OR)
 *  387            CLOSE[0x06]          0      -  (end SE_WAIT)
 *  388          CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  389          OPEN_CALL[0x07]      2      0  DISABLE_MOTOR_TLE7269G hash=0x9A0D92FA
 *  390          ONESHOT   [0x08]    389      5  idx_to_ptr=0
 *  391          CLOSE[0x06]          0      -  (end DISABLE_MOTOR_TLE7269G)
 *  392          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  393          ONESHOT   [0x08]    392      0  idx_to_ptr=0
 *  394            FIELD[0x0B]         12      4  motor_enabled (off=0x000C, hash=0x6BDC382C)
 *  395            UINT[0x01]           -      -  0 (0x00000000)
 *  396          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  397          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  398          ONESHOT   [0x08]    397      0  idx_to_ptr=0
 *  399            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  400            UINT[0x01]           -      -  3 (0x00000003)
 *  401          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  402          OPEN_CALL[0x07]      3      0  SET_BRIDGE_MODE hash=0x5C071EC1
 *  403          ONESHOT   [0x08]    402      6  idx_to_ptr=0
 *  404            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  405          CLOSE[0x06]          0      -  (end SET_BRIDGE_MODE)
 *  406          OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  407          MAIN+PTR  [0x89]    406     14  idx_to_ptr=1
 *  408            INT[0x00]            -      -  10 (0x0000000A)
 *  409          CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  410          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  411          ONESHOT   [0x08]    410      0  idx_to_ptr=0
 *  412            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  413            UINT[0x01]           -      -  0 (0x00000000)
 *  414          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  415          OPEN_CALL[0x07]      3      0  SET_BRIDGE_MODE hash=0x5C071EC1
 *  416          ONESHOT   [0x08]    415      6  idx_to_ptr=0
 *  417            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  418          CLOSE[0x06]          0      -  (end SET_BRIDGE_MODE)
 *  419          OPEN_CALL[0x07]      3      0  SEND_STATUS_MESSAGE hash=0x462235D6
 *  420          ONESHOT   [0x08]    419     10  idx_to_ptr=0
 *  421            STR_IDX[0x0D]       12      9  "DOOR_OPEN"
 *  422          CLOSE[0x06]          0      -  (end SEND_STATUS_MESSAGE)
 *  423          OPEN_CALL[0x07]     33      0  SE_COND hash=0xCE0831A2
 *  424          MAIN      [0x09]    423      8  idx_to_ptr=0
 *  425            OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  426            ONESHOT   [0x08]    425      0  idx_to_ptr=0
 *  427              FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *  428              UINT[0x01]           -      -  4 (0x00000004)
 *  429            CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  430            OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  431            ONESHOT   [0x08]    430      0  idx_to_ptr=0
 *  432              FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *  433              UINT[0x01]           -      -  4 (0x00000004)
 *  434            CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  435            OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  436            ONESHOT   [0x08]    435      0  idx_to_ptr=0
 *  437              FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *  438              UINT[0x01]           -      -  4 (0x00000004)
 *  439            CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  440            OPEN_CALL[0x07]      2      0  SE_TRUE hash=0x0C125BC2
 *  441            PRED      [0x0A]    440      0  idx_to_ptr=0
 *  442            CLOSE[0x06]          0      -  (end SE_TRUE)
 *  443            OPEN_CALL[0x07]     12      0  SE_SEQUENCE hash=0xEC3EE7BF
 *  444            MAIN      [0x09]    443      9  idx_to_ptr=0
 *  445              OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  446              ONESHOT   [0x08]    445      0  idx_to_ptr=0
 *  447                FIELD[0x0B]         96      4  stop_request (off=0x0060, hash=0x97F05C03)
 *  448                UINT[0x01]           -      -  0 (0x00000000)
 *  449              CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  450              OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  451              ONESHOT   [0x08]    450      0  idx_to_ptr=0
 *  452                FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *  453                UINT[0x01]           -      -  0 (0x00000000)
 *  454              CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  455            CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 *  456          CLOSE[0x06]          0      -  (end SE_COND)
 *  457        CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  458        INT[0x00]            -      -  2 (0x00000002)
 *  459        OPEN_CALL[0x07]    265      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  460        MAIN      [0x09]    459      2  idx_to_ptr=0
 *  461          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  462          ONESHOT   [0x08]    461      1  idx_to_ptr=0
 *  463            STR_IDX[0x0D]       13     21  "MOTOR: Closing window"
 *  464          CLOSE[0x06]          0      -  (end SE_LOG)
 *  465          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  466          ONESHOT   [0x08]    465      0  idx_to_ptr=0
 *  467            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  468            UINT[0x01]           -      -  2 (0x00000002)
 *  469          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  470          OPEN_CALL[0x07]      3      0  SET_BRIDGE_MODE hash=0x5C071EC1
 *  471          ONESHOT   [0x08]    470      6  idx_to_ptr=0
 *  472            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  473          CLOSE[0x06]          0      -  (end SET_BRIDGE_MODE)
 *  474          OPEN_CALL[0x07]      3      0  SET_MOTOR_PWM hash=0x3572046E
 *  475          ONESHOT   [0x08]    474      7  idx_to_ptr=0
 *  476            FIELD[0x0B]         40      4  close_speed (off=0x0028, hash=0x3826D73F)
 *  477          CLOSE[0x06]          0      -  (end SET_MOTOR_PWM)
 *  478          OPEN_CALL[0x07]      2      0  ENABLE_MOTOR_TLE7269G hash=0x1F90BFFD
 *  479          ONESHOT   [0x08]    478      8  idx_to_ptr=0
 *  480          CLOSE[0x06]          0      -  (end ENABLE_MOTOR_TLE7269G)
 *  481          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  482          ONESHOT   [0x08]    481      0  idx_to_ptr=0
 *  483            FIELD[0x0B]         12      4  motor_enabled (off=0x000C, hash=0x6BDC382C)
 *  484            UINT[0x01]           -      -  1 (0x00000001)
 *  485          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  486          OPEN_CALL[0x07]    113      0  SE_FORK hash=0x0A24332A
 *  487          MAIN      [0x09]    486      1  idx_to_ptr=0
 *  488            OPEN_CALL[0x07]     34      0  SE_WHILE hash=0xA08B6DD3
 *  489            MAIN      [0x09]    488     10  idx_to_ptr=0
 *  490              OPEN_CALL[0x07]     31      0  SE_FORK_JOIN hash=0xE404E1CF
 *  491              MAIN      [0x09]    490     11  idx_to_ptr=0
 *  492                OPEN_CALL[0x07]     28      0  SE_IF_THEN_ELSE hash=0x1E860193
 *  493                MAIN      [0x09]    492     12  idx_to_ptr=0
 *  494                  OPEN_CALL[0x07]      4      0  SE_FIELD_GT hash=0x10F63374
 *  495                  PRED      [0x0A]    494      1  idx_to_ptr=0
 *  496                    FIELD[0x0B]         16      4  motor_current (off=0x0010, hash=0x34A7FD08)
 *  497                    UINT[0x01]           -      -  5 (0x00000005)
 *  498                  CLOSE[0x06]          0      -  (end SE_FIELD_GT)
 *  499                  OPEN_CALL[0x07]     17      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  500                  MAIN      [0x09]    499      2  idx_to_ptr=0
 *  501                    OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  502                    ONESHOT   [0x08]    501      0  idx_to_ptr=0
 *  503                      FIELD[0x0B]         72      4  over_current (off=0x0048, hash=0x37F0CAB5)
 *  504                      UINT[0x01]           -      -  1 (0x00000001)
 *  505                    CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  506                    OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  507                    ONESHOT   [0x08]    506      4  idx_to_ptr=0
 *  508                      UINT[0x01]           -      -  0 (0x00000000)
 *  509                      UINT[0x01]           -      -  16 (0x00000010)
 *  510                      FIELD[0x0B]         72      4  over_current (off=0x0048, hash=0x37F0CAB5)
 *  511                    CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  512                    OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  513                    ONESHOT   [0x08]    512      1  idx_to_ptr=0
 *  514                      STR_IDX[0x0D]        9     28  "FAULT: Over-current detected"
 *  515                    CLOSE[0x06]          0      -  (end SE_LOG)
 *  516                  CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  517                  OPEN_CALL[0x07]      2      0  SE_NOP hash=0x080C2B37
 *  518                  ONESHOT   [0x08]    517      9  idx_to_ptr=0
 *  519                  CLOSE[0x06]          0      -  (end SE_NOP)
 *  520                CLOSE[0x06]          0      -  (end SE_IF_THEN_ELSE)
 *  521              CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *  522            CLOSE[0x06]          0      -  (end SE_WHILE)
 *  523            OPEN_CALL[0x07]     28      0  SE_WHILE hash=0xA08B6DD3
 *  524            MAIN      [0x09]    523     10  idx_to_ptr=0
 *  525              OPEN_CALL[0x07]     25      0  SE_FORK_JOIN hash=0xE404E1CF
 *  526              MAIN      [0x09]    525     11  idx_to_ptr=0
 *  527                OPEN_CALL[0x07]     22      0  SE_IF_THEN_ELSE hash=0x1E860193
 *  528                MAIN      [0x09]    527     12  idx_to_ptr=0
 *  529                  OPEN_CALL[0x07]      2      0  CHECK_LIMIT_SWITCH_CLOSED hash=0xECBB0205
 *  530                  PRED      [0x0A]    529      6  idx_to_ptr=0
 *  531                  CLOSE[0x06]          0      -  (end CHECK_LIMIT_SWITCH_CLOSED)
 *  532                  OPEN_CALL[0x07]     13      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  533                  MAIN      [0x09]    532      2  idx_to_ptr=0
 *  534                    OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  535                    ONESHOT   [0x08]    534      0  idx_to_ptr=0
 *  536                      FIELD[0x0B]         60      4  fully_closed (off=0x003C, hash=0x52AE64E0)
 *  537                      UINT[0x01]           -      -  1 (0x00000001)
 *  538                    CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  539                    OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  540                    ONESHOT   [0x08]    539      4  idx_to_ptr=0
 *  541                      UINT[0x01]           -      -  0 (0x00000000)
 *  542                      UINT[0x01]           -      -  19 (0x00000013)
 *  543                      FIELD[0x0B]         60      4  fully_closed (off=0x003C, hash=0x52AE64E0)
 *  544                    CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  545                  CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  546                  OPEN_CALL[0x07]      2      0  SE_NOP hash=0x080C2B37
 *  547                  ONESHOT   [0x08]    546      9  idx_to_ptr=0
 *  548                  CLOSE[0x06]          0      -  (end SE_NOP)
 *  549                CLOSE[0x06]          0      -  (end SE_IF_THEN_ELSE)
 *  550              CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *  551            CLOSE[0x06]          0      -  (end SE_WHILE)
 *  552            OPEN_CALL[0x07]     46      0  SE_WHILE hash=0xA08B6DD3
 *  553            MAIN      [0x09]    552     10  idx_to_ptr=0
 *  554              OPEN_CALL[0x07]     43      0  SE_FORK_JOIN hash=0xE404E1CF
 *  555              MAIN      [0x09]    554     11  idx_to_ptr=0
 *  556                OPEN_CALL[0x07]     40      0  SE_IF_THEN_ELSE hash=0x1E860193
 *  557                MAIN      [0x09]    556     12  idx_to_ptr=0
 *  558                  OPEN_CALL[0x07]      2      0  CHECK_MOTOR_STALL hash=0x772EDA2C
 *  559                  PRED      [0x0A]    558      3  idx_to_ptr=0
 *  560                  CLOSE[0x06]          0      -  (end CHECK_MOTOR_STALL)
 *  561                  OPEN_CALL[0x07]     31      0  SE_SEQUENCE hash=0xEC3EE7BF
 *  562                  MAIN      [0x09]    561      9  idx_to_ptr=0
 *  563                    OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  564                    ONESHOT   [0x08]    563      0  idx_to_ptr=0
 *  565                      FIELD[0x0B]         68      4  obstruction (off=0x0044, hash=0x1998554D)
 *  566                      UINT[0x01]           -      -  1 (0x00000001)
 *  567                    CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  568                    OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  569                    ONESHOT   [0x08]    568      4  idx_to_ptr=0
 *  570                      UINT[0x01]           -      -  0 (0x00000000)
 *  571                      UINT[0x01]           -      -  17 (0x00000011)
 *  572                      FIELD[0x0B]         68      4  obstruction (off=0x0044, hash=0x1998554D)
 *  573                    CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  574                    OPEN_CALL[0x07]     17      0  SE_SEQUENCE hash=0xEC3EE7BF
 *  575                    MAIN      [0x09]    574      9  idx_to_ptr=0
 *  576                      OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  577                      ONESHOT   [0x08]    576      0  idx_to_ptr=0
 *  578                        FIELD[0x0B]        104      4  auto_reverse_req (off=0x0068, hash=0x74D06EC8)
 *  579                        UINT[0x01]           -      -  1 (0x00000001)
 *  580                      CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  581                      OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  582                      ONESHOT   [0x08]    581      4  idx_to_ptr=0
 *  583                        UINT[0x01]           -      -  0 (0x00000000)
 *  584                        UINT[0x01]           -      -  20 (0x00000014)
 *  585                        FIELD[0x0B]        104      4  auto_reverse_req (off=0x0068, hash=0x74D06EC8)
 *  586                      CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  587                      OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  588                      ONESHOT   [0x08]    587      1  idx_to_ptr=0
 *  589                        STR_IDX[0x0D]       14     35  "FAULT: Obstruction - auto-reversing"
 *  590                      CLOSE[0x06]          0      -  (end SE_LOG)
 *  591                    CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 *  592                  CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 *  593                  OPEN_CALL[0x07]      2      0  SE_NOP hash=0x080C2B37
 *  594                  ONESHOT   [0x08]    593      9  idx_to_ptr=0
 *  595                  CLOSE[0x06]          0      -  (end SE_NOP)
 *  596                CLOSE[0x06]          0      -  (end SE_IF_THEN_ELSE)
 *  597              CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *  598            CLOSE[0x06]          0      -  (end SE_WHILE)
 *  599          CLOSE[0x06]          0      -  (end SE_FORK)
 *  600          OPEN_CALL[0x07]     42      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  601          MAIN      [0x09]    600      2  idx_to_ptr=0
 *  602            OPEN_CALL[0x07]      8      0  SE_VERIFY_AND_CHECK_ELAPSED_TIME hash=0x0D3E0C4F
 *  603            MAIN+PTR  [0x89]    602     13  idx_to_ptr=2
 *  604              FLOAT[0x02]          -      -  30
 *  605              INT[0x00]            -      -  0 (0x00000000)
 *  606              OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  607              ONESHOT   [0x08]    606      1  idx_to_ptr=0
 *  608                STR_IDX[0x0D]       15     29  "TIMEOUT: Closing exceeded 30s"
 *  609              CLOSE[0x06]          0      -  (end SE_LOG)
 *  610            CLOSE[0x06]          0      -  (end SE_VERIFY_AND_CHECK_ELAPSED_TIME)
 *  611            OPEN_CALL[0x07]     30      0  SE_WAIT hash=0xDD7F6663
 *  612            MAIN      [0x09]    611      3  idx_to_ptr=0
 *  613              OPEN_CALL[0x07]     27      0  SE_PRED_OR hash=0x0CF6212F
 *  614              PRED+SR   [0x4A]    613      4  idx_to_ptr=0
 *  615                OPEN_CALL[0x07]      4      0  SE_FIELD_EQ hash=0xD9FBED0D
 *  616                PRED      [0x0A]    615      5  idx_to_ptr=0
 *  617                  FIELD[0x0B]         60      4  fully_closed (off=0x003C, hash=0x52AE64E0)
 *  618                  UINT[0x01]           -      -  1 (0x00000001)
 *  619                CLOSE[0x06]          0      -  (end SE_FIELD_EQ)
 *  620                OPEN_CALL[0x07]      4      0  SE_FIELD_EQ hash=0xD9FBED0D
 *  621                PRED      [0x0A]    620      5  idx_to_ptr=0
 *  622                  FIELD[0x0B]         96      4  stop_request (off=0x0060, hash=0x97F05C03)
 *  623                  UINT[0x01]           -      -  1 (0x00000001)
 *  624                CLOSE[0x06]          0      -  (end SE_FIELD_EQ)
 *  625                OPEN_CALL[0x07]      4      0  SE_FIELD_EQ hash=0xD9FBED0D
 *  626                PRED      [0x0A]    625      5  idx_to_ptr=0
 *  627                  FIELD[0x0B]         72      4  over_current (off=0x0048, hash=0x37F0CAB5)
 *  628                  UINT[0x01]           -      -  1 (0x00000001)
 *  629                CLOSE[0x06]          0      -  (end SE_FIELD_EQ)
 *  630                OPEN_CALL[0x07]      4      0  SE_FIELD_EQ hash=0xD9FBED0D
 *  631                PRED      [0x0A]    630      5  idx_to_ptr=0
 *  632                  FIELD[0x0B]         68      4  obstruction (off=0x0044, hash=0x1998554D)
 *  633                  UINT[0x01]           -      -  1 (0x00000001)
 *  634                CLOSE[0x06]          0      -  (end SE_FIELD_EQ)
 *  635                OPEN_CALL[0x07]      4      0  SE_FIELD_EQ hash=0xD9FBED0D
 *  636                PRED      [0x0A]    635      5  idx_to_ptr=0
 *  637                  FIELD[0x0B]         64      4  emergency (off=0x0040, hash=0x75463942)
 *  638                  UINT[0x01]           -      -  1 (0x00000001)
 *  639                CLOSE[0x06]          0      -  (end SE_FIELD_EQ)
 *  640              CLOSE[0x06]          0      -  (end SE_PRED_OR)
 *  641            CLOSE[0x06]          0      -  (end SE_WAIT)
 *  642          CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  643          OPEN_CALL[0x07]      2      0  DISABLE_MOTOR_TLE7269G hash=0x9A0D92FA
 *  644          ONESHOT   [0x08]    643      5  idx_to_ptr=0
 *  645          CLOSE[0x06]          0      -  (end DISABLE_MOTOR_TLE7269G)
 *  646          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  647          ONESHOT   [0x08]    646      0  idx_to_ptr=0
 *  648            FIELD[0x0B]         12      4  motor_enabled (off=0x000C, hash=0x6BDC382C)
 *  649            UINT[0x01]           -      -  0 (0x00000000)
 *  650          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  651          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  652          ONESHOT   [0x08]    651      0  idx_to_ptr=0
 *  653            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  654            UINT[0x01]           -      -  3 (0x00000003)
 *  655          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  656          OPEN_CALL[0x07]      3      0  SET_BRIDGE_MODE hash=0x5C071EC1
 *  657          ONESHOT   [0x08]    656      6  idx_to_ptr=0
 *  658            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  659          CLOSE[0x06]          0      -  (end SET_BRIDGE_MODE)
 *  660          OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  661          MAIN+PTR  [0x89]    660     14  idx_to_ptr=3
 *  662            INT[0x00]            -      -  10 (0x0000000A)
 *  663          CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  664          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  665          ONESHOT   [0x08]    664      0  idx_to_ptr=0
 *  666            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  667            UINT[0x01]           -      -  0 (0x00000000)
 *  668          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  669          OPEN_CALL[0x07]      3      0  SET_BRIDGE_MODE hash=0x5C071EC1
 *  670          ONESHOT   [0x08]    669      6  idx_to_ptr=0
 *  671            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  672          CLOSE[0x06]          0      -  (end SET_BRIDGE_MODE)
 *  673          OPEN_CALL[0x07]      3      0  SEND_STATUS_MESSAGE hash=0x462235D6
 *  674          ONESHOT   [0x08]    673     10  idx_to_ptr=0
 *  675            STR_IDX[0x0D]       16     11  "DOOR_CLOSED"
 *  676          CLOSE[0x06]          0      -  (end SEND_STATUS_MESSAGE)
 *  677          OPEN_CALL[0x07]     46      0  SE_COND hash=0xCE0831A2
 *  678          MAIN      [0x09]    677      8  idx_to_ptr=0
 *  679            OPEN_CALL[0x07]     17      0  SE_SEQUENCE hash=0xEC3EE7BF
 *  680            MAIN      [0x09]    679      9  idx_to_ptr=0
 *  681              OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  682              ONESHOT   [0x08]    681      0  idx_to_ptr=0
 *  683                FIELD[0x0B]        104      4  auto_reverse_req (off=0x0068, hash=0x74D06EC8)
 *  684                UINT[0x01]           -      -  0 (0x00000000)
 *  685              CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  686              OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  687              ONESHOT   [0x08]    686      0  idx_to_ptr=0
 *  688                FIELD[0x0B]         68      4  obstruction (off=0x0044, hash=0x1998554D)
 *  689                UINT[0x01]           -      -  0 (0x00000000)
 *  690              CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  691              OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  692              ONESHOT   [0x08]    691      0  idx_to_ptr=0
 *  693                FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *  694                UINT[0x01]           -      -  3 (0x00000003)
 *  695              CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  696            CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 *  697            OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  698            ONESHOT   [0x08]    697      0  idx_to_ptr=0
 *  699              FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *  700              UINT[0x01]           -      -  4 (0x00000004)
 *  701            CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  702            OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  703            ONESHOT   [0x08]    702      0  idx_to_ptr=0
 *  704              FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *  705              UINT[0x01]           -      -  4 (0x00000004)
 *  706            CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  707            OPEN_CALL[0x07]      2      0  SE_TRUE hash=0x0C125BC2
 *  708            PRED      [0x0A]    707      0  idx_to_ptr=0
 *  709            CLOSE[0x06]          0      -  (end SE_TRUE)
 *  710            OPEN_CALL[0x07]     12      0  SE_SEQUENCE hash=0xEC3EE7BF
 *  711            MAIN      [0x09]    710      9  idx_to_ptr=0
 *  712              OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  713              ONESHOT   [0x08]    712      0  idx_to_ptr=0
 *  714                FIELD[0x0B]         96      4  stop_request (off=0x0060, hash=0x97F05C03)
 *  715                UINT[0x01]           -      -  0 (0x00000000)
 *  716              CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  717              OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  718              ONESHOT   [0x08]    717      0  idx_to_ptr=0
 *  719                FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *  720                UINT[0x01]           -      -  0 (0x00000000)
 *  721              CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  722            CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 *  723          CLOSE[0x06]          0      -  (end SE_COND)
 *  724        CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  725        INT[0x00]            -      -  3 (0x00000003)
 *  726        OPEN_CALL[0x07]     76      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  727        MAIN      [0x09]    726      2  idx_to_ptr=0
 *  728          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  729          ONESHOT   [0x08]    728      1  idx_to_ptr=0
 *  730            STR_IDX[0x0D]       17     37  "MOTOR: Auto-reverse after obstruction"
 *  731          CLOSE[0x06]          0      -  (end SE_LOG)
 *  732          OPEN_CALL[0x07]      2      0  DISABLE_MOTOR_TLE7269G hash=0x9A0D92FA
 *  733          ONESHOT   [0x08]    732      5  idx_to_ptr=0
 *  734          CLOSE[0x06]          0      -  (end DISABLE_MOTOR_TLE7269G)
 *  735          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  736          ONESHOT   [0x08]    735      0  idx_to_ptr=0
 *  737            FIELD[0x0B]         12      4  motor_enabled (off=0x000C, hash=0x6BDC382C)
 *  738            UINT[0x01]           -      -  0 (0x00000000)
 *  739          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  740          OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  741          MAIN+PTR  [0x89]    740     14  idx_to_ptr=4
 *  742            INT[0x00]            -      -  5 (0x00000005)
 *  743          CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  744          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  745          ONESHOT   [0x08]    744      0  idx_to_ptr=0
 *  746            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  747            UINT[0x01]           -      -  1 (0x00000001)
 *  748          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  749          OPEN_CALL[0x07]      3      0  SET_BRIDGE_MODE hash=0x5C071EC1
 *  750          ONESHOT   [0x08]    749      6  idx_to_ptr=0
 *  751            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  752          CLOSE[0x06]          0      -  (end SET_BRIDGE_MODE)
 *  753          OPEN_CALL[0x07]      3      0  SET_MOTOR_PWM hash=0x3572046E
 *  754          ONESHOT   [0x08]    753      7  idx_to_ptr=0
 *  755            INT[0x00]            -      -  100 (0x00000064)
 *  756          CLOSE[0x06]          0      -  (end SET_MOTOR_PWM)
 *  757          OPEN_CALL[0x07]      2      0  ENABLE_MOTOR_TLE7269G hash=0x1F90BFFD
 *  758          ONESHOT   [0x08]    757      8  idx_to_ptr=0
 *  759          CLOSE[0x06]          0      -  (end ENABLE_MOTOR_TLE7269G)
 *  760          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  761          ONESHOT   [0x08]    760      0  idx_to_ptr=0
 *  762            FIELD[0x0B]         12      4  motor_enabled (off=0x000C, hash=0x6BDC382C)
 *  763            UINT[0x01]           -      -  1 (0x00000001)
 *  764          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  765          OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  766          MAIN+PTR  [0x89]    765     14  idx_to_ptr=5
 *  767            INT[0x00]            -      -  50 (0x00000032)
 *  768          CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  769          OPEN_CALL[0x07]      2      0  DISABLE_MOTOR_TLE7269G hash=0x9A0D92FA
 *  770          ONESHOT   [0x08]    769      5  idx_to_ptr=0
 *  771          CLOSE[0x06]          0      -  (end DISABLE_MOTOR_TLE7269G)
 *  772          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  773          ONESHOT   [0x08]    772      0  idx_to_ptr=0
 *  774            FIELD[0x0B]         12      4  motor_enabled (off=0x000C, hash=0x6BDC382C)
 *  775            UINT[0x01]           -      -  0 (0x00000000)
 *  776          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  777          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  778          ONESHOT   [0x08]    777      0  idx_to_ptr=0
 *  779            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  780            UINT[0x01]           -      -  0 (0x00000000)
 *  781          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  782          OPEN_CALL[0x07]      3      0  SET_BRIDGE_MODE hash=0x5C071EC1
 *  783          ONESHOT   [0x08]    782      6  idx_to_ptr=0
 *  784            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  785          CLOSE[0x06]          0      -  (end SET_BRIDGE_MODE)
 *  786          OPEN_CALL[0x07]      3      0  SEND_STATUS_MESSAGE hash=0x462235D6
 *  787          ONESHOT   [0x08]    786     10  idx_to_ptr=0
 *  788            STR_IDX[0x0D]       18     20  "OBSTRUCTION_DETECTED"
 *  789          CLOSE[0x06]          0      -  (end SEND_STATUS_MESSAGE)
 *  790          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  791          ONESHOT   [0x08]    790      1  idx_to_ptr=0
 *  792            STR_IDX[0x0D]       19     28  "MOTOR: Auto-reverse complete"
 *  793          CLOSE[0x06]          0      -  (end SE_LOG)
 *  794          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  795          ONESHOT   [0x08]    794      0  idx_to_ptr=0
 *  796            FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *  797            UINT[0x01]           -      -  0 (0x00000000)
 *  798          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  799          OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  800          MAIN      [0x09]    799      5  idx_to_ptr=0
 *  801          CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  802        CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  803        INT[0x00]            -      -  4 (0x00000004)
 *  804        OPEN_CALL[0x07]     67      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  805        MAIN      [0x09]    804      2  idx_to_ptr=0
 *  806          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  807          ONESHOT   [0x08]    806      1  idx_to_ptr=0
 *  808            STR_IDX[0x0D]       20     21  "MOTOR: EMERGENCY STOP"
 *  809          CLOSE[0x06]          0      -  (end SE_LOG)
 *  810          OPEN_CALL[0x07]      2      0  DISABLE_MOTOR_TLE7269G hash=0x9A0D92FA
 *  811          ONESHOT   [0x08]    810      5  idx_to_ptr=0
 *  812          CLOSE[0x06]          0      -  (end DISABLE_MOTOR_TLE7269G)
 *  813          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  814          ONESHOT   [0x08]    813      0  idx_to_ptr=0
 *  815            FIELD[0x0B]         12      4  motor_enabled (off=0x000C, hash=0x6BDC382C)
 *  816            UINT[0x01]           -      -  0 (0x00000000)
 *  817          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  818          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  819          ONESHOT   [0x08]    818      0  idx_to_ptr=0
 *  820            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  821            UINT[0x01]           -      -  0 (0x00000000)
 *  822          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  823          OPEN_CALL[0x07]      3      0  SET_BRIDGE_MODE hash=0x5C071EC1
 *  824          ONESHOT   [0x08]    823      6  idx_to_ptr=0
 *  825            FIELD[0x0B]          4      4  bridge_mode (off=0x0004, hash=0x03BEC4CA)
 *  826          CLOSE[0x06]          0      -  (end SET_BRIDGE_MODE)
 *  827          OPEN_CALL[0x07]      3      0  SEND_STATUS_MESSAGE hash=0x462235D6
 *  828          ONESHOT   [0x08]    827     10  idx_to_ptr=0
 *  829            STR_IDX[0x0D]       21     17  "EMERGENCY_STOPPED"
 *  830          CLOSE[0x06]          0      -  (end SEND_STATUS_MESSAGE)
 *  831          OPEN_CALL[0x07]      2      0  SE_WAIT hash=0xDD7F6663
 *  832          MAIN      [0x09]    831      3  idx_to_ptr=0
 *  833          CLOSE[0x06]          0      -  (end SE_WAIT)
 *  834          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  835          ONESHOT   [0x08]    834      1  idx_to_ptr=0
 *  836            STR_IDX[0x0D]       22     28  "MOTOR: Manual reset received"
 *  837          CLOSE[0x06]          0      -  (end SE_LOG)
 *  838          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  839          ONESHOT   [0x08]    838      0  idx_to_ptr=0
 *  840            FIELD[0x0B]         64      4  emergency (off=0x0040, hash=0x75463942)
 *  841            UINT[0x01]           -      -  0 (0x00000000)
 *  842          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  843          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  844          ONESHOT   [0x08]    843      0  idx_to_ptr=0
 *  845            FIELD[0x0B]         72      4  over_current (off=0x0048, hash=0x37F0CAB5)
 *  846            UINT[0x01]           -      -  0 (0x00000000)
 *  847          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  848          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  849          ONESHOT   [0x08]    848      0  idx_to_ptr=0
 *  850            FIELD[0x0B]         68      4  obstruction (off=0x0044, hash=0x1998554D)
 *  851            UINT[0x01]           -      -  0 (0x00000000)
 *  852          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  853          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  854          ONESHOT   [0x08]    853      0  idx_to_ptr=0
 *  855            FIELD[0x0B]         80      4  manual_reset (off=0x0050, hash=0x8E34B593)
 *  856            UINT[0x01]           -      -  0 (0x00000000)
 *  857          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  858          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  859          ONESHOT   [0x08]    858      0  idx_to_ptr=0
 *  860            FIELD[0x0B]        104      4  auto_reverse_req (off=0x0068, hash=0x74D06EC8)
 *  861            UINT[0x01]           -      -  0 (0x00000000)
 *  862          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  863          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  864          ONESHOT   [0x08]    863      0  idx_to_ptr=0
 *  865            FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *  866            UINT[0x01]           -      -  0 (0x00000000)
 *  867          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  868          OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  869          MAIN      [0x09]    868      5  idx_to_ptr=0
 *  870          CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  871        CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  872        INT[0x00]            -      -  -1 (0xFFFFFFFF)
 *  873        OPEN_CALL[0x07]     14      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  874        MAIN      [0x09]    873      2  idx_to_ptr=0
 *  875          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  876          ONESHOT   [0x08]    875      1  idx_to_ptr=0
 *  877            STR_IDX[0x0D]       23     41  "MOTOR: Invalid state - entering emerg..."
 *  878          CLOSE[0x06]          0      -  (end SE_LOG)
 *  879          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  880          ONESHOT   [0x08]    879      0  idx_to_ptr=0
 *  881            FIELD[0x0B]          0      4  motor_state (off=0x0000, hash=0x7EFCE2D8)
 *  882            UINT[0x01]           -      -  4 (0x00000004)
 *  883          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  884          OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  885          MAIN      [0x09]    884      5  idx_to_ptr=0
 *  886          CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  887        CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  888      CLOSE[0x06]          0      -  (end SE_STATE_MACHINE)
 *  889      OPEN_CALL[0x07]     47      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  890      MAIN      [0x09]    889      2  idx_to_ptr=0
 *  891        OPEN_CALL[0x07]     14      0  SE_WAIT hash=0xDD7F6663
 *  892        MAIN      [0x09]    891      3  idx_to_ptr=0
 *  893          OPEN_CALL[0x07]     11      0  SE_PRED_OR hash=0x0CF6212F
 *  894          PRED+SR   [0x4A]    893      4  idx_to_ptr=0
 *  895            OPEN_CALL[0x07]      4      0  SE_FIELD_EQ hash=0xD9FBED0D
 *  896            PRED      [0x0A]    895      5  idx_to_ptr=0
 *  897              FIELD[0x0B]        100      4  status_request (off=0x0064, hash=0xDCC3E951)
 *  898              UINT[0x01]           -      -  1 (0x00000001)
 *  899            CLOSE[0x06]          0      -  (end SE_FIELD_EQ)
 *  900            OPEN_CALL[0x07]      3      0  SE_CHECK_EVENT hash=0x80659F81
 *  901            PRED      [0x0A]    900      7  idx_to_ptr=0
 *  902              INT[0x00]            -      -  32 (0x00000020)
 *  903            CLOSE[0x06]          0      -  (end SE_CHECK_EVENT)
 *  904          CLOSE[0x06]          0      -  (end SE_PRED_OR)
 *  905        CLOSE[0x06]          0      -  (end SE_WAIT)
 *  906        OPEN_CALL[0x07]      2      0  READ_DIAGNOSTICS_TLE7269G hash=0xD1C8709B
 *  907        ONESHOT   [0x08]    906     11  idx_to_ptr=0
 *  908        CLOSE[0x06]          0      -  (end READ_DIAGNOSTICS_TLE7269G)
 *  909        OPEN_CALL[0x07]      2      0  READ_CURRENT_POSITION hash=0xB62BA5BB
 *  910        ONESHOT   [0x08]    909     12  idx_to_ptr=0
 *  911        CLOSE[0x06]          0      -  (end READ_CURRENT_POSITION)
 *  912        OPEN_CALL[0x07]      2      0  READ_MOTOR_CURRENT hash=0x3DADDF65
 *  913        ONESHOT   [0x08]    912     13  idx_to_ptr=0
 *  914        CLOSE[0x06]          0      -  (end READ_MOTOR_CURRENT)
 *  915        OPEN_CALL[0x07]      2      0  READ_TEMPERATURE hash=0x0B55B0E4
 *  916        ONESHOT   [0x08]    915     14  idx_to_ptr=0
 *  917        CLOSE[0x06]          0      -  (end READ_TEMPERATURE)
 *  918        OPEN_CALL[0x07]      2      0  ASSEMBLE_STATUS_MESSAGE hash=0x199FBF58
 *  919        ONESHOT   [0x08]    918     15  idx_to_ptr=0
 *  920        CLOSE[0x06]          0      -  (end ASSEMBLE_STATUS_MESSAGE)
 *  921        OPEN_CALL[0x07]      2      0  SEND_SERIAL_STATUS hash=0x5EA6EF23
 *  922        ONESHOT   [0x08]    921     16  idx_to_ptr=0
 *  923        CLOSE[0x06]          0      -  (end SEND_SERIAL_STATUS)
 *  924        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  925        ONESHOT   [0x08]    924      0  idx_to_ptr=0
 *  926          FIELD[0x0B]        100      4  status_request (off=0x0064, hash=0xDCC3E951)
 *  927          UINT[0x01]           -      -  0 (0x00000000)
 *  928        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  929        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  930        ONESHOT   [0x08]    929      1  idx_to_ptr=0
 *  931          STR_IDX[0x0D]       24     19  "STATUS: Report sent"
 *  932        CLOSE[0x06]          0      -  (end SE_LOG)
 *  933        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  934        MAIN      [0x09]    933      5  idx_to_ptr=0
 *  935        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  936      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  937      OPEN_CALL[0x07]    125      0  SE_FORK hash=0x0A24332A
 *  938      MAIN      [0x09]    937      1  idx_to_ptr=0
 *  939        OPEN_CALL[0x07]     40      0  SE_WHILE hash=0xA08B6DD3
 *  940        MAIN      [0x09]    939     10  idx_to_ptr=0
 *  941          OPEN_CALL[0x07]     37      0  SE_FORK_JOIN hash=0xE404E1CF
 *  942          MAIN      [0x09]    941     11  idx_to_ptr=0
 *  943            OPEN_CALL[0x07]     34      0  SE_IF_THEN_ELSE hash=0x1E860193
 *  944            MAIN      [0x09]    943     12  idx_to_ptr=0
 *  945              OPEN_CALL[0x07]      4      0  SE_FIELD_GT hash=0x10F63374
 *  946              PRED      [0x0A]    945      1  idx_to_ptr=0
 *  947                FIELD[0x0B]         28      4  temperature (off=0x001C, hash=0xE9F2A935)
 *  948                UINT[0x01]           -      -  85 (0x00000055)
 *  949              CLOSE[0x06]          0      -  (end SE_FIELD_GT)
 *  950              OPEN_CALL[0x07]     23      0  SE_SEQUENCE hash=0xEC3EE7BF
 *  951              MAIN      [0x09]    950      9  idx_to_ptr=0
 *  952                OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  953                ONESHOT   [0x08]    952      1  idx_to_ptr=0
 *  954                  STR_IDX[0x0D]       25     23  "DIAG: Thermal shutdown!"
 *  955                CLOSE[0x06]          0      -  (end SE_LOG)
 *  956                OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  957                ONESHOT   [0x08]    956      4  idx_to_ptr=0
 *  958                  UINT[0x01]           -      -  0 (0x00000000)
 *  959                  UINT[0x01]           -      -  22 (0x00000016)
 *  960                  FIELD[0x0B]         28      4  temperature (off=0x001C, hash=0xE9F2A935)
 *  961                CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  962                OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  963                ONESHOT   [0x08]    962      0  idx_to_ptr=0
 *  964                  FIELD[0x0B]         64      4  emergency (off=0x0040, hash=0x75463942)
 *  965                  UINT[0x01]           -      -  1 (0x00000001)
 *  966                CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  967                OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  968                ONESHOT   [0x08]    967      4  idx_to_ptr=0
 *  969                  UINT[0x01]           -      -  0 (0x00000000)
 *  970                  UINT[0x01]           -      -  5 (0x00000005)
 *  971                  FIELD[0x0B]         64      4  emergency (off=0x0040, hash=0x75463942)
 *  972                CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  973              CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 *  974              OPEN_CALL[0x07]      2      0  SE_NOP hash=0x080C2B37
 *  975              ONESHOT   [0x08]    974      9  idx_to_ptr=0
 *  976              CLOSE[0x06]          0      -  (end SE_NOP)
 *  977            CLOSE[0x06]          0      -  (end SE_IF_THEN_ELSE)
 *  978          CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *  979        CLOSE[0x06]          0      -  (end SE_WHILE)
 *  980        OPEN_CALL[0x07]     48      0  SE_WHILE hash=0xA08B6DD3
 *  981        MAIN      [0x09]    980     10  idx_to_ptr=0
 *  982          OPEN_CALL[0x07]     45      0  SE_FORK_JOIN hash=0xE404E1CF
 *  983          MAIN      [0x09]    982     11  idx_to_ptr=0
 *  984            OPEN_CALL[0x07]     42      0  SE_IF_THEN_ELSE hash=0x1E860193
 *  985            MAIN      [0x09]    984     12  idx_to_ptr=0
 *  986              OPEN_CALL[0x07]     12      0  SE_PRED_OR hash=0x0CF6212F
 *  987              PRED+SR   [0x4A]    986      4  idx_to_ptr=0
 *  988                OPEN_CALL[0x07]      4      0  SE_FIELD_LT hash=0xD2EA98E7
 *  989                PRED      [0x0A]    988      8  idx_to_ptr=0
 *  990                  FIELD[0x0B]         32      4  voltage (off=0x0020, hash=0xE1935F65)
 *  991                  UINT[0x01]           -      -  9 (0x00000009)
 *  992                CLOSE[0x06]          0      -  (end SE_FIELD_LT)
 *  993                OPEN_CALL[0x07]      4      0  SE_FIELD_GT hash=0x10F63374
 *  994                PRED      [0x0A]    993      1  idx_to_ptr=0
 *  995                  FIELD[0x0B]         32      4  voltage (off=0x0020, hash=0xE1935F65)
 *  996                  UINT[0x01]           -      -  16 (0x00000010)
 *  997                CLOSE[0x06]          0      -  (end SE_FIELD_GT)
 *  998              CLOSE[0x06]          0      -  (end SE_PRED_OR)
 *  999              OPEN_CALL[0x07]     23      0  SE_SEQUENCE hash=0xEC3EE7BF
 * 1000              MAIN      [0x09]    999      9  idx_to_ptr=0
 * 1001                OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 * 1002                ONESHOT   [0x08]   1001      1  idx_to_ptr=0
 * 1003                  STR_IDX[0x0D]       26     27  "DIAG: Voltage out of range!"
 * 1004                CLOSE[0x06]          0      -  (end SE_LOG)
 * 1005                OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 * 1006                ONESHOT   [0x08]   1005      4  idx_to_ptr=0
 * 1007                  UINT[0x01]           -      -  0 (0x00000000)
 * 1008                  UINT[0x01]           -      -  23 (0x00000017)
 * 1009                  FIELD[0x0B]         32      4  voltage (off=0x0020, hash=0xE1935F65)
 * 1010                CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 * 1011                OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 * 1012                ONESHOT   [0x08]   1011      0  idx_to_ptr=0
 * 1013                  FIELD[0x0B]         64      4  emergency (off=0x0040, hash=0x75463942)
 * 1014                  UINT[0x01]           -      -  1 (0x00000001)
 * 1015                CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 * 1016                OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 * 1017                ONESHOT   [0x08]   1016      4  idx_to_ptr=0
 * 1018                  UINT[0x01]           -      -  0 (0x00000000)
 * 1019                  UINT[0x01]           -      -  5 (0x00000005)
 * 1020                  FIELD[0x0B]         64      4  emergency (off=0x0040, hash=0x75463942)
 * 1021                CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 * 1022              CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 * 1023              OPEN_CALL[0x07]      2      0  SE_NOP hash=0x080C2B37
 * 1024              ONESHOT   [0x08]   1023      9  idx_to_ptr=0
 * 1025              CLOSE[0x06]          0      -  (end SE_NOP)
 * 1026            CLOSE[0x06]          0      -  (end SE_IF_THEN_ELSE)
 * 1027          CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 * 1028        CLOSE[0x06]          0      -  (end SE_WHILE)
 * 1029        OPEN_CALL[0x07]     32      0  SE_WHILE hash=0xA08B6DD3
 * 1030        MAIN      [0x09]   1029     10  idx_to_ptr=0
 * 1031          OPEN_CALL[0x07]     29      0  SE_FORK_JOIN hash=0xE404E1CF
 * 1032          MAIN      [0x09]   1031     11  idx_to_ptr=0
 * 1033            OPEN_CALL[0x07]     26      0  SE_IF_THEN_ELSE hash=0x1E860193
 * 1034            MAIN      [0x09]   1033     12  idx_to_ptr=0
 * 1035              OPEN_CALL[0x07]     20      0  SE_SEQUENCE hash=0xEC3EE7BF
 * 1036              MAIN      [0x09]   1035      9  idx_to_ptr=0
 * 1037                OPEN_CALL[0x07]      2      0  READ_FAULT_STATUS_TLE7269G hash=0xE057BF86
 * 1038                ONESHOT   [0x08]   1037     17  idx_to_ptr=0
 * 1039                CLOSE[0x06]          0      -  (end READ_FAULT_STATUS_TLE7269G)
 * 1040                OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 * 1041                ONESHOT   [0x08]   1040      1  idx_to_ptr=0
 * 1042                  STR_IDX[0x0D]       27     29  "DIAG: TLE7269G fault detected"
 * 1043                CLOSE[0x06]          0      -  (end SE_LOG)
 * 1044                OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 * 1045                ONESHOT   [0x08]   1044      0  idx_to_ptr=0
 * 1046                  FIELD[0x0B]         64      4  emergency (off=0x0040, hash=0x75463942)
 * 1047                  UINT[0x01]           -      -  1 (0x00000001)
 * 1048                CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 * 1049                OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 * 1050                ONESHOT   [0x08]   1049      4  idx_to_ptr=0
 * 1051                  UINT[0x01]           -      -  0 (0x00000000)
 * 1052                  UINT[0x01]           -      -  5 (0x00000005)
 * 1053                  FIELD[0x0B]         64      4  emergency (off=0x0040, hash=0x75463942)
 * 1054                CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 * 1055              CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 * 1056              OPEN_CALL[0x07]      2      0  SE_NOP hash=0x080C2B37
 * 1057              ONESHOT   [0x08]   1056      9  idx_to_ptr=0
 * 1058              CLOSE[0x06]          0      -  (end SE_NOP)
 * 1059            CLOSE[0x06]          0      -  (end SE_IF_THEN_ELSE)
 * 1060          CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 * 1061        CLOSE[0x06]          0      -  (end SE_WHILE)
 * 1062      CLOSE[0x06]          0      -  (end SE_FORK)
 * 1063    CLOSE[0x06]          0      -  (end SE_FORK)
 * 1064  CLOSE[0x06]          0      -  (end SE_FUNCTION_INTERFACE)
 *
 * Total params: 1065
 */

#endif // DOOR_WINDOW_CONTROLLER_DUMP_32_H
