// ============================================================================
// door_window_controller_records.h
// Generated record structures for door_window_controller
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef DOOR_WINDOW_CONTROLLER_RECORDS_H
#define DOOR_WINDOW_CONTROLLER_RECORDS_H

#include <stdint.h>
#include <stdbool.h>

// Forward declarations
typedef struct door_controller_bb_s door_controller_bb_t;

// Record: door_controller_bb (size=136, align=8)
struct door_controller_bb_s {
    int32_t motor_state;  // offset=0, size=4
    int32_t bridge_mode;  // offset=4, size=4
    int32_t motor_pwm;  // offset=8, size=4
    int32_t motor_enabled;  // offset=12, size=4
    float motor_current;  // offset=16, size=4
    float max_current;  // offset=20, size=4
    int32_t position;  // offset=24, size=4
    float temperature;  // offset=28, size=4
    float voltage;  // offset=32, size=4
    int32_t open_speed;  // offset=36, size=4
    int32_t close_speed;  // offset=40, size=4
    float thermal_threshold;  // offset=44, size=4
    float min_voltage;  // offset=48, size=4
    float max_voltage;  // offset=52, size=4
    int32_t fully_open;  // offset=56, size=4
    int32_t fully_closed;  // offset=60, size=4
    int32_t emergency;  // offset=64, size=4
    int32_t obstruction;  // offset=68, size=4
    int32_t over_current;  // offset=72, size=4
    int32_t system_shutdown;  // offset=76, size=4
    int32_t manual_reset;  // offset=80, size=4
    int32_t fault_pin_active;  // offset=84, size=4
    int32_t open_request;  // offset=88, size=4
    int32_t close_request;  // offset=92, size=4
    int32_t stop_request;  // offset=96, size=4
    int32_t status_request;  // offset=100, size=4
    int32_t auto_reverse_req;  // offset=104, size=4
    int32_t serial_data_avail;  // offset=108, size=4
    int32_t serial_msg_type;  // offset=112, size=4
    uint64_t config_ptr;  // offset=120, size=8 (ptr64)
    uint64_t diag_ptr;  // offset=128, size=8 (ptr64)
};

#endif // DOOR_WINDOW_CONTROLLER_RECORDS_H
