// ============================================================================
// door_window_controller_user_registration.c
// User function registration for door_window_controller
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// NOTE: Builtin functions (SE_*) are registered via s_engine_register_builtins()
// ============================================================================

#include "door_window_controller.h"
#include "door_window_controller_user_functions.h"
#include "s_engine_module.h"

// Oneshot function entries
static s_expr_fn_entry_t door_window_controller_oneshot_entries[] = {
    { 0x21F70576, (void*)read_serial_message },
    { 0x2294BEC5, (void*)parse_message_type },
    { 0x9A0D92FA, (void*)disable_motor_tle7269g },
    { 0x5C071EC1, (void*)set_bridge_mode },
    { 0x3572046E, (void*)set_motor_pwm },
    { 0x1F90BFFD, (void*)enable_motor_tle7269g },
    { 0x462235D6, (void*)send_status_message },
    { 0xD1C8709B, (void*)read_diagnostics_tle7269g },
    { 0xB62BA5BB, (void*)read_current_position },
    { 0x3DADDF65, (void*)read_motor_current },
    { 0x0B55B0E4, (void*)read_temperature },
    { 0x199FBF58, (void*)assemble_status_message },
    { 0x5EA6EF23, (void*)send_serial_status },
    { 0xE057BF86, (void*)read_fault_status_tle7269g },
};

static const s_expr_fn_table_t door_window_controller_oneshot_table = {
    .entries = door_window_controller_oneshot_entries,
    .count = 14
};

// Predicate function entries
static s_expr_fn_entry_t door_window_controller_pred_entries[] = {
    { 0x2B37E8C9, (void*)check_limit_switch_open },
    { 0x772EDA2C, (void*)check_motor_stall },
    { 0xECBB0205, (void*)check_limit_switch_closed },
};

static const s_expr_fn_table_t door_window_controller_pred_table = {
    .entries = door_window_controller_pred_entries,
    .count = 3
};

// Table accessors
const s_expr_fn_table_t* door_window_controller_get_oneshot_table(void) {
    return &door_window_controller_oneshot_table;
}

const s_expr_fn_table_t* door_window_controller_get_main_table(void) {
    return NULL;
}

const s_expr_fn_table_t* door_window_controller_get_pred_table(void) {
    return &door_window_controller_pred_table;
}

// Register all user functions with module
void door_window_controller_register_all(s_expr_module_t* module) {
    s_expr_module_register_oneshot(module, &door_window_controller_oneshot_table);
    s_expr_module_register_pred(module, &door_window_controller_pred_table);
}
