-- ============================================================================
-- loop_test_module.lua
-- Pre-serialized module_data for LuaJIT runtime
-- DO NOT EDIT - Generated by s_compile.lua v5.2
-- ============================================================================

local M = {}

M.name         = "loop_test"
M.name_hash    = 0xD1A777D8
M.pointer_size = 4
M.debug        = true

M.oneshot_funcs = { "SE_SET_FIELD", "SE_LOG", "SE_LOG_INT", "SE_INC_FIELD" }
M.main_funcs    = { "SE_FUNCTION_INTERFACE", "SE_FORK_JOIN", "SE_WHILE", "SE_CHAIN_FLOW", "SE_TICK_DELAY", "SE_RETURN_PIPELINE_DISABLE", "SE_RETURN_TERMINATE" }
M.pred_funcs    = { "SE_STATE_INCREMENT_AND_TEST", "SE_FIELD_INCREMENT_AND_TEST" }

M.string_table = { "loop_sequence_fn start", "outer_sequence_counter %d", "inner_sequence_fn start", "inner_sequence_counter %d", "inner_sequence_fn end", "loop_sequence_fn end" }
M.string_index = {
  ["inner_sequence_counter %d"] = 3,
  ["inner_sequence_fn end"] = 4,
  ["inner_sequence_fn start"] = 2,
  ["loop_sequence_fn end"] = 5,
  ["loop_sequence_fn start"] = 0,
  ["outer_sequence_counter %d"] = 1,
}

M.tree_order = { "loop_test" }
M.trees = {}

M.trees["loop_test"] = {
  name          = "loop_test",
  name_hash     = 0xD1A777D8,
  node_count    = 42,
  pointer_count = 4,
  record_name   = "loop_test_blackboard",
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_FUNCTION_INTERFACE",
      func_hash=0xC7FEA7F6,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={
        {
          func_name="SE_SET_FIELD",
          func_hash=0xFFF84A15,
          call_type="o_call",
          order=0,
          param_count=2,
          pointer_index=nil,
          params={
            {type="field_ref",value="outer_sequence_counter",order=0},
            {type="uint",value=0,order=1},
          },
          children={},
        },
        {
          func_name="SE_SET_FIELD",
          func_hash=0xFFF84A15,
          call_type="o_call",
          order=1,
          param_count=2,
          pointer_index=nil,
          params={
            {type="field_ref",value="inner_sequence_counter",order=0},
            {type="uint",value=0,order=1},
          },
          children={},
        },
        {
          func_name="SE_FORK_JOIN",
          func_hash=0xE404E1CF,
          call_type="m_call",
          order=2,
          param_count=0,
          pointer_index=nil,
          params={},
          children={
            {
              func_name="SE_WHILE",
              func_hash=0xA08B6DD3,
              call_type="m_call",
              order=0,
              param_count=0,
              pointer_index=nil,
              params={},
              children={
                {
                  func_name="SE_STATE_INCREMENT_AND_TEST",
                  func_hash=0x42A88A80,
                  call_type="p_call",
                  order=0,
                  param_count=2,
                  pointer_index=nil,
                  params={
                    {type="uint",value=1,order=0},
                    {type="uint",value=10,order=1},
                  },
                  children={},
                },
                {
                  func_name="SE_FORK_JOIN",
                  func_hash=0xE404E1CF,
                  call_type="m_call",
                  order=1,
                  param_count=0,
                  pointer_index=nil,
                  params={},
                  children={
                    {
                      func_name="SE_CHAIN_FLOW",
                      func_hash=0xFFC1FAA4,
                      call_type="m_call",
                      order=0,
                      param_count=0,
                      pointer_index=nil,
                      params={},
                      children={
                        {
                          func_name="SE_LOG",
                          func_hash=0xCEBBEFA4,
                          call_type="o_call",
                          order=0,
                          param_count=1,
                          pointer_index=nil,
                          params={
                            {type="str_ptr",value="loop_sequence_fn start",order=0},
                          },
                          children={},
                        },
                        {
                          func_name="SE_LOG_INT",
                          func_hash=0x2442CEA2,
                          call_type="o_call",
                          order=1,
                          param_count=2,
                          pointer_index=nil,
                          params={
                            {type="str_ptr",value="outer_sequence_counter %d",order=0},
                            {type="field_ref",value="outer_sequence_counter",order=1},
                          },
                          children={},
                        },
                        {
                          func_name="SE_INC_FIELD",
                          func_hash=0x09391555,
                          call_type="o_call",
                          order=2,
                          param_count=2,
                          pointer_index=nil,
                          params={
                            {type="field_ref",value="outer_sequence_counter",order=0},
                            {type="uint",value=1,order=1},
                          },
                          children={},
                        },
                        {
                          func_name="SE_CHAIN_FLOW",
                          func_hash=0xFFC1FAA4,
                          call_type="m_call",
                          order=3,
                          param_count=0,
                          pointer_index=nil,
                          params={},
                          children={
                            {
                              func_name="SE_LOG",
                              func_hash=0xCEBBEFA4,
                              call_type="o_call",
                              order=0,
                              param_count=1,
                              pointer_index=nil,
                              params={
                                {type="str_ptr",value="inner_sequence_fn start",order=0},
                              },
                              children={},
                            },
                            {
                              func_name="SE_LOG_INT",
                              func_hash=0x2442CEA2,
                              call_type="o_call",
                              order=1,
                              param_count=2,
                              pointer_index=nil,
                              params={
                                {type="str_ptr",value="inner_sequence_counter %d",order=0},
                                {type="field_ref",value="inner_sequence_counter",order=1},
                              },
                              children={},
                            },
                            {
                              func_name="SE_INC_FIELD",
                              func_hash=0x09391555,
                              call_type="o_call",
                              order=2,
                              param_count=2,
                              pointer_index=nil,
                              params={
                                {type="field_ref",value="inner_sequence_counter",order=0},
                                {type="uint",value=1,order=1},
                              },
                              children={},
                            },
                            {
                              func_name="SE_TICK_DELAY",
                              func_hash=0x0C3460EB,
                              call_type="pt_m_call",
                              order=3,
                              param_count=1,
                              pointer_index=0,
                              params={
                                {type="int",value=3,order=0},
                              },
                              children={},
                            },
                            {
                              func_name="SE_LOG",
                              func_hash=0xCEBBEFA4,
                              call_type="o_call",
                              order=4,
                              param_count=1,
                              pointer_index=nil,
                              params={
                                {type="str_ptr",value="inner_sequence_fn end",order=0},
                              },
                              children={},
                            },
                            {
                              func_name="SE_RETURN_PIPELINE_DISABLE",
                              func_hash=0x6B7AA500,
                              call_type="m_call",
                              order=5,
                              param_count=0,
                              pointer_index=nil,
                              params={},
                              children={},
                            },
                          },
                        },
                        {
                          func_name="SE_TICK_DELAY",
                          func_hash=0x0C3460EB,
                          call_type="pt_m_call",
                          order=4,
                          param_count=1,
                          pointer_index=1,
                          params={
                            {type="int",value=5,order=0},
                          },
                          children={},
                        },
                        {
                          func_name="SE_LOG",
                          func_hash=0xCEBBEFA4,
                          call_type="o_call",
                          order=5,
                          param_count=1,
                          pointer_index=nil,
                          params={
                            {type="str_ptr",value="loop_sequence_fn end",order=0},
                          },
                          children={},
                        },
                        {
                          func_name="SE_RETURN_PIPELINE_DISABLE",
                          func_hash=0x6B7AA500,
                          call_type="m_call",
                          order=6,
                          param_count=0,
                          pointer_index=nil,
                          params={},
                          children={},
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
        {
          func_name="SE_FORK_JOIN",
          func_hash=0xE404E1CF,
          call_type="m_call",
          order=3,
          param_count=0,
          pointer_index=nil,
          params={},
          children={
            {
              func_name="SE_SET_FIELD",
              func_hash=0xFFF84A15,
              call_type="o_call",
              order=0,
              param_count=2,
              pointer_index=nil,
              params={
                {type="field_ref",value="field_test_increment",order=0},
                {type="uint",value=1,order=1},
              },
              children={},
            },
            {
              func_name="SE_SET_FIELD",
              func_hash=0xFFF84A15,
              call_type="o_call",
              order=1,
              param_count=2,
              pointer_index=nil,
              params={
                {type="field_ref",value="field_test_limit",order=0},
                {type="uint",value=10,order=1},
              },
              children={},
            },
            {
              func_name="SE_WHILE",
              func_hash=0xA08B6DD3,
              call_type="m_call",
              order=2,
              param_count=0,
              pointer_index=nil,
              params={},
              children={
                {
                  func_name="SE_FIELD_INCREMENT_AND_TEST",
                  func_hash=0x275252DB,
                  call_type="p_call",
                  order=0,
                  param_count=3,
                  pointer_index=nil,
                  params={
                    {type="field_ref",value="field_test_counter",order=0},
                    {type="field_ref",value="field_test_increment",order=1},
                    {type="field_ref",value="field_test_limit",order=2},
                  },
                  children={},
                },
                {
                  func_name="SE_FORK_JOIN",
                  func_hash=0xE404E1CF,
                  call_type="m_call",
                  order=1,
                  param_count=0,
                  pointer_index=nil,
                  params={},
                  children={
                    {
                      func_name="SE_CHAIN_FLOW",
                      func_hash=0xFFC1FAA4,
                      call_type="m_call",
                      order=0,
                      param_count=0,
                      pointer_index=nil,
                      params={},
                      children={
                        {
                          func_name="SE_LOG",
                          func_hash=0xCEBBEFA4,
                          call_type="o_call",
                          order=0,
                          param_count=1,
                          pointer_index=nil,
                          params={
                            {type="str_ptr",value="loop_sequence_fn start",order=0},
                          },
                          children={},
                        },
                        {
                          func_name="SE_LOG_INT",
                          func_hash=0x2442CEA2,
                          call_type="o_call",
                          order=1,
                          param_count=2,
                          pointer_index=nil,
                          params={
                            {type="str_ptr",value="outer_sequence_counter %d",order=0},
                            {type="field_ref",value="outer_sequence_counter",order=1},
                          },
                          children={},
                        },
                        {
                          func_name="SE_INC_FIELD",
                          func_hash=0x09391555,
                          call_type="o_call",
                          order=2,
                          param_count=2,
                          pointer_index=nil,
                          params={
                            {type="field_ref",value="outer_sequence_counter",order=0},
                            {type="uint",value=1,order=1},
                          },
                          children={},
                        },
                        {
                          func_name="SE_CHAIN_FLOW",
                          func_hash=0xFFC1FAA4,
                          call_type="m_call",
                          order=3,
                          param_count=0,
                          pointer_index=nil,
                          params={},
                          children={
                            {
                              func_name="SE_LOG",
                              func_hash=0xCEBBEFA4,
                              call_type="o_call",
                              order=0,
                              param_count=1,
                              pointer_index=nil,
                              params={
                                {type="str_ptr",value="inner_sequence_fn start",order=0},
                              },
                              children={},
                            },
                            {
                              func_name="SE_LOG_INT",
                              func_hash=0x2442CEA2,
                              call_type="o_call",
                              order=1,
                              param_count=2,
                              pointer_index=nil,
                              params={
                                {type="str_ptr",value="inner_sequence_counter %d",order=0},
                                {type="field_ref",value="inner_sequence_counter",order=1},
                              },
                              children={},
                            },
                            {
                              func_name="SE_INC_FIELD",
                              func_hash=0x09391555,
                              call_type="o_call",
                              order=2,
                              param_count=2,
                              pointer_index=nil,
                              params={
                                {type="field_ref",value="inner_sequence_counter",order=0},
                                {type="uint",value=1,order=1},
                              },
                              children={},
                            },
                            {
                              func_name="SE_TICK_DELAY",
                              func_hash=0x0C3460EB,
                              call_type="pt_m_call",
                              order=3,
                              param_count=1,
                              pointer_index=2,
                              params={
                                {type="int",value=3,order=0},
                              },
                              children={},
                            },
                            {
                              func_name="SE_LOG",
                              func_hash=0xCEBBEFA4,
                              call_type="o_call",
                              order=4,
                              param_count=1,
                              pointer_index=nil,
                              params={
                                {type="str_ptr",value="inner_sequence_fn end",order=0},
                              },
                              children={},
                            },
                            {
                              func_name="SE_RETURN_PIPELINE_DISABLE",
                              func_hash=0x6B7AA500,
                              call_type="m_call",
                              order=5,
                              param_count=0,
                              pointer_index=nil,
                              params={},
                              children={},
                            },
                          },
                        },
                        {
                          func_name="SE_TICK_DELAY",
                          func_hash=0x0C3460EB,
                          call_type="pt_m_call",
                          order=4,
                          param_count=1,
                          pointer_index=3,
                          params={
                            {type="int",value=5,order=0},
                          },
                          children={},
                        },
                        {
                          func_name="SE_LOG",
                          func_hash=0xCEBBEFA4,
                          call_type="o_call",
                          order=5,
                          param_count=1,
                          pointer_index=nil,
                          params={
                            {type="str_ptr",value="loop_sequence_fn end",order=0},
                          },
                          children={},
                        },
                        {
                          func_name="SE_RETURN_PIPELINE_DISABLE",
                          func_hash=0x6B7AA500,
                          call_type="m_call",
                          order=6,
                          param_count=0,
                          pointer_index=nil,
                          params={},
                          children={},
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
        {
          func_name="SE_RETURN_TERMINATE",
          func_hash=0xDFE64C74,
          call_type="m_call",
          order=4,
          param_count=0,
          pointer_index=nil,
          params={},
          children={},
        },
      },
    },
  },
}

M.record_order = { "loop_test_blackboard" }
M.records      = {}
M.records["loop_test_blackboard"] = {
  name      = "loop_test_blackboard",
  name_hash = 0x033C03AC,
  size      = 20,
  align     = 4,
  fields    = {
    {name="outer_sequence_counter",name_hash=0x24954557,type="uint32",offset=0,size=4,is_pointer=false,is_char_array=false,is_embedded=false},
    {name="inner_sequence_counter",name_hash=0xD0B76C4E,type="uint32",offset=4,size=4,is_pointer=false,is_char_array=false,is_embedded=false},
    {name="field_test_counter",name_hash=0x6542B7E7,type="uint32",offset=8,size=4,is_pointer=false,is_char_array=false,is_embedded=false},
    {name="field_test_increment",name_hash=0x696CDE6A,type="uint32",offset=12,size=4,is_pointer=false,is_char_array=false,is_embedded=false},
    {name="field_test_limit",name_hash=0x1CAA35D8,type="uint32",offset=16,size=4,is_pointer=false,is_char_array=false,is_embedded=false},
  },
}

M.const_order = {  }
M.constants   = {}

M.events      = {}
M.event_names = {}
return M
