-- ============================================================================
-- callback_function_module.lua
-- Pre-serialized module_data for LuaJIT runtime
-- DO NOT EDIT - Generated by s_compile.lua v5.2
-- ============================================================================

local M = {}

M.name         = "callback_function"
M.name_hash    = 0x0C1A5BFB
M.pointer_size = 4
M.debug        = false

M.oneshot_funcs = { "SE_LOG", "SE_LOAD_FUNCTION" }
M.main_funcs    = { "SE_FUNCTION_INTERFACE", "SE_SEQUENCE_ONCE", "SE_EXEC_FN", "SE_RETURN_FUNCTION_TERMINATE" }
M.pred_funcs    = {  }

M.string_table = { "callback test started", "callback function called", "do some stack work", "call a dictionary function" }
M.string_index = {
  ["call a dictionary function"] = 3,
  ["callback function called"] = 1,
  ["callback test started"] = 0,
  ["do some stack work"] = 2,
}

M.tree_order = { "callback_function" }
M.trees = {}

M.trees["callback_function"] = {
  name          = "callback_function",
  name_hash     = 0x0C1A5BFB,
  node_count    = 9,
  pointer_count = 1,
  record_name   = "callback_function_blackboard",
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_FUNCTION_INTERFACE",
      func_hash=0xC7FEA7F6,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={
        {
          func_name="SE_LOG",
          func_hash=0xCEBBEFA4,
          call_type="o_call",
          order=0,
          param_count=1,
          pointer_index=nil,
          params={
            {type="str_ptr",value="callback test started",order=0},
          },
          children={},
        },
        {
          func_name="SE_LOAD_FUNCTION",
          func_hash=0x30DB52C3,
          call_type="io_call",
          order=1,
          param_count=1,
          pointer_index=nil,
          params={
            {type="field_ref",value="fn_ptr",order=0},
          },
          children={
            {
              func_name="SE_SEQUENCE_ONCE",
              func_hash=0x4F4BB2E1,
              call_type="m_call",
              order=1,
              param_count=0,
              pointer_index=nil,
              params={},
              children={
                {
                  func_name="SE_LOG",
                  func_hash=0xCEBBEFA4,
                  call_type="o_call",
                  order=0,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="str_ptr",value="callback function called",order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_LOG",
                  func_hash=0xCEBBEFA4,
                  call_type="o_call",
                  order=1,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="str_ptr",value="do some stack work",order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_LOG",
                  func_hash=0xCEBBEFA4,
                  call_type="o_call",
                  order=2,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="str_ptr",value="call a dictionary function",order=0},
                  },
                  children={},
                },
              },
            },
          },
        },
        {
          func_name="SE_EXEC_FN",
          func_hash=0xC9C09EC0,
          call_type="pt_m_call",
          order=2,
          param_count=1,
          pointer_index=0,
          params={
            {type="field_ref",value="fn_ptr",order=0},
          },
          children={},
        },
        {
          func_name="SE_RETURN_FUNCTION_TERMINATE",
          func_hash=0x0A5B8A85,
          call_type="m_call",
          order=3,
          param_count=0,
          pointer_index=nil,
          params={},
          children={},
        },
      },
    },
  },
}

M.record_order = { "callback_function_blackboard" }
M.records      = {}
M.records["callback_function_blackboard"] = {
  name      = "callback_function_blackboard",
  name_hash = 0x590F5B8D,
  size      = 8,
  align     = 8,
  fields    = {
    {name="fn_ptr",name_hash=0xE4D06AB8,type="ptr64",offset=0,size=8,is_pointer=true,is_char_array=false,is_embedded=false},
  },
}

M.const_order = {  }
M.constants   = {}

M.events      = {}
M.event_names = {}
return M
