-- ============================================================================
-- state_machine_test_module.lua
-- Pre-serialized module_data for LuaJIT runtime
-- DO NOT EDIT - Generated by s_compile.lua v5.2
-- ============================================================================

local M = {}

M.name         = "state_machine_test"
M.name_hash    = 0x6824A885
M.pointer_size = 4
M.debug        = true

M.oneshot_funcs = { "SE_LOG", "SE_SET_FIELD", "CFL_DISABLE_CHILDREN", "CFL_ENABLE_CHILD" }
M.main_funcs    = { "SE_FUNCTION_INTERFACE", "SE_FORK_JOIN", "SE_TICK_DELAY", "SE_FORK", "SE_SEQUENCE", "SE_STATE_MACHINE", "SE_RETURN_PIPELINE_DISABLE", "SE_RETURN_TERMINATE", "SE_RETURN_FUNCTION_TERMINATE" }
M.pred_funcs    = {  }

M.string_table = { "Fork Join Test Started", "Fork Join Test Terminated", "Fork 1 Test Started", "Fork 1 Test Terminated", "State machine test started", "State 0", "State 0 terminated", "State 1", "State 1 terminated", "State 2", "State 2 terminated", "State machine test finished" }
M.string_index = {
  ["Fork 1 Test Started"] = 2,
  ["Fork 1 Test Terminated"] = 3,
  ["Fork Join Test Started"] = 0,
  ["Fork Join Test Terminated"] = 1,
  ["State 0"] = 5,
  ["State 0 terminated"] = 6,
  ["State 1"] = 7,
  ["State 1 terminated"] = 8,
  ["State 2"] = 9,
  ["State 2 terminated"] = 10,
  ["State machine test finished"] = 11,
  ["State machine test started"] = 4,
}

M.tree_order = { "state_machine_test" }
M.trees = {}

M.trees["state_machine_test"] = {
  name          = "state_machine_test",
  name_hash     = 0x6824A885,
  node_count    = 48,
  pointer_count = 7,
  record_name   = "state_machine_blackboard",
  defaults_index = 0xFFFF,
  nodes = {
    {
      func_name="SE_FUNCTION_INTERFACE",
      func_hash=0xC7FEA7F6,
      call_type="m_call",
      order=0,
      param_count=0,
      pointer_index=nil,
      params={},
      children={
        {
          func_name="SE_LOG",
          func_hash=0xCEBBEFA4,
          call_type="o_call",
          order=0,
          param_count=1,
          pointer_index=nil,
          params={
            {type="str_ptr",value="Fork Join Test Started",order=0},
          },
          children={},
        },
        {
          func_name="SE_FORK_JOIN",
          func_hash=0xE404E1CF,
          call_type="m_call",
          order=1,
          param_count=0,
          pointer_index=nil,
          params={},
          children={
            {
              func_name="SE_LOG",
              func_hash=0xCEBBEFA4,
              call_type="o_call",
              order=0,
              param_count=1,
              pointer_index=nil,
              params={
                {type="str_ptr",value="Fork Join Test Started",order=0},
              },
              children={},
            },
            {
              func_name="SE_TICK_DELAY",
              func_hash=0x0C3460EB,
              call_type="pt_m_call",
              order=1,
              param_count=1,
              pointer_index=0,
              params={
                {type="int",value=10,order=0},
              },
              children={},
            },
            {
              func_name="SE_LOG",
              func_hash=0xCEBBEFA4,
              call_type="o_call",
              order=2,
              param_count=1,
              pointer_index=nil,
              params={
                {type="str_ptr",value="Fork Join Test Terminated",order=0},
              },
              children={},
            },
          },
        },
        {
          func_name="SE_FORK",
          func_hash=0x0A24332A,
          call_type="m_call",
          order=2,
          param_count=0,
          pointer_index=nil,
          params={},
          children={
            {
              func_name="SE_SEQUENCE",
              func_hash=0xEC3EE7BF,
              call_type="m_call",
              order=0,
              param_count=0,
              pointer_index=nil,
              params={},
              children={
                {
                  func_name="SE_LOG",
                  func_hash=0xCEBBEFA4,
                  call_type="o_call",
                  order=0,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="str_ptr",value="Fork 1 Test Started",order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_TICK_DELAY",
                  func_hash=0x0C3460EB,
                  call_type="pt_m_call",
                  order=1,
                  param_count=1,
                  pointer_index=1,
                  params={
                    {type="int",value=10,order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_LOG",
                  func_hash=0xCEBBEFA4,
                  call_type="o_call",
                  order=2,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="str_ptr",value="Fork 1 Test Terminated",order=0},
                  },
                  children={},
                },
              },
            },
          },
        },
        {
          func_name="SE_SET_FIELD",
          func_hash=0xFFF84A15,
          call_type="io_call",
          order=3,
          param_count=2,
          pointer_index=nil,
          params={
            {type="field_ref",value="state",order=0},
            {type="uint",value=0,order=1},
          },
          children={},
        },
        {
          func_name="SE_LOG",
          func_hash=0xCEBBEFA4,
          call_type="o_call",
          order=4,
          param_count=1,
          pointer_index=nil,
          params={
            {type="str_ptr",value="State machine test started",order=0},
          },
          children={},
        },
        {
          func_name="SE_STATE_MACHINE",
          func_hash=0x5EEDA8E9,
          call_type="m_call",
          order=5,
          param_count=5,
          pointer_index=nil,
          params={
            {type="field_ref",value="state",order=0},
            {type="int",value=0,order=1},
            {type="int",value=1,order=3},
            {type="int",value=2,order=5},
            {type="int",value=-1,order=7},
          },
          children={
            {
              func_name="SE_SEQUENCE",
              func_hash=0xEC3EE7BF,
              call_type="m_call",
              order=2,
              param_count=0,
              pointer_index=nil,
              params={},
              children={
                {
                  func_name="SE_LOG",
                  func_hash=0xCEBBEFA4,
                  call_type="o_call",
                  order=0,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="str_ptr",value="State 0",order=0},
                  },
                  children={},
                },
                {
                  func_name="CFL_DISABLE_CHILDREN",
                  func_hash=0x5839B05B,
                  call_type="o_call",
                  order=1,
                  param_count=0,
                  pointer_index=nil,
                  params={},
                  children={},
                },
                {
                  func_name="CFL_ENABLE_CHILD",
                  func_hash=0xD42E3453,
                  call_type="o_call",
                  order=2,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="int",value=0,order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_TICK_DELAY",
                  func_hash=0x0C3460EB,
                  call_type="pt_m_call",
                  order=3,
                  param_count=1,
                  pointer_index=2,
                  params={
                    {type="int",value=10,order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_SET_FIELD",
                  func_hash=0xFFF84A15,
                  call_type="o_call",
                  order=4,
                  param_count=2,
                  pointer_index=nil,
                  params={
                    {type="field_ref",value="state",order=0},
                    {type="uint",value=1,order=1},
                  },
                  children={},
                },
                {
                  func_name="SE_LOG",
                  func_hash=0xCEBBEFA4,
                  call_type="o_call",
                  order=5,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="str_ptr",value="State 0 terminated",order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_RETURN_PIPELINE_DISABLE",
                  func_hash=0x6B7AA500,
                  call_type="m_call",
                  order=6,
                  param_count=0,
                  pointer_index=nil,
                  params={},
                  children={},
                },
              },
            },
            {
              func_name="SE_SEQUENCE",
              func_hash=0xEC3EE7BF,
              call_type="m_call",
              order=4,
              param_count=0,
              pointer_index=nil,
              params={},
              children={
                {
                  func_name="SE_LOG",
                  func_hash=0xCEBBEFA4,
                  call_type="o_call",
                  order=0,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="str_ptr",value="State 1",order=0},
                  },
                  children={},
                },
                {
                  func_name="CFL_DISABLE_CHILDREN",
                  func_hash=0x5839B05B,
                  call_type="o_call",
                  order=1,
                  param_count=0,
                  pointer_index=nil,
                  params={},
                  children={},
                },
                {
                  func_name="CFL_ENABLE_CHILD",
                  func_hash=0xD42E3453,
                  call_type="o_call",
                  order=2,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="int",value=1,order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_TICK_DELAY",
                  func_hash=0x0C3460EB,
                  call_type="pt_m_call",
                  order=3,
                  param_count=1,
                  pointer_index=3,
                  params={
                    {type="int",value=10,order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_SET_FIELD",
                  func_hash=0xFFF84A15,
                  call_type="o_call",
                  order=4,
                  param_count=2,
                  pointer_index=nil,
                  params={
                    {type="field_ref",value="state",order=0},
                    {type="uint",value=2,order=1},
                  },
                  children={},
                },
                {
                  func_name="SE_LOG",
                  func_hash=0xCEBBEFA4,
                  call_type="o_call",
                  order=5,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="str_ptr",value="State 1 terminated",order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_RETURN_PIPELINE_DISABLE",
                  func_hash=0x6B7AA500,
                  call_type="m_call",
                  order=6,
                  param_count=0,
                  pointer_index=nil,
                  params={},
                  children={},
                },
              },
            },
            {
              func_name="SE_SEQUENCE",
              func_hash=0xEC3EE7BF,
              call_type="m_call",
              order=6,
              param_count=0,
              pointer_index=nil,
              params={},
              children={
                {
                  func_name="SE_LOG",
                  func_hash=0xCEBBEFA4,
                  call_type="o_call",
                  order=0,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="str_ptr",value="State 2",order=0},
                  },
                  children={},
                },
                {
                  func_name="CFL_DISABLE_CHILDREN",
                  func_hash=0x5839B05B,
                  call_type="o_call",
                  order=1,
                  param_count=0,
                  pointer_index=nil,
                  params={},
                  children={},
                },
                {
                  func_name="CFL_ENABLE_CHILD",
                  func_hash=0xD42E3453,
                  call_type="o_call",
                  order=2,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="int",value=2,order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_TICK_DELAY",
                  func_hash=0x0C3460EB,
                  call_type="pt_m_call",
                  order=3,
                  param_count=1,
                  pointer_index=4,
                  params={
                    {type="int",value=10,order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_SET_FIELD",
                  func_hash=0xFFF84A15,
                  call_type="o_call",
                  order=4,
                  param_count=2,
                  pointer_index=nil,
                  params={
                    {type="field_ref",value="state",order=0},
                    {type="uint",value=0,order=1},
                  },
                  children={},
                },
                {
                  func_name="SE_LOG",
                  func_hash=0xCEBBEFA4,
                  call_type="o_call",
                  order=5,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="str_ptr",value="State 2 terminated",order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_RETURN_PIPELINE_DISABLE",
                  func_hash=0x6B7AA500,
                  call_type="m_call",
                  order=6,
                  param_count=0,
                  pointer_index=nil,
                  params={},
                  children={},
                },
              },
            },
            {
              func_name="SE_SEQUENCE",
              func_hash=0xEC3EE7BF,
              call_type="m_call",
              order=8,
              param_count=0,
              pointer_index=nil,
              params={},
              children={
                {
                  func_name="SE_LOG",
                  func_hash=0xCEBBEFA4,
                  call_type="o_call",
                  order=0,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="str_ptr",value="State 2",order=0},
                  },
                  children={},
                },
                {
                  func_name="CFL_DISABLE_CHILDREN",
                  func_hash=0x5839B05B,
                  call_type="o_call",
                  order=1,
                  param_count=0,
                  pointer_index=nil,
                  params={},
                  children={},
                },
                {
                  func_name="CFL_ENABLE_CHILD",
                  func_hash=0xD42E3453,
                  call_type="o_call",
                  order=2,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="int",value=2,order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_TICK_DELAY",
                  func_hash=0x0C3460EB,
                  call_type="pt_m_call",
                  order=3,
                  param_count=1,
                  pointer_index=5,
                  params={
                    {type="int",value=100,order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_LOG",
                  func_hash=0xCEBBEFA4,
                  call_type="o_call",
                  order=4,
                  param_count=1,
                  pointer_index=nil,
                  params={
                    {type="str_ptr",value="State 2 terminated",order=0},
                  },
                  children={},
                },
                {
                  func_name="SE_RETURN_TERMINATE",
                  func_hash=0xDFE64C74,
                  call_type="m_call",
                  order=5,
                  param_count=0,
                  pointer_index=nil,
                  params={},
                  children={},
                },
              },
            },
          },
        },
        {
          func_name="SE_TICK_DELAY",
          func_hash=0x0C3460EB,
          call_type="pt_m_call",
          order=6,
          param_count=1,
          pointer_index=6,
          params={
            {type="int",value=350,order=0},
          },
          children={},
        },
        {
          func_name="SE_LOG",
          func_hash=0xCEBBEFA4,
          call_type="o_call",
          order=7,
          param_count=1,
          pointer_index=nil,
          params={
            {type="str_ptr",value="State machine test finished",order=0},
          },
          children={},
        },
        {
          func_name="SE_RETURN_FUNCTION_TERMINATE",
          func_hash=0x0A5B8A85,
          call_type="m_call",
          order=8,
          param_count=0,
          pointer_index=nil,
          params={},
          children={},
        },
      },
    },
  },
}

M.record_order = { "state_machine_blackboard" }
M.records      = {}
M.records["state_machine_blackboard"] = {
  name      = "state_machine_blackboard",
  name_hash = 0xC89D038C,
  size      = 4,
  align     = 4,
  fields    = {
    {name="state",name_hash=0x783132F6,type="int32",offset=0,size=4,is_pointer=false,is_char_array=false,is_embedded=false},
  },
}

M.const_order = {  }
M.constants   = {}

M.events      = {}
M.event_names = {}
return M
