-- ============================================================================
-- s_expr_generators.lua
-- S-Expression Engine Code Generators - Version 5.3
-- 
-- Contains:
--   - ModuleGenerator (C header generation)
--   - BinaryEmitter (low-level byte emission)
--   - BinaryModuleGenerator (binary module generation)
--
-- VERSION 5.3 CHANGES:
--   - Added parent_offset (u16_b) to all brace tokens (OPEN_CALL, CLOSE,
--     OPEN_DICT, CLOSE_DICT, OPEN_KEY, CLOSE_KEY, OPEN_ARRAY, CLOSE_ARRAY,
--     OPEN_TUPLE, CLOSE_TUPLE, OPEN/CLOSE for lists)
--   - parent_offset = relative offset back to enclosing OPEN_CALL param
--   - 0 = top-level / no parent
--   - Enables O(1) upward navigation in the param stream
--
-- Loaded by s_expr_dsl.lua via dofile()
-- ============================================================================

local ffi = require("ffi")
local bit = require("bit")

-- These will be set by the parent module
local M = {}
local hash_module = nil
local types_module = nil
local builtins_module = nil

-- Called by s_expr_dsl.lua to inject dependencies
function M._init(hash, types, builtins)
    hash_module = hash
    types_module = types
    builtins_module = builtins
end

-- ============================================================================
-- MODULE GENERATOR CLASS (for C headers)
-- ============================================================================

local ModuleGenerator = {}
ModuleGenerator.__index = ModuleGenerator

function ModuleGenerator.new(module_data)
    local self = setmetatable({}, ModuleGenerator)
    self.module = module_data
    self.is_64bit = (module_data.pointer_size == 8)
    return self
end

function ModuleGenerator:to_c_records_header(base_name)
    local lines = {}
    local mod = self.module
    local guard = base_name:upper() .. "_RECORDS_H"
    
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "// " .. base_name .. "_records.h")
    table.insert(lines, "// Generated record structures for " .. mod.name)
    table.insert(lines, "// DO NOT EDIT - Generated by s_expr_dsl v5.3")
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "")
    table.insert(lines, "#ifndef " .. guard)
    table.insert(lines, "#define " .. guard)
    table.insert(lines, "")
    table.insert(lines, "#include <stdint.h>")
    table.insert(lines, "#include <stdbool.h>")
    table.insert(lines, "")
    
    -- Forward declarations for pointer types
    table.insert(lines, "// Forward declarations")
    for _, name in ipairs(mod.record_order) do
        table.insert(lines, "typedef struct " .. name .. "_s " .. name .. "_t;")
    end
    table.insert(lines, "")
    
    -- Record definitions
    for _, name in ipairs(mod.record_order) do
        local rec = mod.records[name]
        local rec_upper = name:upper()
        
        -- Collect array length defines for this record
        local array_defines = {}
        for _, field in ipairs(rec.fields) do
            if field.is_char_array or field.is_int32_array or field.is_float32_array then
                local define_name = rec_upper .. "_" .. field.name:upper() .. "_LEN"
                table.insert(array_defines, {
                    name = define_name,
                    len = field.array_len
                })
            end
        end
        
        -- Emit array length defines before the struct
        if #array_defines > 0 then
            table.insert(lines, "// Array length constants for " .. name)
            for _, def in ipairs(array_defines) do
                table.insert(lines, string.format("#define %s %d", def.name, def.len))
            end
            table.insert(lines, "")
        end
        
        table.insert(lines, "// Record: " .. name .. " (size=" .. rec.size .. ", align=" .. rec.align .. ")")
        table.insert(lines, "struct " .. name .. "_s {")
        
        for _, field in ipairs(rec.fields) do
            local ctype
            local is_array = false
            local array_len_str = nil
            
            if field.is_pointer then
                if field.is_ptr64 then
                    -- Always 64-bit pointer storage
                    ctype = "uint64_t"
                else
                    local target = field.target_type
                    if target == "char" or target == "void" or 
                       target == "int" or target == "float" or target == "double" then
                        ctype = target .. "*"
                    else
                        ctype = target .. "_t*"
                    end
                end
            elseif field.is_char_array then
                ctype = "char"
                is_array = true
                array_len_str = rec_upper .. "_" .. field.name:upper() .. "_LEN"
            elseif field.is_int32_array then
                ctype = "int32_t"
                is_array = true
                array_len_str = rec_upper .. "_" .. field.name:upper() .. "_LEN"
            elseif field.is_float32_array then
                ctype = "float"
                is_array = true
                array_len_str = rec_upper .. "_" .. field.name:upper() .. "_LEN"
            elseif field.is_embedded then
                ctype = field.embedded_record .. "_t"
            else
                local info = types_module.type_info[field.type]
                ctype = info and info.ctype or "uint32_t"
            end
            
            local decl
            if is_array then
                decl = string.format("    %s %s[%s];", ctype, field.name, array_len_str)
            else
                decl = string.format("    %s %s;", ctype, field.name)
            end
            
            local comment = string.format("  // offset=%d, size=%d", field.offset, field.size)
            if field.is_ptr64 then
                comment = comment .. " (ptr64)"
            elseif field.is_int32_array then
                comment = comment .. " (int32 array)"
            elseif field.is_float32_array then
                comment = comment .. " (float32 array)"
            elseif field.is_char_array then
                comment = comment .. " (char array)"
            end
            
            table.insert(lines, decl .. comment)
        end
        
        table.insert(lines, "};")
        table.insert(lines, "")
    end
    
    table.insert(lines, "#endif // " .. guard)
    
    return table.concat(lines, "\n")
end

function ModuleGenerator:to_c_header(base_name)
    local lines = {}
    local mod = self.module
    local guard = base_name:upper() .. "_H"
    
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "// " .. base_name .. ".h")
    table.insert(lines, "// Generated S-expression module for " .. mod.name)
    table.insert(lines, "// DO NOT EDIT - Generated by s_expr_dsl v5.3")
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "")
    table.insert(lines, "#ifndef " .. guard)
    table.insert(lines, "#define " .. guard)
    table.insert(lines, "")
    table.insert(lines, "#ifdef __cplusplus")
    table.insert(lines, 'extern "C" {')
    table.insert(lines, "#endif")
    table.insert(lines, "")
    table.insert(lines, '#include "s_engine_types.h"')
    if #mod.record_order > 0 then
        
        table.insert(lines, '#include "' .. base_name .. '_records.h"')
    end
    table.insert(lines, "")
    
    -- Module info
    table.insert(lines, "// Module: " .. mod.name)
    table.insert(lines, string.format("#define %s_NAME_HASH %s", base_name:upper(), hash_module.fmt_hash(mod.name_hash)))
    table.insert(lines, string.format("#define %s_TREE_COUNT %d", base_name:upper(), #mod.tree_order))
    table.insert(lines, string.format("#define %s_RECORD_COUNT %d", base_name:upper(), #mod.record_order))
    table.insert(lines, "")
    
    -- User-defined events
    if mod.events and #mod.events > 0 then
        table.insert(lines, "// User-defined event IDs")
        for _, evt in ipairs(mod.events) do
            local def_name = "SE_EVENT_" .. evt.name:upper()
            table.insert(lines, string.format("#define %s 0x%04X", def_name, evt.id))
        end
        table.insert(lines, "")
    end
    
    -- String table
    if #mod.string_table > 0 then
        table.insert(lines, "// String table")
        table.insert(lines, "static const char* const " .. base_name .. "_strings[] = {")
        for i, str in ipairs(mod.string_table) do
            local escaped = str:gsub("\\", "\\\\"):gsub('"', '\\"'):gsub("\n", "\\n"):gsub("\r", "\\r")
            local comma = (i < #mod.string_table) and "," or ""
            table.insert(lines, '    "' .. escaped .. '"' .. comma)
        end
        table.insert(lines, "};")
        table.insert(lines, string.format("#define %s_STRING_COUNT %d", base_name:upper(), #mod.string_table))
        table.insert(lines, "")
    end
    
    -- Function hashes
    local all_funcs = {}
    for _, name in ipairs(mod.oneshot_funcs) do table.insert(all_funcs, name) end
    for _, name in ipairs(mod.main_funcs) do table.insert(all_funcs, name) end
    for _, name in ipairs(mod.pred_funcs) do table.insert(all_funcs, name) end
    
    if #all_funcs > 0 then
        table.insert(lines, "// Function hashes")
        local seen = {}
        for _, name in ipairs(all_funcs) do
            if not seen[name] then
                seen[name] = true
                local h = hash_module.fnv1a_32(name)
                local def_name = name:upper():gsub("[^%w]", "_") .. "_HASH"
                table.insert(lines, string.format("#define %s %s", def_name, hash_module.fmt_hash(h)))
            end
        end
        table.insert(lines, "")
    end
    
    -- Tree hashes
    if #mod.tree_order > 0 then
        table.insert(lines, "// Tree hashes")
        for _, name in ipairs(mod.tree_order) do
            local h = hash_module.fnv1a_32(name)
            local def_name = name:upper():gsub("[^%w]", "_") .. "_HASH"
            table.insert(lines, string.format("#define %s %s", def_name, hash_module.fmt_hash(h)))
        end
        table.insert(lines, "")
    end
    
    -- Record hashes
    if #mod.record_order > 0 then
        table.insert(lines, "// Record hashes")
        for _, name in ipairs(mod.record_order) do
            local h = hash_module.fnv1a_32(name)
            local def_name = name:upper():gsub("[^%w]", "_") .. "_HASH"
            table.insert(lines, string.format("#define %s %s", def_name, hash_module.fmt_hash(h)))
        end
        table.insert(lines, "")
    end
    
    -- Field hashes (deduplicated)
    local field_hashes = {}
    local field_order = {}
    for _, rname in ipairs(mod.record_order) do
        local rec = mod.records[rname]
        for _, field in ipairs(rec.fields) do
            if not field_hashes[field.name] then
                field_hashes[field.name] = hash_module.fnv1a_32(field.name)
                table.insert(field_order, field.name)
            end
        end
    end
    
    if #field_order > 0 then
        table.insert(lines, "// Field hashes")
        for _, name in ipairs(field_order) do
            local h = field_hashes[name]
            local def_name = "FIELD_" .. name:upper():gsub("[^%w]", "_") .. "_HASH"
            table.insert(lines, string.format("#define %s %s", def_name, hash_module.fmt_hash(h)))
        end
        table.insert(lines, "")
    end
    
    table.insert(lines, "#ifdef __cplusplus")
    table.insert(lines, "}")
    table.insert(lines, "#endif")
    table.insert(lines, "")
    table.insert(lines, "#endif // " .. guard)
    
    return table.concat(lines, "\n")
end

function ModuleGenerator:to_c_debug_header(base_name)
    local lines = {}
    local mod = self.module
    local guard = base_name:upper() .. "_DEBUG_H"
    
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "// " .. base_name .. "_debug.h")
    table.insert(lines, "// Debug hash reference for " .. mod.name)
    table.insert(lines, "// DO NOT EDIT - Generated by s_expr_dsl v5.3")
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "")
    table.insert(lines, "#ifndef " .. guard)
    table.insert(lines, "#define " .. guard)
    table.insert(lines, "")
    
    local function hash_hex(h)
        local u32 = ffi.new("uint32_t", h)
        return string.format("%08X", tonumber(u32))
    end
    
    if #mod.oneshot_funcs > 0 then
        table.insert(lines, "// Oneshot functions")
        for _, name in ipairs(mod.oneshot_funcs) do
            local h = hash_module.fnv1a_32(name)
            table.insert(lines, string.format("#define H_%s %s  // %s", hash_hex(h), hash_module.fmt_hash(h), name))
        end
        table.insert(lines, "")
    end
    
    if #mod.main_funcs > 0 then
        table.insert(lines, "// Main functions")
        for _, name in ipairs(mod.main_funcs) do
            local h = hash_module.fnv1a_32(name)
            table.insert(lines, string.format("#define H_%s %s  // %s", hash_hex(h), hash_module.fmt_hash(h), name))
        end
        table.insert(lines, "")
    end
    
    if #mod.pred_funcs > 0 then
        table.insert(lines, "// Predicate functions")
        for _, name in ipairs(mod.pred_funcs) do
            local h = hash_module.fnv1a_32(name)
            table.insert(lines, string.format("#define H_%s %s  // %s", hash_hex(h), hash_module.fmt_hash(h), name))
        end
        table.insert(lines, "")
    end
    
    table.insert(lines, "#endif // " .. guard)
    return table.concat(lines, "\n")
end

function ModuleGenerator:to_c_user_header(base_name)
    local lines = {}
    local mod = self.module
    local guard = base_name:upper() .. "_USER_FUNCTIONS_H"
    
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "// " .. base_name .. "_user_functions.h")
    table.insert(lines, "// User function prototypes for " .. mod.name)
    table.insert(lines, "// DO NOT EDIT - Generated by s_expr_dsl v5.3")
    table.insert(lines, "// NOTE: Builtin functions (SE_*) are in s_engine_builtins.h")
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "")
    table.insert(lines, "#ifndef " .. guard)
    table.insert(lines, "#define " .. guard)
    table.insert(lines, "")
    table.insert(lines, '#include "s_engine_types.h"')
    table.insert(lines, "")
    table.insert(lines, "#ifdef __cplusplus")
    table.insert(lines, 'extern "C" {')
    table.insert(lines, "#endif")
    table.insert(lines, "")
    
    local function to_c_name(name)
        return name:lower()
    end
    
    -- Filter out builtin functions
    local user_oneshot = {}
    local user_main = {}
    local user_pred = {}
    
    for _, name in ipairs(mod.oneshot_funcs) do
        if not builtins_module.is_builtin(name) then
            table.insert(user_oneshot, name)
        end
    end
    for _, name in ipairs(mod.main_funcs) do
        if not builtins_module.is_builtin(name) then
            table.insert(user_main, name)
        end
    end
    for _, name in ipairs(mod.pred_funcs) do
        if not builtins_module.is_builtin(name) then
            table.insert(user_pred, name)
        end
    end
    
    local param_list = [[
    s_expr_tree_instance_t* inst,
    const s_expr_param_t* params,
    uint16_t param_count,
    s_expr_event_type_t event_type,
    uint16_t event_id,
    void* event_data
)]]
    
    if #user_oneshot > 0 then
        table.insert(lines, "// Oneshot functions")
        for _, name in ipairs(user_oneshot) do
            table.insert(lines, string.format("void %s(", to_c_name(name)))
            table.insert(lines, param_list .. ";")
            table.insert(lines, "")
        end
    end
    
    if #user_main > 0 then
        table.insert(lines, "// Main functions")
        for _, name in ipairs(user_main) do
            table.insert(lines, string.format("s_expr_result_t %s(", to_c_name(name)))
            table.insert(lines, param_list .. ";")
            table.insert(lines, "")
        end
    end
    
    if #user_pred > 0 then
        table.insert(lines, "// Predicate functions")
        for _, name in ipairs(user_pred) do
            table.insert(lines, string.format("bool %s(", to_c_name(name)))
            table.insert(lines, param_list .. ";")
            table.insert(lines, "")
        end
    end
    
    table.insert(lines, "#ifdef __cplusplus")
    table.insert(lines, "}")
    table.insert(lines, "#endif")
    table.insert(lines, "")
    table.insert(lines, "#endif // " .. guard)
    return table.concat(lines, "\n")
end

function ModuleGenerator:to_c_user_registration(base_name)
    local lines = {}
    local mod = self.module
    
    local function to_c_name(name)
        return name:lower()
    end
    
    -- Filter out builtin functions
    local user_oneshot = {}
    local user_main = {}
    local user_pred = {}
    
    for _, name in ipairs(mod.oneshot_funcs) do
        if not builtins_module.is_builtin(name) then
            table.insert(user_oneshot, name)
        end
    end
    for _, name in ipairs(mod.main_funcs) do
        if not builtins_module.is_builtin(name) then
            table.insert(user_main, name)
        end
    end
    for _, name in ipairs(mod.pred_funcs) do
        if not builtins_module.is_builtin(name) then
            table.insert(user_pred, name)
        end
    end
    
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "// " .. base_name .. "_user_registration.c")
    table.insert(lines, "// User function registration for " .. mod.name)
    table.insert(lines, "// DO NOT EDIT - Generated by s_expr_dsl v5.3")
    table.insert(lines, "// NOTE: Builtin functions (SE_*) are registered via s_engine_register_builtins()")
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "")
    table.insert(lines, '#include "' .. base_name .. '.h"')
    table.insert(lines, '#include "' .. base_name .. '_user_functions.h"')
    table.insert(lines, '#include "s_engine_module.h"')
    table.insert(lines, "")
    
    if #user_oneshot > 0 then
        table.insert(lines, "// Oneshot function entries")
        table.insert(lines, "static s_expr_fn_entry_t " .. base_name .. "_oneshot_entries[] = {")
        for _, name in ipairs(user_oneshot) do
            table.insert(lines, string.format("    { %s, (void*)%s },", 
                hash_module.fmt_hash(hash_module.fnv1a_32(name)), to_c_name(name)))
        end
        table.insert(lines, "};")
        table.insert(lines, "")
        table.insert(lines, "static const s_expr_fn_table_t " .. base_name .. "_oneshot_table = {")
        table.insert(lines, "    .entries = " .. base_name .. "_oneshot_entries,")
        table.insert(lines, "    .count = " .. #user_oneshot)
        table.insert(lines, "};")
        table.insert(lines, "")
    end
    
    if #user_main > 0 then
        table.insert(lines, "// Main function entries")
        table.insert(lines, "static s_expr_fn_entry_t " .. base_name .. "_main_entries[] = {")
        for _, name in ipairs(user_main) do
            table.insert(lines, string.format("    { %s, (void*)%s },", 
                hash_module.fmt_hash(hash_module.fnv1a_32(name)), to_c_name(name)))
        end
        table.insert(lines, "};")
        table.insert(lines, "")
        table.insert(lines, "static const s_expr_fn_table_t " .. base_name .. "_main_table = {")
        table.insert(lines, "    .entries = " .. base_name .. "_main_entries,")
        table.insert(lines, "    .count = " .. #user_main)
        table.insert(lines, "};")
        table.insert(lines, "")
    end
    
    if #user_pred > 0 then
        table.insert(lines, "// Predicate function entries")
        table.insert(lines, "static s_expr_fn_entry_t " .. base_name .. "_pred_entries[] = {")
        for _, name in ipairs(user_pred) do
            table.insert(lines, string.format("    { %s, (void*)%s },", 
                hash_module.fmt_hash(hash_module.fnv1a_32(name)), to_c_name(name)))
        end
        table.insert(lines, "};")
        table.insert(lines, "")
        table.insert(lines, "static const s_expr_fn_table_t " .. base_name .. "_pred_table = {")
        table.insert(lines, "    .entries = " .. base_name .. "_pred_entries,")
        table.insert(lines, "    .count = " .. #user_pred)
        table.insert(lines, "};")
        table.insert(lines, "")
    end
    
    -- Table accessors
    table.insert(lines, "// Table accessors")
    
    if #user_oneshot > 0 then
        table.insert(lines, "const s_expr_fn_table_t* " .. base_name .. "_get_oneshot_table(void) {")
        table.insert(lines, "    return &" .. base_name .. "_oneshot_table;")
        table.insert(lines, "}")
    else
        table.insert(lines, "const s_expr_fn_table_t* " .. base_name .. "_get_oneshot_table(void) {")
        table.insert(lines, "    return NULL;")
        table.insert(lines, "}")
    end
    table.insert(lines, "")
    
    if #user_main > 0 then
        table.insert(lines, "const s_expr_fn_table_t* " .. base_name .. "_get_main_table(void) {")
        table.insert(lines, "    return &" .. base_name .. "_main_table;")
        table.insert(lines, "}")
    else
        table.insert(lines, "const s_expr_fn_table_t* " .. base_name .. "_get_main_table(void) {")
        table.insert(lines, "    return NULL;")
        table.insert(lines, "}")
    end
    table.insert(lines, "")
    
    if #user_pred > 0 then
        table.insert(lines, "const s_expr_fn_table_t* " .. base_name .. "_get_pred_table(void) {")
        table.insert(lines, "    return &" .. base_name .. "_pred_table;")
        table.insert(lines, "}")
    else
        table.insert(lines, "const s_expr_fn_table_t* " .. base_name .. "_get_pred_table(void) {")
        table.insert(lines, "    return NULL;")
        table.insert(lines, "}")
    end
    table.insert(lines, "")
    
    -- Register-all function
    table.insert(lines, "// Register all user functions with module")
    table.insert(lines, "void " .. base_name .. "_register_all(s_expr_module_t* module) {")
    if #user_oneshot > 0 then
        table.insert(lines, "    s_expr_module_register_oneshot(module, &" .. base_name .. "_oneshot_table);")
    end
    if #user_main > 0 then
        table.insert(lines, "    s_expr_module_register_main(module, &" .. base_name .. "_main_table);")
    end
    if #user_pred > 0 then
        table.insert(lines, "    s_expr_module_register_pred(module, &" .. base_name .. "_pred_table);")
    end
    table.insert(lines, "}")
    
    return table.concat(lines, "\n")
end

function ModuleGenerator:dump()
    local lines = {}
    local mod = self.module
    
    table.insert(lines, "=== MODULE DUMP: " .. mod.name .. " ===")
    table.insert(lines, string.format("Name hash: %s", hash_module.fmt_hash(mod.name_hash)))
    table.insert(lines, string.format("Pointer size: %d", mod.pointer_size))
    table.insert(lines, "")
    
    table.insert(lines, "RECORDS (" .. #mod.record_order .. "):")
    for _, name in ipairs(mod.record_order) do
        local rec = mod.records[name]
        table.insert(lines, string.format("  %s (size=%d, align=%d, hash=%s)", name, rec.size, rec.align, hash_module.fmt_hash(rec.name_hash)))
    end
    table.insert(lines, "")
    
    table.insert(lines, "TREES (" .. #mod.tree_order .. "):")
    for _, name in ipairs(mod.tree_order) do
        local tree = mod.trees[name]
        table.insert(lines, string.format("  %s (nodes=%d, ptrs=%d, record=%s)", name, tree.node_count, tree.pointer_count, tree.record_name or "none"))
    end
    table.insert(lines, "")
    
    table.insert(lines, "FUNCTIONS:")
    table.insert(lines, "  Oneshot (" .. #mod.oneshot_funcs .. "): " .. table.concat(mod.oneshot_funcs, ", "))
    table.insert(lines, "  Main (" .. #mod.main_funcs .. "): " .. table.concat(mod.main_funcs, ", "))
    table.insert(lines, "  Pred (" .. #mod.pred_funcs .. "): " .. table.concat(mod.pred_funcs, ", "))
    
    return table.concat(lines, "\n")
end

M.ModuleGenerator = ModuleGenerator

-- ============================================================================
-- BINARY EMITTER
-- ============================================================================

local BinaryEmitter = {}
BinaryEmitter.__index = BinaryEmitter

function BinaryEmitter.new()
    local self = setmetatable({}, BinaryEmitter)
    self.buffer = {}
    self.pos = 0
    return self
end

function BinaryEmitter:emit_u8(v)
    table.insert(self.buffer, bit.band(v, 0xFF))
    self.pos = self.pos + 1
end

function BinaryEmitter:emit_u16(v)
    table.insert(self.buffer, bit.band(v, 0xFF))
    table.insert(self.buffer, bit.band(bit.rshift(v, 8), 0xFF))
    self.pos = self.pos + 2
end

function BinaryEmitter:emit_u32(v)
    if v < 0 then v = 0x100000000 + v end
    table.insert(self.buffer, bit.band(v, 0xFF))
    table.insert(self.buffer, bit.band(bit.rshift(v, 8), 0xFF))
    table.insert(self.buffer, bit.band(bit.rshift(v, 16), 0xFF))
    table.insert(self.buffer, bit.band(bit.rshift(v, 24), 0xFF))
    self.pos = self.pos + 4
end

function BinaryEmitter:emit_i32(v)
    if v < 0 then v = 0x100000000 + v end
    self:emit_u32(v)
end

function BinaryEmitter:emit_f32(v)
    local buf = ffi.new("float[1]", v)
    local bytes = ffi.cast("uint8_t*", buf)
    for i = 0, 3 do
        table.insert(self.buffer, bytes[i])
    end
    self.pos = self.pos + 4
end

function BinaryEmitter:emit_u64(v)
    local lo = bit.band(v, 0xFFFFFFFF)
    local hi = math.floor(v / 0x100000000)
    self:emit_u32(lo)
    self:emit_u32(hi)
end

function BinaryEmitter:emit_i64(v)
    if v < 0 then
        local abs_val = -v
        local lo = bit.band(abs_val, 0xFFFFFFFF)
        local hi = math.floor(abs_val / 0x100000000)
        lo = bit.band(bit.bnot(lo), 0xFFFFFFFF)
        hi = bit.band(bit.bnot(hi), 0xFFFFFFFF)
        lo = lo + 1
        if lo > 0xFFFFFFFF then
            lo = 0
            hi = hi + 1
        end
        self:emit_u32(lo)
        self:emit_u32(hi)
    else
        self:emit_u64(v)
    end
end

function BinaryEmitter:emit_f64(v)
    local buf = ffi.new("double[1]", v)
    local bytes = ffi.cast("uint8_t*", buf)
    for i = 0, 7 do
        table.insert(self.buffer, bytes[i])
    end
    self.pos = self.pos + 8
end

function BinaryEmitter:emit_string(s)
    local len = #s
    self:emit_u16(len)
    for i = 1, len do
        self:emit_u8(s:byte(i))
    end
    self:emit_u8(0)
    local total = 2 + len + 1
    local padding = (4 - (total % 4)) % 4
    for i = 1, padding do
        self:emit_u8(0)
    end
end

function BinaryEmitter:emit_bytes(bytes)
    for _, b in ipairs(bytes) do
        table.insert(self.buffer, bit.band(b, 0xFF))
    end
    self.pos = self.pos + #bytes
end

function BinaryEmitter:align(n)
    local padding = (n - (self.pos % n)) % n
    for i = 1, padding do
        self:emit_u8(0)
    end
end

function BinaryEmitter:patch_u16(offset, v)
    self.buffer[offset + 1] = bit.band(v, 0xFF)
    self.buffer[offset + 2] = bit.band(bit.rshift(v, 8), 0xFF)
end

function BinaryEmitter:patch_u32(offset, v)
    if v < 0 then v = 0x100000000 + v end
    self.buffer[offset + 1] = bit.band(v, 0xFF)
    self.buffer[offset + 2] = bit.band(bit.rshift(v, 8), 0xFF)
    self.buffer[offset + 3] = bit.band(bit.rshift(v, 16), 0xFF)
    self.buffer[offset + 4] = bit.band(bit.rshift(v, 24), 0xFF)
end

function BinaryEmitter:get_pos()
    return self.pos
end

function BinaryEmitter:to_bytes()
    return self.buffer
end

M.BinaryEmitter = BinaryEmitter

-- ============================================================================
-- BINARY MODULE GENERATOR
-- ============================================================================

-- Binary format constants
local SEXB_MAGIC = 0x42584553    -- "SEXB"
local SEXB_VERSION = 0x0503      -- Version 5.3

local SEXB_FLAG_32BIT = 0x0000
local SEXB_FLAG_64BIT = 0x0001
local SEXB_FLAG_DEBUG = 0x0002

local BinaryModuleGenerator = {}
BinaryModuleGenerator.__index = BinaryModuleGenerator

function BinaryModuleGenerator.new(module_data)
    local self = setmetatable({}, BinaryModuleGenerator)
    self.module = module_data
    self.is_64bit = (module_data.pointer_size == 8)
    self.param_size = self.is_64bit and 16 or 8
    self:build_lookups()
    return self
end

function BinaryModuleGenerator:build_lookups()
    local mod = self.module
    
    self.record_index = {}
    for i, name in ipairs(mod.record_order) do
        self.record_index[name] = i - 1
    end
    
    self.string_index = {}
    for i, s in ipairs(mod.string_table) do
        self.string_index[s] = i - 1
    end
    
    self.const_index = {}
    for i, name in ipairs(mod.const_order) do
        self.const_index[name] = i - 1
    end
    
    self.oneshot_hash_index = {}
    for i, name in ipairs(mod.oneshot_funcs) do
        self.oneshot_hash_index[hash_module.fnv1a_32(name)] = i - 1
    end
    
    self.main_hash_index = {}
    for i, name in ipairs(mod.main_funcs) do
        self.main_hash_index[hash_module.fnv1a_32(name)] = i - 1
    end
    
    self.pred_hash_index = {}
    for i, name in ipairs(mod.pred_funcs) do
        self.pred_hash_index[hash_module.fnv1a_32(name)] = i - 1
    end
end

function BinaryModuleGenerator:emit_param_struct(e, param_type, index_to_pointer, u16_a, u16_b, value_32_or_64)
    local S_EXPR_PARAM = types_module.S_EXPR_PARAM
    
    e:emit_u8(param_type)
    e:emit_u8(index_to_pointer or 0)
    
    if self.is_64bit then
        for i = 1, 6 do e:emit_u8(0) end
        
        if value_32_or_64 then
            if type(value_32_or_64) == "number" then
                if param_type == S_EXPR_PARAM.FLOAT then
                    e:emit_f64(value_32_or_64)
                elseif param_type == S_EXPR_PARAM.INT then
                    e:emit_i64(value_32_or_64)
                else
                    e:emit_u64(value_32_or_64)
                end
            else
                e:emit_u64(0)
            end
        else
            e:emit_u16(u16_a or 0)
            e:emit_u16(u16_b or 0)
            e:emit_u32(0)
        end
    else
        e:emit_u16(0)
        
        if value_32_or_64 then
            if type(value_32_or_64) == "number" then
                if param_type == S_EXPR_PARAM.FLOAT then
                    e:emit_f32(value_32_or_64)
                elseif param_type == S_EXPR_PARAM.INT then
                    e:emit_i32(value_32_or_64)
                else
                    e:emit_u32(value_32_or_64)
                end
            else
                e:emit_u32(0)
            end
        else
            e:emit_u16(u16_a or 0)
            e:emit_u16(u16_b or 0)
        end
    end
end

function BinaryModuleGenerator:count_node_params(node)
    local count = 2  -- OPEN_CALL + func_ref
    
    for _, param in ipairs(node.params) do
        count = count + 1
    end
    
    for _, child in ipairs(node.children) do
        count = count + self:count_node_params(child) + 1
    end
    
    return count
end

function BinaryModuleGenerator:resolve_field_offset(field_name)
    if not self.current_tree_record then
        return nil, nil
    end
    
    local rec = self.module.records[self.current_tree_record]
    if not rec then return nil, nil end
    
    for _, field in ipairs(rec.fields) do
        if field.name == field_name then
            return field.offset, field.size
        end
    end
    
    return nil, nil
end

function BinaryModuleGenerator:resolve_nested_field_offset(path)
    if not self.current_tree_record then
        return nil, nil
    end
    
    local rec = self.module.records[self.current_tree_record]
    if not rec then return nil, nil end
    
    local parts = {}
    for part in path:gmatch("[^.]+") do
        table.insert(parts, part)
    end
    
    local offset = 0
    local current_rec = rec
    local field = nil
    
    for i, part in ipairs(parts) do
        field = nil
        for _, f in ipairs(current_rec.fields) do
            if f.name == part then
                field = f
                break
            end
        end
        
        if not field then
            return nil, nil
        end
        
        offset = offset + field.offset
        
        if i < #parts and field.is_embedded then
            current_rec = self.module.records[field.embedded_record]
            if not current_rec then
                return nil, nil
            end
        end
    end
    
    return offset, field and field.size or 0
end

function BinaryModuleGenerator:emit_dsl_param(e, param)
    local S_EXPR_PARAM = types_module.S_EXPR_PARAM
    local ptype = param.type
    local value = param.value
    
    if ptype == "int" then
        self:emit_param_struct(e, S_EXPR_PARAM.INT, 0, nil, nil, value)
        return 1
    elseif ptype == "uint" then
        self:emit_param_struct(e, S_EXPR_PARAM.UINT, 0, nil, nil, value)
        return 1
    elseif ptype == "float" then
        self:emit_param_struct(e, S_EXPR_PARAM.FLOAT, 0, nil, nil, value)
        return 1
    elseif ptype == "str_hash" then
        self:emit_param_struct(e, S_EXPR_PARAM.STR_HASH, 0, nil, nil, value.hash)
        return 1
    elseif ptype == "str_idx" or ptype == "str_ptr" then
        local idx = self.string_index[value] or 0
        local len = #value
        self:emit_param_struct(e, S_EXPR_PARAM.STR_IDX, 0, idx, len)
        return 1
    elseif ptype == "field_ref" then
        local offset, size = self:resolve_field_offset(value)
        if offset then
            self:emit_param_struct(e, S_EXPR_PARAM.FIELD, 0, offset, size)
        else
            local h = hash_module.fnv1a_32(value)
            self:emit_param_struct(e, S_EXPR_PARAM.FIELD, 0, nil, nil, h)
        end
        return 1
    elseif ptype == "stack_push" then
        self:emit_param_struct(e, S_EXPR_PARAM.STACK_PUSH, 0, nil, nil, value)
        return 1
    elseif ptype == "stack_pop" then
        self:emit_param_struct(e, S_EXPR_PARAM.STACK_POP, 0, nil, nil, value)
        return 1
    elseif ptype == "nested_field_ref" then
        local offset, size = self:resolve_nested_field_offset(value)
        if offset then
            self:emit_param_struct(e, S_EXPR_PARAM.FIELD, 0, offset, size)
        else
            local h = hash_module.fnv1a_32(value)
            self:emit_param_struct(e, S_EXPR_PARAM.FIELD, 0, nil, nil, h)
        end
        return 1
    elseif ptype == "const_ref" then
        local idx = self.const_index[value] or 0
        self:emit_param_struct(e, S_EXPR_PARAM.CONST_REF, 0, idx, 0)
        return 1
    elseif ptype == "result" then
        self:emit_param_struct(e, S_EXPR_PARAM.RESULT, 0, nil, nil, value)
        return 1
    elseif ptype == "list_start" then
        self:emit_param_struct(e, S_EXPR_PARAM.OPEN, 0, 0, 0)
        return 1
    elseif ptype == "list_end" then
        self:emit_param_struct(e, S_EXPR_PARAM.CLOSE, 0, 0, 0)
        return 1
    elseif ptype == "stack_tos" then
        self:emit_param_struct(e, S_EXPR_PARAM.STACK_TOS, 0, nil, nil, value)
        return 1
    elseif ptype == "stack_local" then
        self:emit_param_struct(e, S_EXPR_PARAM.STACK_LOCAL, 0, nil, nil, value)
        return 1
    elseif ptype == "null_param" then
        self:emit_param_struct(e, S_EXPR_PARAM.NULL_PARAM, 0, 0, 0)
        return 1
    else
        self:emit_param_struct(e, S_EXPR_PARAM.UINT, 0, nil, nil, value or 0)
        return 1
    end
end

function BinaryModuleGenerator:emit_tree_params(e, tree)
    local S_EXPR_PARAM = types_module.S_EXPR_PARAM
    local S_EXPR_FLAG_SURVIVES_RESET = types_module.S_EXPR_FLAG_SURVIVES_RESET
    local S_EXPR_FLAG_POINTER = types_module.S_EXPR_FLAG_POINTER
    
    local param_count = 0
    local current_node_idx = 0
    local brace_stack = {}
    
    -- ========================================================================
    -- Parent offset tracking (v5.3)
    -- Stack of param indices for enclosing OPEN_CALL tokens.
    -- Used to compute relative parent_offset in all brace tokens.
    -- parent_offset = 0 means top-level (no parent).
    -- ========================================================================
    local parent_call_stack = {}
    
    local function current_parent_offset()
        if #parent_call_stack == 0 then
            return 0
        end
        return param_count - parent_call_stack[#parent_call_stack]
    end
    
    local function emit_node(node)
        local opcode, func_index
        
        if node.call_type == "o_call" then
            opcode = S_EXPR_PARAM.ONESHOT
            func_index = self.oneshot_hash_index[node.func_hash] or 0
        elseif node.call_type == "io_call" then
            opcode = bit.bor(S_EXPR_PARAM.ONESHOT, S_EXPR_FLAG_SURVIVES_RESET)
            func_index = self.oneshot_hash_index[node.func_hash] or 0
        elseif node.call_type == "m_call" then
            opcode = S_EXPR_PARAM.MAIN
            func_index = self.main_hash_index[node.func_hash] or 0
        elseif node.call_type == "pt_m_call" then
            opcode = bit.bor(S_EXPR_PARAM.MAIN, S_EXPR_FLAG_POINTER)
            func_index = self.main_hash_index[node.func_hash] or 0
        elseif node.call_type == "p_call" then
            opcode = S_EXPR_PARAM.PRED
            func_index = self.pred_hash_index[node.func_hash] or 0
        elseif node.call_type == "p_call_composite" then
            opcode = bit.bor(S_EXPR_PARAM.PRED, S_EXPR_FLAG_SURVIVES_RESET)
            func_index = self.pred_hash_index[node.func_hash] or 0
        else
            opcode = S_EXPR_PARAM.MAIN
            func_index = 0
        end
        
        local node_index = current_node_idx
        current_node_idx = current_node_idx + 1
        
        local idx_to_ptr = node.pointer_index or 0
        local content_count = self:count_node_params(node)
        
        -- OPEN_CALL: parent_offset points to enclosing OPEN_CALL
        local parent_offset = current_parent_offset()
        self:emit_param_struct(e, S_EXPR_PARAM.OPEN_CALL, idx_to_ptr, content_count, parent_offset)
        
        -- Push this OPEN_CALL's param_count as the new parent for children
        table.insert(parent_call_stack, param_count)
        param_count = param_count + 1
        
        self:emit_param_struct(e, opcode, idx_to_ptr, node_index, func_index)
        param_count = param_count + 1
        
        -- Merge params and children, sort by order
        local items = {}
        
        for _, param in ipairs(node.params) do
            table.insert(items, {
                type = "param",
                order = param.order or 0,
                data = param
            })
        end
        
        for _, child in ipairs(node.children) do
            table.insert(items, {
                type = "child",
                order = child.order or 0,
                data = child
            })
        end
        
        table.sort(items, function(a, b)
            return a.order < b.order
        end)
        
        for _, item in ipairs(items) do
            if item.type == "param" then
                local param = item.data
                if param.type == "list_start" then
                    local open_byte_pos = e:get_pos()
                    local open_param_idx = param_count
                    local po = current_parent_offset()
                    self:emit_param_struct(e, S_EXPR_PARAM.OPEN, 0, 0, po)
                    table.insert(brace_stack, {byte_pos = open_byte_pos, param_idx = open_param_idx, brace_type = "list"})
                    param_count = param_count + 1
                elseif param.type == "list_end" then
                    local open_info = table.remove(brace_stack)
                    if open_info and open_info.brace_type == "list" then
                        local close_param_idx = param_count
                        local brace_offset = close_param_idx - open_info.param_idx
                        local patch_offset = self.is_64bit and (open_info.byte_pos + 8) or (open_info.byte_pos + 4)
                        e:patch_u16(patch_offset, brace_offset)
                        local po = current_parent_offset()
                        self:emit_param_struct(e, S_EXPR_PARAM.CLOSE, 0, brace_offset, po)
                    else
                        local po = current_parent_offset()
                        self:emit_param_struct(e, S_EXPR_PARAM.CLOSE, 0, 0, po)
                    end
                    param_count = param_count + 1
                elseif param.type == "dict_start" then
                    local open_byte_pos = e:get_pos()
                    local open_param_idx = param_count
                    local po = current_parent_offset()
                    self:emit_param_struct(e, S_EXPR_PARAM.OPEN_DICT, 0, 0, po)
                    table.insert(brace_stack, {byte_pos = open_byte_pos, param_idx = open_param_idx, brace_type = "dict"})
                    param_count = param_count + 1
                elseif param.type == "dict_end" then
                    local open_info = table.remove(brace_stack)
                    if open_info and open_info.brace_type == "dict" then
                        local close_param_idx = param_count
                        local brace_offset = close_param_idx - open_info.param_idx
                        local patch_offset = self.is_64bit and (open_info.byte_pos + 8) or (open_info.byte_pos + 4)
                        e:patch_u16(patch_offset, brace_offset)
                        local po = current_parent_offset()
                        self:emit_param_struct(e, S_EXPR_PARAM.CLOSE_DICT, 0, brace_offset, po)
                    else
                        local po = current_parent_offset()
                        self:emit_param_struct(e, S_EXPR_PARAM.CLOSE_DICT, 0, 0, po)
                    end
                    param_count = param_count + 1
                elseif param.type == "dict_key" then
                    local open_byte_pos = e:get_pos()
                    local open_param_idx = param_count
                    local key_hash = hash_module.fnv1a_32(param.value)
                    -- OPEN_KEY uses the full 32-bit value field for key_hash,
                    -- so parent_offset is not stored here (hash takes priority)
                    self:emit_param_struct(e, S_EXPR_PARAM.OPEN_KEY, 0, nil, nil, key_hash)
                    table.insert(brace_stack, {byte_pos = open_byte_pos, param_idx = open_param_idx, brace_type = "dict_key"})
                    param_count = param_count + 1
                elseif param.type == "dict_key_hash" then
                    local open_byte_pos = e:get_pos()
                    local open_param_idx = param_count
                    -- OPEN_KEY uses the full 32-bit value field for key_hash
                    self:emit_param_struct(e, S_EXPR_PARAM.OPEN_KEY, 0, nil, nil, param.value)
                    table.insert(brace_stack, {byte_pos = open_byte_pos, param_idx = open_param_idx, brace_type = "dict_key"})
                    param_count = param_count + 1
                elseif param.type == "end_dict_key" then
                    local open_info = table.remove(brace_stack)
                    if open_info and open_info.brace_type == "dict_key" then
                        local close_param_idx = param_count
                        local brace_offset = close_param_idx - open_info.param_idx
                        local po = current_parent_offset()
                        self:emit_param_struct(e, S_EXPR_PARAM.CLOSE_KEY, 0, brace_offset, po)
                    else
                        local po = current_parent_offset()
                        self:emit_param_struct(e, S_EXPR_PARAM.CLOSE_KEY, 0, 0, po)
                    end
                    param_count = param_count + 1
                elseif param.type == "array_start" then
                    local open_byte_pos = e:get_pos()
                    local open_param_idx = param_count
                    local po = current_parent_offset()
                    self:emit_param_struct(e, S_EXPR_PARAM.OPEN_ARRAY, 0, 0, po)
                    table.insert(brace_stack, {byte_pos = open_byte_pos, param_idx = open_param_idx, brace_type = "array"})
                    param_count = param_count + 1
                elseif param.type == "array_end" then
                    local open_info = table.remove(brace_stack)
                    if open_info and open_info.brace_type == "array" then
                        local close_param_idx = param_count
                        local brace_offset = close_param_idx - open_info.param_idx
                        local patch_offset = self.is_64bit and (open_info.byte_pos + 8) or (open_info.byte_pos + 4)
                        e:patch_u16(patch_offset, brace_offset)
                        local po = current_parent_offset()
                        self:emit_param_struct(e, S_EXPR_PARAM.CLOSE_ARRAY, 0, brace_offset, po)
                    else
                        local po = current_parent_offset()
                        self:emit_param_struct(e, S_EXPR_PARAM.CLOSE_ARRAY, 0, 0, po)
                    end
                    param_count = param_count + 1
                elseif param.type == "tuple_start" then
                    local open_byte_pos = e:get_pos()
                    local open_param_idx = param_count
                    local po = current_parent_offset()
                    self:emit_param_struct(e, S_EXPR_PARAM.OPEN_TUPLE, 0, 0, po)
                    table.insert(brace_stack, {byte_pos = open_byte_pos, param_idx = open_param_idx, brace_type = "tuple"})
                    param_count = param_count + 1
                elseif param.type == "tuple_end" then
                    local open_info = table.remove(brace_stack)
                    if open_info and open_info.brace_type == "tuple" then
                        local close_param_idx = param_count
                        local brace_offset = close_param_idx - open_info.param_idx
                        local patch_offset = self.is_64bit and (open_info.byte_pos + 8) or (open_info.byte_pos + 4)
                        e:patch_u16(patch_offset, brace_offset)
                        local po = current_parent_offset()
                        self:emit_param_struct(e, S_EXPR_PARAM.CLOSE_TUPLE, 0, brace_offset, po)
                    else
                        local po = current_parent_offset()
                        self:emit_param_struct(e, S_EXPR_PARAM.CLOSE_TUPLE, 0, 0, po)
                    end
                    param_count = param_count + 1
                else
                    param_count = param_count + self:emit_dsl_param(e, param)
                end
            else
                emit_node(item.data)
            end
        end
        
        -- CLOSE for the OPEN_CALL: pop parent, compute offset back to our OPEN_CALL
        local my_open_call_idx = table.remove(parent_call_stack)
        local close_parent_offset = param_count - my_open_call_idx
        self:emit_param_struct(e, S_EXPR_PARAM.CLOSE, 0, close_parent_offset, current_parent_offset())
        param_count = param_count + 1
    end
    
    for _, node in ipairs(tree.nodes) do
        emit_node(node)
    end
    
    return param_count
end

function BinaryModuleGenerator:generate()
    local e = BinaryEmitter.new()
    local mod = self.module
    
    -- Header
    e:emit_u32(SEXB_MAGIC)
    e:emit_u16(SEXB_VERSION)
    
    local flags = self.is_64bit and SEXB_FLAG_64BIT or SEXB_FLAG_32BIT
    if mod.debug then flags = bit.bor(flags, SEXB_FLAG_DEBUG) end
    e:emit_u16(flags)
    
    e:emit_u32(mod.name_hash)
    e:emit_u16(#mod.tree_order)
    e:emit_u16(#mod.record_order)
    e:emit_u16(#mod.string_table)
    e:emit_u16(#mod.const_order)
    e:emit_u16(#mod.oneshot_funcs)
    e:emit_u16(#mod.main_funcs)
    e:emit_u16(#mod.pred_funcs)
    e:emit_u16(0)
    
    local size_patch = e:get_pos()
    e:emit_u32(0)
    
    -- Directory
    local dir_start = e:get_pos()
    for i = 1, 8 do
        e:emit_u32(0)
    end
    
    -- Trees
    local tree_offset = e:get_pos()
    e:patch_u32(dir_start, tree_offset)
    
    local tree_param_patches = {}
    for _, name in ipairs(mod.tree_order) do
        local tree = mod.trees[name]
        
        e:emit_u32(tree.name_hash)
        
        local rec_hash = 0
        if tree.record_name and mod.records[tree.record_name] then
            rec_hash = mod.records[tree.record_name].name_hash
        end
        e:emit_u32(rec_hash)
        
        e:emit_u16(tree.node_count)
        e:emit_u16(tree.pointer_count or 0)
        e:emit_u16(tree.defaults_index or 0xFFFF)
        e:emit_u16(0)
        
        local param_patch = e:get_pos()
        e:emit_u32(0)
        e:emit_u16(0)
        e:emit_u16(0)
        
        table.insert(tree_param_patches, {
            tree = tree,
            offset_patch = param_patch,
            count_patch = param_patch + 4,
        })
    end
    
    -- Records
    local record_offset = e:get_pos()
    e:patch_u32(dir_start + 4, record_offset)
    
    local field_patches = {}
    for _, name in ipairs(mod.record_order) do
        local rec = mod.records[name]
        
        e:emit_u32(rec.name_hash)
        e:emit_u16(#rec.fields)
        e:emit_u16(rec.size)
        
        local field_patch = e:get_pos()
        e:emit_u32(0)
        
        table.insert(field_patches, {
            record = rec,
            offset_patch = field_patch
        })
    end
    
    -- Fields
    local field_offset = e:get_pos()
    e:patch_u32(dir_start + 8, field_offset)
    
    for _, patch in ipairs(field_patches) do
        e:patch_u32(patch.offset_patch, e:get_pos())
        
        for _, field in ipairs(patch.record.fields) do
            e:emit_u32(field.name_hash)
            e:emit_u8(field.type_tag or 0x07)
            
            local field_flags = 0
            if field.is_pointer then field_flags = bit.bor(field_flags, 0x01) end
            if field.is_char_array then field_flags = bit.bor(field_flags, 0x02) end
            if field.is_embedded then field_flags = bit.bor(field_flags, 0x04) end
            if field.is_ptr64 then field_flags = bit.bor(field_flags, 0x08) end
            e:emit_u8(field_flags)
            
            e:emit_u16(field.offset)
            e:emit_u16(field.size)
            
            local aux = 0
            if field.is_char_array then
                aux = field.array_len
            elseif field.is_pointer and field.target_type then
                aux = self.record_index[field.target_type] or 0
            elseif field.is_embedded and field.embedded_record then
                aux = self.record_index[field.embedded_record] or 0
            end
            e:emit_u16(aux)
        end
    end
    
    -- String blob
    local string_offset = e:get_pos()
    e:patch_u32(dir_start + 12, string_offset)
    
    for _, s in ipairs(mod.string_table) do
        e:emit_string(s)
    end
    e:align(4)
    
    -- Constants
    local const_offset = e:get_pos()
    e:patch_u32(dir_start + 16, const_offset)
    
    local const_data_patches = {}
    for _, name in ipairs(mod.const_order) do
        local cnst = mod.constants[name]
        local rec = mod.records[cnst.record_type]
        
        e:emit_u32(cnst.name_hash)
        e:emit_u16(self.record_index[cnst.record_type] or 0)
        e:emit_u16(rec and rec.size or 0)
        
        local data_patch = e:get_pos()
        e:emit_u32(0)
        
        table.insert(const_data_patches, {
            const = cnst,
            offset_patch = data_patch,
            size = rec and rec.size or 0
        })
    end
    
    -- Constant data
    local const_data_offset = e:get_pos()
    e:patch_u32(dir_start + 20, const_data_offset)
    
    for _, patch in ipairs(const_data_patches) do
        e:patch_u32(patch.offset_patch, e:get_pos())
        
        if patch.const.data_bytes then
            e:emit_bytes(patch.const.data_bytes)
        else
            for i = 1, patch.size do
                e:emit_u8(0)
            end
        end
        e:align(4)
    end
    
    -- Function hash tables
    local func_offset = e:get_pos()
    e:patch_u32(dir_start + 24, func_offset)
    
    for _, name in ipairs(mod.oneshot_funcs) do
        e:emit_u32(hash_module.fnv1a_32(name))
    end
    for _, name in ipairs(mod.main_funcs) do
        e:emit_u32(hash_module.fnv1a_32(name))
    end
    for _, name in ipairs(mod.pred_funcs) do
        e:emit_u32(hash_module.fnv1a_32(name))
    end
    
    -- Parameters
    local params_offset = e:get_pos()
    e:patch_u32(dir_start + 28, params_offset)
    
    e:align(self.param_size)
    
    for _, patch in ipairs(tree_param_patches) do
        local tree = patch.tree
        self.current_tree_record = tree.record_name
        
        local start_pos = e:get_pos()
        e:patch_u32(patch.offset_patch, start_pos)
        
        local param_count = self:emit_tree_params(e, tree)
        e:patch_u16(patch.count_patch, param_count)
        
        e:align(self.param_size)
    end
    
    self.current_tree_record = nil
    
    -- Finalize
    e:patch_u32(size_patch, e:get_pos())
    
    return e:to_bytes(), e:get_pos()
end

function BinaryModuleGenerator:to_binary_file(output_path)
    local bytes, size = self:generate()
    
    local f = io.open(output_path, "wb")
    if not f then
        error("Cannot open output file: " .. output_path)
    end
    
    for _, b in ipairs(bytes) do
        f:write(string.char(b))
    end
    f:close()
    
    return size
end

function BinaryModuleGenerator:to_c_header(base_name)
    local bytes, size = self:generate()
    local lines = {}
    
    local mode_suffix = self.is_64bit and "_64" or "_32"
    local guard = base_name:upper() .. "_BIN" .. mode_suffix:upper() .. "_H"
    local var_name = base_name:lower() .. "_module_bin" .. mode_suffix
    
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "// " .. base_name .. "_bin" .. mode_suffix .. ".h")
    table.insert(lines, "// Generated binary module data for " .. self.module.name)
    table.insert(lines, "// Mode: " .. (self.is_64bit and "64-bit" or "32-bit"))
    table.insert(lines, "// Version: 5.3 (direct s_expr_param_t, zero-copy, parent_offset)")
    table.insert(lines, "// DO NOT EDIT - Generated by s_expr_dsl v5.3")
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "")
    table.insert(lines, "#ifndef " .. guard)
    table.insert(lines, "#define " .. guard)
    table.insert(lines, "")
    table.insert(lines, "#include <stdint.h>")
    table.insert(lines, "")
    table.insert(lines, string.format("#define %s_SIZE %d", var_name:upper(), size))
    table.insert(lines, string.format("#define %s_HASH %s", var_name:upper(), hash_module.fmt_hash(self.module.name_hash)))
    table.insert(lines, string.format("#define %s_IS_64BIT %d", var_name:upper(), self.is_64bit and 1 or 0))
    table.insert(lines, "")
    table.insert(lines, string.format("static const uint8_t %s[%d] __attribute__((aligned(%d))) = {", 
                                       var_name, size, self.param_size))
    
    local row = {}
    for i, b in ipairs(bytes) do
        table.insert(row, string.format("0x%02X", b))
        if #row == 16 or i == size then
            local comma = (i == size) and "" or ","
            table.insert(lines, "    " .. table.concat(row, ", ") .. comma)
            row = {}
        end
    end
    
    table.insert(lines, "};")
    table.insert(lines, "")
    table.insert(lines, "#endif // " .. guard)
    
    return table.concat(lines, "\n")
end

function BinaryModuleGenerator:get_func_index(node)
    if node.call_type == "o_call" or node.call_type == "io_call" then
        return self.oneshot_hash_index[node.func_hash] or 0
    elseif node.call_type == "m_call" or node.call_type == "pt_m_call" then
        return self.main_hash_index[node.func_hash] or 0
    elseif node.call_type == "p_call" or node.call_type == "p_call_composite" then
        return self.pred_hash_index[node.func_hash] or 0
    end
    return 0
end

M.BinaryModuleGenerator = BinaryModuleGenerator

return M