-- ============================================================================
-- s_expr_debug.lua
-- S-Expression Engine Debug Output Generators - Version 5.2
-- 
-- Contains:
--   - generate_debug_header() - Debug header with hash->name mappings
--   - to_debug_dump() - Human-readable parameter dump
--
-- Loaded by s_expr_dsl.lua via dofile()
-- ============================================================================

local ffi = require("ffi")
local bit = require("bit")

local M = {}
local hash_module = nil
local types_module = nil

-- Called by s_expr_dsl.lua to inject dependencies
function M._init(hash, types)
    hash_module = hash
    types_module = types
end

-- ============================================================================
-- DEBUG HEADER GENERATOR
-- ============================================================================

function M.generate_debug_header(module)
    local lines = {}
    
    local guard = string.upper(module.name) .. "_DEBUG_H"
    local prefix = string.upper(module.name)
    
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "// " .. module.name .. "_debug.h")
    table.insert(lines, "// DEBUG INFORMATION - Auto-generated by s_expr_dsl.lua v5.2")
    table.insert(lines, "// Module: " .. module.name)
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "")
    table.insert(lines, "#ifndef " .. guard)
    table.insert(lines, "#define " .. guard)
    table.insert(lines, "")
    table.insert(lines, "#include <stdint.h>")
    table.insert(lines, "#include <stdio.h>")
    table.insert(lines, "")
    
    local tree_order = module.tree_order or {}
    local trees = module.trees or {}
    local record_order = module.record_order or {}
    local records = module.records or {}
    local oneshot_funcs = module.oneshot_funcs or {}
    local main_funcs = module.main_funcs or {}
    local pred_funcs = module.pred_funcs or {}
    
    -- Tree debug info
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "// TREE DEBUG INFO")
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "")
    table.insert(lines, "typedef struct {")
    table.insert(lines, "    uint32_t    hash;")
    table.insert(lines, "    const char* name;")
    table.insert(lines, "    uint16_t    node_count;")
    table.insert(lines, "    uint16_t    pointer_count;")
    table.insert(lines, "    uint16_t    param_count;")
    table.insert(lines, "} " .. module.name .. "_tree_debug_t;")
    table.insert(lines, "")
    
    table.insert(lines, "static const " .. module.name .. "_tree_debug_t " .. module.name .. "_tree_debug[] = {")
    if #tree_order > 0 then
        for i, tree_name in ipairs(tree_order) do
            local tree = trees[tree_name] or {}
            local name_hash = tree.name_hash or hash_module.fnv1a_32(tree_name)
            local node_count = tree.node_count or 0
            local pointer_count = tree.pointer_count or 0
            local param_count = tree.params and #tree.params or 0
            table.insert(lines, string.format(
                '    { 0x%08X, "%s", %d, %d, %d },',
                name_hash, tree_name, node_count, pointer_count, param_count
            ))
        end
    else
        table.insert(lines, '    { 0, "", 0, 0, 0 },  // Empty placeholder')
    end
    table.insert(lines, "};")
    table.insert(lines, string.format("#define %s_TREE_DEBUG_COUNT %d", prefix, math.max(1, #tree_order)))
    table.insert(lines, "")
    
    -- Function debug info
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "// FUNCTION DEBUG INFO")
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "")
    table.insert(lines, "typedef struct {")
    table.insert(lines, "    uint32_t    hash;")
    table.insert(lines, "    const char* name;")
    table.insert(lines, "    uint16_t    index;")
    table.insert(lines, "} " .. module.name .. "_func_debug_t;")
    table.insert(lines, "")
    
    local function emit_func_table(func_list, table_name, count_name)
        table.insert(lines, "static const " .. module.name .. "_func_debug_t " .. module.name .. "_" .. table_name .. "[] = {")
        if #func_list > 0 then
            for i, name in ipairs(func_list) do
                local h = hash_module.fnv1a_32(name)
                table.insert(lines, string.format(
                    '    { 0x%08X, "%s", %d },',
                    h, name, i - 1
                ))
            end
        else
            table.insert(lines, '    { 0, "", 0 },  // Empty placeholder')
        end
        table.insert(lines, "};")
        table.insert(lines, string.format("#define %s_%s %d", prefix, count_name, math.max(1, #func_list)))
        table.insert(lines, "")
    end
    
    table.insert(lines, "// Oneshot functions")
    emit_func_table(oneshot_funcs, "oneshot_debug", "ONESHOT_DEBUG_COUNT")
    
    table.insert(lines, "// Main functions")
    emit_func_table(main_funcs, "main_debug", "MAIN_DEBUG_COUNT")
    
    table.insert(lines, "// Predicate functions")
    emit_func_table(pred_funcs, "pred_debug", "PRED_DEBUG_COUNT")
    
    -- Record debug info
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "// RECORD DEBUG INFO")
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "")
    table.insert(lines, "typedef struct {")
    table.insert(lines, "    uint32_t    hash;")
    table.insert(lines, "    const char* name;")
    table.insert(lines, "    uint16_t    offset;")
    table.insert(lines, "    uint16_t    size;")
    table.insert(lines, "} " .. module.name .. "_field_debug_t;")
    table.insert(lines, "")
    table.insert(lines, "typedef struct {")
    table.insert(lines, "    uint32_t    hash;")
    table.insert(lines, "    const char* name;")
    table.insert(lines, "    uint16_t    size;")
    table.insert(lines, "    uint16_t    field_count;")
    table.insert(lines, "    const " .. module.name .. "_field_debug_t* fields;")
    table.insert(lines, "} " .. module.name .. "_record_debug_t;")
    table.insert(lines, "")
    
    -- Emit field tables for each record
    for _, record_name in ipairs(record_order) do
        local record = records[record_name] or {}
        local record_fields = record.fields or {}
        local field_table_name = module.name .. "_" .. string.lower(record_name) .. "_fields_debug"
        table.insert(lines, "static const " .. module.name .. "_field_debug_t " .. field_table_name .. "[] = {")
        if #record_fields > 0 then
            for _, field in ipairs(record_fields) do
                local field_name = field.name or "unknown"
                table.insert(lines, string.format(
                    '    { 0x%08X, "%s", %d, %d },',
                    hash_module.fnv1a_32(field_name), field_name, field.offset or 0, field.size or 0
                ))
            end
        else
            table.insert(lines, '    { 0, "", 0, 0 },  // Empty placeholder')
        end
        table.insert(lines, "};")
        table.insert(lines, "")
    end
    
    -- Emit record table
    table.insert(lines, "static const " .. module.name .. "_record_debug_t " .. module.name .. "_record_debug[] = {")
    if #record_order > 0 then
        for _, record_name in ipairs(record_order) do
            local record = records[record_name] or {}
            local record_fields = record.fields or {}
            local field_table_name = module.name .. "_" .. string.lower(record_name) .. "_fields_debug"
            table.insert(lines, string.format(
                '    { 0x%08X, "%s", %d, %d, %s },',
                hash_module.fnv1a_32(record_name), record_name, record.size or 0, #record_fields, field_table_name
            ))
        end
    else
        table.insert(lines, '    { 0, "", 0, 0, NULL },  // Empty placeholder')
    end
    table.insert(lines, "};")
    table.insert(lines, string.format("#define %s_RECORD_DEBUG_COUNT %d", prefix, math.max(1, #record_order)))
    table.insert(lines, "")
    
    -- Lookup functions
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "// DEBUG LOOKUP FUNCTIONS")
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "")
    
    table.insert(lines, "static inline const char* " .. module.name .. "_find_tree_name(uint32_t hash) {")
    table.insert(lines, "    for (int i = 0; i < " .. prefix .. "_TREE_DEBUG_COUNT; i++) {")
    table.insert(lines, "        if (" .. module.name .. "_tree_debug[i].hash == hash) return " .. module.name .. "_tree_debug[i].name;")
    table.insert(lines, "    }")
    table.insert(lines, '    return "UNKNOWN";')
    table.insert(lines, "}")
    table.insert(lines, "")
    
    table.insert(lines, "static inline const char* " .. module.name .. "_find_main_name(uint32_t hash) {")
    table.insert(lines, "    for (int i = 0; i < " .. prefix .. "_MAIN_DEBUG_COUNT; i++) {")
    table.insert(lines, "        if (" .. module.name .. "_main_debug[i].hash == hash) return " .. module.name .. "_main_debug[i].name;")
    table.insert(lines, "    }")
    table.insert(lines, '    return "UNKNOWN";')
    table.insert(lines, "}")
    table.insert(lines, "")
    
    table.insert(lines, "static inline const char* " .. module.name .. "_find_oneshot_name(uint32_t hash) {")
    table.insert(lines, "    for (int i = 0; i < " .. prefix .. "_ONESHOT_DEBUG_COUNT; i++) {")
    table.insert(lines, "        if (" .. module.name .. "_oneshot_debug[i].hash == hash) return " .. module.name .. "_oneshot_debug[i].name;")
    table.insert(lines, "    }")
    table.insert(lines, '    return "UNKNOWN";')
    table.insert(lines, "}")
    table.insert(lines, "")
    
    table.insert(lines, "static inline const char* " .. module.name .. "_find_pred_name(uint32_t hash) {")
    table.insert(lines, "    for (int i = 0; i < " .. prefix .. "_PRED_DEBUG_COUNT; i++) {")
    table.insert(lines, "        if (" .. module.name .. "_pred_debug[i].hash == hash) return " .. module.name .. "_pred_debug[i].name;")
    table.insert(lines, "    }")
    table.insert(lines, '    return "UNKNOWN";')
    table.insert(lines, "}")
    table.insert(lines, "")
    
    table.insert(lines, "static inline const char* " .. module.name .. "_find_record_name(uint32_t hash) {")
    table.insert(lines, "    for (int i = 0; i < " .. prefix .. "_RECORD_DEBUG_COUNT; i++) {")
    table.insert(lines, "        if (" .. module.name .. "_record_debug[i].hash == hash) return " .. module.name .. "_record_debug[i].name;")
    table.insert(lines, "    }")
    table.insert(lines, '    return "UNKNOWN";')
    table.insert(lines, "}")
    table.insert(lines, "")
    
    table.insert(lines, "#endif // " .. guard)
    table.insert(lines, "")
    
    return table.concat(lines, "\n")
end

function M.write_debug_header(module, output_path)
    local content = M.generate_debug_header(module)
    local path = output_path or "./" .. module.name .. "_debug.h"
    local f = io.open(path, "w")
    if f then
        f:write(content)
        f:close()
        print("Generated: " .. path)
    else
        error("Failed to write: " .. path)
    end
end

-- ============================================================================
-- PARAMETER DUMP GENERATOR
-- ============================================================================

-- ============================================================================
-- PARAMETER DUMP GENERATOR (with full hex information)
-- ============================================================================

function M.to_debug_dump(bin_gen, base_name)
    local lines = {}
    local mod = bin_gen.module
    local is_64bit = bin_gen.is_64bit
    local mode_suffix = is_64bit and "_64" or "_32"
    local guard = base_name:upper() .. "_DUMP" .. mode_suffix:upper() .. "_H"
    
    local S_EXPR_PARAM = types_module.S_EXPR_PARAM
    
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "// " .. base_name .. "_dump" .. mode_suffix .. ".h")
    table.insert(lines, "// DEBUG PARAMETER DUMP for " .. mod.name)
    table.insert(lines, "// Mode: " .. (is_64bit and "64-bit" or "32-bit"))
    table.insert(lines, "// Generated by s_expr_dsl v5.2")
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "")
    table.insert(lines, "#ifndef " .. guard)
    table.insert(lines, "#define " .. guard)
    table.insert(lines, "")
    
    -- Type code reference
    table.insert(lines, "/*")
    table.insert(lines, " * PARAMETER TYPE CODES:")
    table.insert(lines, " *   0x00 INT          0x01 UINT         0x02 FLOAT        0x03 STR_HASH")
    table.insert(lines, " *   0x04 SLOT         0x05 OPEN         0x06 CLOSE        0x07 OPEN_CALL")
    table.insert(lines, " *   0x08 ONESHOT      0x09 MAIN         0x0A PRED         0x0B FIELD")
    table.insert(lines, " *   0x0C RESULT       0x0D STR_IDX      0x0E CONST_REF    0x0F RESERVED")
    table.insert(lines, " *   0x10 OPEN_DICT    0x11 CLOSE_DICT   0x12 OPEN_KEY     0x13 CLOSE_KEY")
    table.insert(lines, " *   0x14 OPEN_ARRAY   0x15 CLOSE_ARRAY  0x16 OPEN_TUPLE   0x17 CLOSE_TUPLE")
    table.insert(lines, " *")
    table.insert(lines, " * FLAGS:")
    table.insert(lines, " *   0x40 SURVIVES_RESET (io_call, p_call_composite)")
    table.insert(lines, " *   0x80 POINTER        (pt_m_call)")
    table.insert(lines, " */")
    table.insert(lines, "")
    
    table.insert(lines, "/*")
    table.insert(lines, " * Module: " .. mod.name)
    table.insert(lines, string.format(" * Hash:   0x%08X", mod.name_hash))
    table.insert(lines, " * Trees:  " .. #mod.tree_order)
    table.insert(lines, " * Records: " .. #mod.record_order)
    table.insert(lines, " * Strings: " .. #mod.string_table)
    table.insert(lines, " * Constants: " .. #mod.const_order)
    table.insert(lines, " * Param size: " .. (is_64bit and "16 bytes (64-bit)" or "8 bytes (32-bit)"))
    table.insert(lines, " */")
    table.insert(lines, "")
    
    -- String table dump with hex indices
    if #mod.string_table > 0 then
        table.insert(lines, "// ============================================================================")
        table.insert(lines, "// STRING TABLE")
        table.insert(lines, "// ============================================================================")
        table.insert(lines, "/*")
        for i, s in ipairs(mod.string_table) do
            local escaped = s:gsub("\\", "\\\\"):gsub('"', '\\"'):gsub("\n", "\\n"):gsub("\r", "\\r")
            local hash = hash_module.fnv1a_32(s)
            table.insert(lines, string.format(" * [0x%04X] (%3d) hash=0x%08X \"%s\"", 
                i - 1, i - 1, hash, escaped))
        end
        table.insert(lines, " */")
        table.insert(lines, "")
    end
    
    -- Function tables dump with hashes
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "// FUNCTION TABLES")
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "/*")
    if #mod.oneshot_funcs > 0 then
        table.insert(lines, " * ONESHOT FUNCTIONS (type=0x08, with 0x40=io_call):")
        for i, name in ipairs(mod.oneshot_funcs) do
            local hash = hash_module.fnv1a_32(name)
            table.insert(lines, string.format(" *   [0x%04X] (%2d) hash=0x%08X %s", 
                i - 1, i - 1, hash, name))
        end
        table.insert(lines, " *")
    end
    if #mod.main_funcs > 0 then
        table.insert(lines, " * MAIN FUNCTIONS (type=0x09, with 0x80=pt_m_call):")
        for i, name in ipairs(mod.main_funcs) do
            local hash = hash_module.fnv1a_32(name)
            table.insert(lines, string.format(" *   [0x%04X] (%2d) hash=0x%08X %s", 
                i - 1, i - 1, hash, name))
        end
        table.insert(lines, " *")
    end
    if #mod.pred_funcs > 0 then
        table.insert(lines, " * PRED FUNCTIONS (type=0x0A, with 0x40=p_call_composite):")
        for i, name in ipairs(mod.pred_funcs) do
            local hash = hash_module.fnv1a_32(name)
            table.insert(lines, string.format(" *   [0x%04X] (%2d) hash=0x%08X %s", 
                i - 1, i - 1, hash, name))
        end
    end
    table.insert(lines, " */")
    table.insert(lines, "")
    
    -- Record table dump
    if #mod.record_order > 0 then
        table.insert(lines, "// ============================================================================")
        table.insert(lines, "// RECORD DEFINITIONS")
        table.insert(lines, "// ============================================================================")
        table.insert(lines, "/*")
        for i, rec_name in ipairs(mod.record_order) do
            local rec = mod.records[rec_name]
            table.insert(lines, string.format(" * RECORD[0x%04X]: %s (size=%d, align=%d, hash=0x%08X)",
                i - 1, rec_name, rec.size, rec.align, rec.name_hash))
            for j, field in ipairs(rec.fields) do
                local flags = ""
                if field.is_pointer then flags = flags .. " PTR" end
                if field.is_ptr64 then flags = flags .. "64" end
                if field.is_char_array then flags = flags .. " CHAR[" .. field.array_len .. "]" end
                if field.is_int32_array then flags = flags .. " INT32[" .. field.array_len .. "]" end
                if field.is_float32_array then flags = flags .. " FLOAT32[" .. field.array_len .. "]" end
                if field.is_embedded then flags = flags .. " EMBED:" .. field.embedded_record end
                table.insert(lines, string.format(" *   [%2d] off=0x%04X size=%2d hash=0x%08X %s%s",
                    j - 1, field.offset, field.size, field.name_hash, field.name, flags))
            end
            table.insert(lines, " *")
        end
        table.insert(lines, " */")
        table.insert(lines, "")
    end
    
    -- Constants dump
    if #mod.const_order > 0 then
        table.insert(lines, "// ============================================================================")
        table.insert(lines, "// CONSTANTS")
        table.insert(lines, "// ============================================================================")
        table.insert(lines, "/*")
        for i, const_name in ipairs(mod.const_order) do
            local cnst = mod.constants[const_name]
            table.insert(lines, string.format(" * CONST[0x%04X]: %s (record=%s, hash=0x%08X)",
                i - 1, const_name, cnst.record_type, cnst.name_hash))
            if cnst.data_bytes then
                local hex_line = " *   bytes: "
                for j, b in ipairs(cnst.data_bytes) do
                    hex_line = hex_line .. string.format("%02X ", b)
                    if j % 16 == 0 and j < #cnst.data_bytes then
                        table.insert(lines, hex_line)
                        hex_line = " *          "
                    end
                end
                table.insert(lines, hex_line)
            end
        end
        table.insert(lines, " */")
        table.insert(lines, "")
    end
    
    -- Tree parameter dumps
    table.insert(lines, "// ============================================================================")
    table.insert(lines, "// TREE PARAMETERS")
    table.insert(lines, "// ============================================================================")
    
    for _, tree_name in ipairs(mod.tree_order) do
        local tree = mod.trees[tree_name]
        
        -- Get record info if available
        local rec = nil
        if tree.record_name then
            rec = mod.records[tree.record_name]
        end
        
        table.insert(lines, "/*")
        table.insert(lines, string.format(" * TREE: %s", tree_name))
        table.insert(lines, string.format(" *   hash=0x%08X nodes=%d ptrs=%d", 
            tree.name_hash, tree.node_count, tree.pointer_count or 0))
        if tree.record_name then
            table.insert(lines, string.format(" *   record=%s (hash=0x%08X)", 
                tree.record_name, rec and rec.name_hash or 0))
        end
        if tree.defaults_name then
            table.insert(lines, string.format(" *   defaults=%s (idx=0x%04X)", 
                tree.defaults_name, tree.defaults_index))
        end
        table.insert(lines, " *")
        table.insert(lines, " * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS")
        table.insert(lines, " * -------------------------------------------------------------------------")
        
        local param_idx = 0
        local brace_stack = {}
        
        local function resolve_field_offset(field_name)
            if not rec then return nil, nil end
            for _, field in ipairs(rec.fields) do
                if field.name == field_name then
                    return field.offset, field.size
                end
            end
            return nil, nil
        end
        
        local function resolve_nested_field_offset(path)
            if not rec then return nil, nil end
            local parts = {}
            for part in path:gmatch("[^.]+") do
                table.insert(parts, part)
            end
            
            local offset = 0
            local current_rec = rec
            local field = nil
            
            for i, part in ipairs(parts) do
                field = nil
                for _, f in ipairs(current_rec.fields) do
                    if f.name == part then
                        field = f
                        break
                    end
                end
                if not field then return nil, nil end
                offset = offset + field.offset
                if i < #parts and field.is_embedded then
                    current_rec = mod.records[field.embedded_record]
                    if not current_rec then return nil, nil end
                end
            end
            return offset, field and field.size or 0
        end
        
        local function fmt_hex32(v)
            if v < 0 then v = 0x100000000 + v end
            return string.format("0x%08X", v)
        end
        
        local function dump_node(node, depth)
            local indent = string.rep("  ", depth)
            local pi = indent .. "  "  -- param indent (extra 2 spaces)
            
            -- Determine opcode for this call type
            local opcode, opcode_name
            if node.call_type == "o_call" then
                opcode = S_EXPR_PARAM.ONESHOT
                opcode_name = "ONESHOT"
            elseif node.call_type == "io_call" then
                opcode = bit.bor(S_EXPR_PARAM.ONESHOT, 0x40)
                opcode_name = "ONESHOT+SR"
            elseif node.call_type == "m_call" then
                opcode = S_EXPR_PARAM.MAIN
                opcode_name = "MAIN"
            elseif node.call_type == "pt_m_call" then
                opcode = bit.bor(S_EXPR_PARAM.MAIN, 0x80)
                opcode_name = "MAIN+PTR"
            elseif node.call_type == "p_call" then
                opcode = S_EXPR_PARAM.PRED
                opcode_name = "PRED"
            elseif node.call_type == "p_call_composite" then
                opcode = bit.bor(S_EXPR_PARAM.PRED, 0x40)
                opcode_name = "PRED+SR"
            else
                opcode = S_EXPR_PARAM.MAIN
                opcode_name = "MAIN"
            end
            
            local func_idx = bin_gen:get_func_index(node)
            local node_idx = param_idx  -- Node index for this node
            
            -- Count content for OPEN_CALL
            local content_count = bin_gen:count_node_params(node)
            
            -- OPEN_CALL
            local ptr_idx = node.pointer_index or 0
            table.insert(lines, string.format(" * %4d  %sOPEN_CALL[0x%02X]  %5d  %5d  %s hash=0x%08X",
                param_idx, indent, S_EXPR_PARAM.OPEN_CALL, content_count, 0,
                node.func_name, node.func_hash))
            param_idx = param_idx + 1
            
            -- Function reference (ONESHOT/MAIN/PRED)
            table.insert(lines, string.format(" * %4d  %s%-10s[0x%02X]  %5d  %5d  idx_to_ptr=%d",
                param_idx, indent, opcode_name, opcode, node_idx, func_idx, ptr_idx))
            param_idx = param_idx + 1
            
            -- Merge and sort params/children by order
            local items = {}
            for _, param in ipairs(node.params) do
                table.insert(items, { type = "param", order = param.order or 0, data = param })
            end
            for _, child in ipairs(node.children) do
                table.insert(items, { type = "child", order = child.order or 0, data = child })
            end
            table.sort(items, function(a, b) return a.order < b.order end)
            
            for _, item in ipairs(items) do
                if item.type == "child" then
                    dump_node(item.data, depth + 1)
                else
                    local p = item.data
                    local pt = p.type
                    local pv = p.value
                    
                    if pt == "int" then
                        local hex_val = pv < 0 and (0x100000000 + pv) or pv
                        table.insert(lines, string.format(" * %4d  %sINT[0x%02X]        %5s  %5s  %d (%s)",
                            param_idx, pi, S_EXPR_PARAM.INT, "-", "-", pv, fmt_hex32(pv)))
                            
                    elseif pt == "uint" then
                        table.insert(lines, string.format(" * %4d  %sUINT[0x%02X]       %5s  %5s  %d (%s)",
                            param_idx, pi, S_EXPR_PARAM.UINT, "-", "-", pv, fmt_hex32(pv)))
                            
                    elseif pt == "float" then
                        table.insert(lines, string.format(" * %4d  %sFLOAT[0x%02X]      %5s  %5s  %g",
                            param_idx, pi, S_EXPR_PARAM.FLOAT, "-", "-", pv))
                            
                    elseif pt == "str_idx" or pt == "str_ptr" then
                        local str_idx = bin_gen.string_index[pv] or 0
                        local str_len = #pv
                        local escaped = pv:gsub("\\", "\\\\"):gsub('"', '\\"'):gsub("\n", "\\n")
                        if #escaped > 40 then escaped = escaped:sub(1, 37) .. "..." end
                        table.insert(lines, string.format(" * %4d  %sSTR_IDX[0x%02X]    %5d  %5d  \"%s\"",
                            param_idx, pi, S_EXPR_PARAM.STR_IDX, str_idx, str_len, escaped))
                            
                    elseif pt == "str_hash" then
                        table.insert(lines, string.format(" * %4d  %sSTR_HASH[0x%02X]   %5s  %5s  \"%s\" hash=%s",
                            param_idx, pi, S_EXPR_PARAM.STR_HASH, "-", "-", pv.str, fmt_hex32(pv.hash)))
                            
                    elseif pt == "field_ref" then
                        local offset, size = resolve_field_offset(pv)
                        local field_hash = hash_module.fnv1a_32(pv)
                        if offset then
                            table.insert(lines, string.format(" * %4d  %sFIELD[0x%02X]      %5d  %5d  %s (off=0x%04X, hash=%s)",
                                param_idx, pi, S_EXPR_PARAM.FIELD, offset, size, pv, offset, fmt_hex32(field_hash)))
                        else
                            table.insert(lines, string.format(" * %4d  %sFIELD[0x%02X]      %5s  %5s  %s hash=%s (unresolved)",
                                param_idx, pi, S_EXPR_PARAM.FIELD, "-", "-", pv, fmt_hex32(field_hash)))
                        end
                        
                    elseif pt == "nested_field_ref" then
                        local offset, size = resolve_nested_field_offset(pv)
                        local field_hash = hash_module.fnv1a_32(pv)
                        if offset then
                            table.insert(lines, string.format(" * %4d  %sFIELD[0x%02X]      %5d  %5d  %s (off=0x%04X, hash=%s)",
                                param_idx, pi, S_EXPR_PARAM.FIELD, offset, size, pv, offset, fmt_hex32(field_hash)))
                        else
                            table.insert(lines, string.format(" * %4d  %sFIELD[0x%02X]      %5s  %5s  %s hash=%s (unresolved)",
                                param_idx, pi, S_EXPR_PARAM.FIELD, "-", "-", pv, fmt_hex32(field_hash)))
                        end
                        
                    elseif pt == "const_ref" then
                        local const_idx = bin_gen.const_index[pv] or 0
                        local cnst = mod.constants[pv]
                        local const_hash = cnst and cnst.name_hash or hash_module.fnv1a_32(pv)
                        table.insert(lines, string.format(" * %4d  %sCONST_REF[0x%02X]  %5d  %5d  %s hash=%s",
                            param_idx, pi, S_EXPR_PARAM.CONST_REF, const_idx, 0, pv, fmt_hex32(const_hash)))
                        
                    elseif pt == "result" then
                        table.insert(lines, string.format(" * %4d  %sRESULT[0x%02X]     %5s  %5s  %d (%s)",
                            param_idx, pi, S_EXPR_PARAM.RESULT, "-", "-", pv, fmt_hex32(pv)))
                        
                    elseif pt == "list_start" then
                        table.insert(brace_stack, { idx = param_idx, brace_type = "list", name = pv })
                        table.insert(lines, string.format(" * %4d  %sOPEN[0x%02X]       %5s  %5s  list '%s'",
                            param_idx, pi, S_EXPR_PARAM.OPEN, "?", "-", pv or ""))
                            
                    elseif pt == "list_end" then
                        local open_info = table.remove(brace_stack)
                        local offset = open_info and (param_idx - open_info.idx) or 0
                        table.insert(lines, string.format(" * %4d  %sCLOSE[0x%02X]      %5d  %5s  list '%s' (opened at %d)",
                            param_idx, pi, S_EXPR_PARAM.CLOSE, offset, "-", 
                            open_info and open_info.name or "", open_info and open_info.idx or 0))
                            
                    elseif pt == "dict_start" then
                        table.insert(brace_stack, { idx = param_idx, brace_type = "dict", name = pv })
                        table.insert(lines, string.format(" * %4d  %sOPEN_DICT[0x%02X]  %5s  %5s  dict '%s'",
                            param_idx, pi, S_EXPR_PARAM.OPEN_DICT, "?", "-", pv or ""))
                            
                    elseif pt == "dict_end" then
                        local open_info = table.remove(brace_stack)
                        local offset = open_info and (param_idx - open_info.idx) or 0
                        table.insert(lines, string.format(" * %4d  %sCLOSE_DICT[0x%02X] %5d  %5s  dict '%s' (opened at %d)",
                            param_idx, pi, S_EXPR_PARAM.CLOSE_DICT, offset, "-",
                            open_info and open_info.name or "", open_info and open_info.idx or 0))
                            
                    elseif pt == "dict_key" then
                        local key_hash = hash_module.fnv1a_32(pv)
                        table.insert(brace_stack, { idx = param_idx, brace_type = "dict_key", name = pv, hash = key_hash })
                        table.insert(lines, string.format(" * %4d  %sOPEN_KEY[0x%02X]   %5s  %5s  \"%s\" hash=%s",
                            param_idx, pi, S_EXPR_PARAM.OPEN_KEY, "-", "-", pv, fmt_hex32(key_hash)))
                            
                    elseif pt == "dict_key_hash" then
                        table.insert(brace_stack, { idx = param_idx, brace_type = "dict_key", name = tostring(pv), hash = pv })
                        table.insert(lines, string.format(" * %4d  %sOPEN_KEY[0x%02X]   %5s  %5s  hash=%s",
                            param_idx, pi, S_EXPR_PARAM.OPEN_KEY, "-", "-", fmt_hex32(pv)))
                            
                    elseif pt == "end_dict_key" then
                        local open_info = table.remove(brace_stack)
                        local offset = open_info and (param_idx - open_info.idx) or 0
                        table.insert(lines, string.format(" * %4d  %sCLOSE_KEY[0x%02X]  %5d  %5s  key '%s' (opened at %d)",
                            param_idx, pi, S_EXPR_PARAM.CLOSE_KEY, offset, "-",
                            open_info and open_info.name or "", open_info and open_info.idx or 0))
                            
                    elseif pt == "array_start" then
                        table.insert(brace_stack, { idx = param_idx, brace_type = "array", name = pv })
                        table.insert(lines, string.format(" * %4d  %sOPEN_ARRAY[0x%02X] %5s  %5s  array '%s'",
                            param_idx, pi, S_EXPR_PARAM.OPEN_ARRAY, "?", "-", pv or ""))
                            
                    elseif pt == "array_end" then
                        local open_info = table.remove(brace_stack)
                        local offset = open_info and (param_idx - open_info.idx) or 0
                        table.insert(lines, string.format(" * %4d  %sCLOSE_ARRAY[0x%02X]%5d  %5s  array '%s' (opened at %d)",
                            param_idx, pi, S_EXPR_PARAM.CLOSE_ARRAY, offset, "-",
                            open_info and open_info.name or "", open_info and open_info.idx or 0))
                            
                    elseif pt == "tuple_start" then
                        table.insert(brace_stack, { idx = param_idx, brace_type = "tuple", name = pv })
                        table.insert(lines, string.format(" * %4d  %sOPEN_TUPLE[0x%02X] %5s  %5s  tuple '%s'",
                            param_idx, pi, S_EXPR_PARAM.OPEN_TUPLE, "?", "-", pv or ""))
                            
                    elseif pt == "tuple_end" then
                        local open_info = table.remove(brace_stack)
                        local offset = open_info and (param_idx - open_info.idx) or 0
                        table.insert(lines, string.format(" * %4d  %sCLOSE_TUPLE[0x%02X]%5d  %5s  tuple '%s' (opened at %d)",
                            param_idx, pi, S_EXPR_PARAM.CLOSE_TUPLE, offset, "-",
                            open_info and open_info.name or "", open_info and open_info.idx or 0))
                            
                    else
                        -- Unknown/other types
                        table.insert(lines, string.format(" * %4d  %s%s             %5s  %5s  %s",
                            param_idx, pi, pt:upper(), "-", "-", tostring(pv)))
                    end
                    
                    param_idx = param_idx + 1
                end
            end
            
            -- CLOSE for this call
            table.insert(lines, string.format(" * %4d  %sCLOSE[0x%02X]      %5d  %5s  (end %s)",
                param_idx, indent, S_EXPR_PARAM.CLOSE, 0, "-", node.func_name))
            param_idx = param_idx + 1
        end
        
        for _, node in ipairs(tree.nodes) do
            dump_node(node, 0)
        end
        
        table.insert(lines, " *")
        table.insert(lines, string.format(" * Total params: %d", param_idx))
        table.insert(lines, " */")
        table.insert(lines, "")
    end
    
    table.insert(lines, "#endif // " .. guard)
    
    return table.concat(lines, "\n")
end
return M