// drone_control.h
// Generated by avro_dsl.lua - DO NOT EDIT
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "avro_common.h"

#ifdef __cplusplus
extern "C" {
#endif

// ============ FILE METADATA ============
#define DRONE_CONTROL_RECORD_COUNT  8
#define DRONE_CONTROL_SCHEMA_FILE   "drone_control.h"

// Per-record schema hashes: FNV-1a of "<file>.h:<record>"
#define FLY_STRAIGHT_REQUEST_SCHEMA_HASH   0xA084479FU
#define FLY_STRAIGHT_RESPONSE_SCHEMA_HASH   0xFEADC6A5U
#define FLY_ARC_REQUEST_SCHEMA_HASH   0xC7919983U
#define FLY_ARC_RESPONSE_SCHEMA_HASH   0x6E4B05B1U
#define FLY_UP_REQUEST_SCHEMA_HASH   0x6E4B294CU
#define FLY_UP_RESPONSE_SCHEMA_HASH   0x92D4ED60U
#define FLY_DOWN_REQUEST_SCHEMA_HASH   0xF9FCDFD9U
#define FLY_DOWN_RESPONSE_SCHEMA_HASH   0x1CD40DC7U

// ============ USER POINTERS ============
typedef struct {
    void *ptr;
} finalize_data_t;

// ============ RECORDS ============
// Note: For cross-platform wire safety, use the _wire_t variants

typedef struct {
    float distance;
    float final_altitude;
    float final_speed;
    float heading;
    finalize_data_t finalize;
} fly_straight_request_t;

typedef struct {
    float distance;
    float final_altitude;
    float final_speed;
    float heading;
    bool success;
    int32_t error_code;
} fly_straight_response_t;

typedef struct {
    float distance;
    float final_altitude;
    float final_speed;
    float heading;
    finalize_data_t finalize;
} fly_arc_request_t;

typedef struct {
    float distance;
    float final_altitude;
    float final_speed;
    float heading;
    bool success;
    int32_t error_code;
} fly_arc_response_t;

typedef struct {
    float final_altitude;
    float final_speed;
    finalize_data_t finalize;
} fly_up_request_t;

typedef struct {
    float final_altitude;
    float final_speed;
    bool success;
    int32_t error_code;
} fly_up_response_t;

typedef struct {
    float final_altitude;
    float final_speed;
    finalize_data_t finalize;
} fly_down_request_t;

typedef struct {
    float final_altitude;
    float final_speed;
    bool success;
    int32_t error_code;
} fly_down_response_t;

// ============ WIRE-SAFE RECORDS ============
// Packed structs with fixed-size enums for cross-platform compatibility
// Use these for 32-bit <-> 64-bit communication

#pragma pack(push, 1)
typedef struct {
    float distance;
    float final_altitude;
    float final_speed;
    float heading;
    finalize_data_t finalize;
} fly_straight_request_wire_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    float distance;
    float final_altitude;
    float final_speed;
    float heading;
    bool success;
    int32_t error_code;
} fly_straight_response_wire_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    float distance;
    float final_altitude;
    float final_speed;
    float heading;
    finalize_data_t finalize;
} fly_arc_request_wire_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    float distance;
    float final_altitude;
    float final_speed;
    float heading;
    bool success;
    int32_t error_code;
} fly_arc_response_wire_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    float final_altitude;
    float final_speed;
    finalize_data_t finalize;
} fly_up_request_wire_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    float final_altitude;
    float final_speed;
    bool success;
    int32_t error_code;
} fly_up_response_wire_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    float final_altitude;
    float final_speed;
    finalize_data_t finalize;
} fly_down_request_wire_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    float final_altitude;
    float final_speed;
    bool success;
    int32_t error_code;
} fly_down_response_wire_t;
#pragma pack(pop)

// ============ WIRE CONVERSION HELPERS ============

static inline void fly_straight_request_to_wire(const fly_straight_request_t* src, fly_straight_request_wire_t* dst) {
    dst->distance = src->distance;
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->heading = src->heading;
    dst->finalize = src->finalize;
}

static inline void fly_straight_request_from_wire(const fly_straight_request_wire_t* src, fly_straight_request_t* dst) {
    dst->distance = src->distance;
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->heading = src->heading;
    dst->finalize = src->finalize;
}

static inline void fly_straight_response_to_wire(const fly_straight_response_t* src, fly_straight_response_wire_t* dst) {
    dst->distance = src->distance;
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->heading = src->heading;
    dst->success = src->success;
    dst->error_code = src->error_code;
}

static inline void fly_straight_response_from_wire(const fly_straight_response_wire_t* src, fly_straight_response_t* dst) {
    dst->distance = src->distance;
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->heading = src->heading;
    dst->success = src->success;
    dst->error_code = src->error_code;
}

static inline void fly_arc_request_to_wire(const fly_arc_request_t* src, fly_arc_request_wire_t* dst) {
    dst->distance = src->distance;
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->heading = src->heading;
    dst->finalize = src->finalize;
}

static inline void fly_arc_request_from_wire(const fly_arc_request_wire_t* src, fly_arc_request_t* dst) {
    dst->distance = src->distance;
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->heading = src->heading;
    dst->finalize = src->finalize;
}

static inline void fly_arc_response_to_wire(const fly_arc_response_t* src, fly_arc_response_wire_t* dst) {
    dst->distance = src->distance;
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->heading = src->heading;
    dst->success = src->success;
    dst->error_code = src->error_code;
}

static inline void fly_arc_response_from_wire(const fly_arc_response_wire_t* src, fly_arc_response_t* dst) {
    dst->distance = src->distance;
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->heading = src->heading;
    dst->success = src->success;
    dst->error_code = src->error_code;
}

static inline void fly_up_request_to_wire(const fly_up_request_t* src, fly_up_request_wire_t* dst) {
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->finalize = src->finalize;
}

static inline void fly_up_request_from_wire(const fly_up_request_wire_t* src, fly_up_request_t* dst) {
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->finalize = src->finalize;
}

static inline void fly_up_response_to_wire(const fly_up_response_t* src, fly_up_response_wire_t* dst) {
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->success = src->success;
    dst->error_code = src->error_code;
}

static inline void fly_up_response_from_wire(const fly_up_response_wire_t* src, fly_up_response_t* dst) {
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->success = src->success;
    dst->error_code = src->error_code;
}

static inline void fly_down_request_to_wire(const fly_down_request_t* src, fly_down_request_wire_t* dst) {
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->finalize = src->finalize;
}

static inline void fly_down_request_from_wire(const fly_down_request_wire_t* src, fly_down_request_t* dst) {
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->finalize = src->finalize;
}

static inline void fly_down_response_to_wire(const fly_down_response_t* src, fly_down_response_wire_t* dst) {
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->success = src->success;
    dst->error_code = src->error_code;
}

static inline void fly_down_response_from_wire(const fly_down_response_wire_t* src, fly_down_response_t* dst) {
    dst->final_altitude = src->final_altitude;
    dst->final_speed = src->final_speed;
    dst->success = src->success;
    dst->error_code = src->error_code;
}

// ============ WIRE HEADER ============
// Common header for all wire packets (16 bytes, packed)
// schema_hash is per-record: FNV-1a of "<file>.h:<record>"

#pragma pack(push, 1)
typedef struct {
    double      timestamp;     // 8: message timestamp (set by transport)
    uint32_t    schema_hash;   // 4: per-record FNV-1a hash
    uint16_t    seq;           // 2: sequence number (set by transport)
    uint16_t    source_node;   // 2: originating node ID
} drone_control_wire_header_t;
#pragma pack(pop)

_Static_assert(sizeof(drone_control_wire_header_t) == 16, "Wire header must be 16 bytes");

// ============ WIRE PACKETS ============
// Per-record packet types with unified header
// Socket-safe: no pointers, fixed size, per-record hash identification

#pragma pack(push, 1)
typedef struct {
    drone_control_wire_header_t header;
    fly_straight_request_wire_t        data;
} fly_straight_request_packet_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    drone_control_wire_header_t header;
    fly_straight_response_wire_t        data;
} fly_straight_response_packet_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    drone_control_wire_header_t header;
    fly_arc_request_wire_t        data;
} fly_arc_request_packet_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    drone_control_wire_header_t header;
    fly_arc_response_wire_t        data;
} fly_arc_response_packet_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    drone_control_wire_header_t header;
    fly_up_request_wire_t        data;
} fly_up_request_packet_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    drone_control_wire_header_t header;
    fly_up_response_wire_t        data;
} fly_up_response_packet_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    drone_control_wire_header_t header;
    fly_down_request_wire_t        data;
} fly_down_request_packet_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    drone_control_wire_header_t header;
    fly_down_response_wire_t        data;
} fly_down_response_packet_t;
#pragma pack(pop)

// Static assertions for wire format sizes
_Static_assert(sizeof(fly_straight_request_wire_t) == 24, "fly_straight_request_wire_t size mismatch");
_Static_assert(sizeof(fly_straight_response_wire_t) == 21, "fly_straight_response_wire_t size mismatch");
_Static_assert(sizeof(fly_arc_request_wire_t) == 24, "fly_arc_request_wire_t size mismatch");
_Static_assert(sizeof(fly_arc_response_wire_t) == 21, "fly_arc_response_wire_t size mismatch");
_Static_assert(sizeof(fly_up_request_wire_t) == 16, "fly_up_request_wire_t size mismatch");
_Static_assert(sizeof(fly_up_response_wire_t) == 13, "fly_up_response_wire_t size mismatch");
_Static_assert(sizeof(fly_down_request_wire_t) == 16, "fly_down_request_wire_t size mismatch");
_Static_assert(sizeof(fly_down_response_wire_t) == 13, "fly_down_response_wire_t size mismatch");

// Packet encode helpers - populate header and return pointer to wire data
// Note: seq and timestamp are zeroed; set by transport layer before sending

static inline fly_straight_request_wire_t* fly_straight_request_packet_init(
        fly_straight_request_packet_t* pkt,
        uint16_t source_node)
{
    pkt->header.schema_hash = FLY_STRAIGHT_REQUEST_SCHEMA_HASH;
    pkt->header.timestamp = 0.0;
    pkt->header.seq = 0;
    pkt->header.source_node = source_node;
    return &pkt->data;
}

static inline fly_straight_response_wire_t* fly_straight_response_packet_init(
        fly_straight_response_packet_t* pkt,
        uint16_t source_node)
{
    pkt->header.schema_hash = FLY_STRAIGHT_RESPONSE_SCHEMA_HASH;
    pkt->header.timestamp = 0.0;
    pkt->header.seq = 0;
    pkt->header.source_node = source_node;
    return &pkt->data;
}

static inline fly_arc_request_wire_t* fly_arc_request_packet_init(
        fly_arc_request_packet_t* pkt,
        uint16_t source_node)
{
    pkt->header.schema_hash = FLY_ARC_REQUEST_SCHEMA_HASH;
    pkt->header.timestamp = 0.0;
    pkt->header.seq = 0;
    pkt->header.source_node = source_node;
    return &pkt->data;
}

static inline fly_arc_response_wire_t* fly_arc_response_packet_init(
        fly_arc_response_packet_t* pkt,
        uint16_t source_node)
{
    pkt->header.schema_hash = FLY_ARC_RESPONSE_SCHEMA_HASH;
    pkt->header.timestamp = 0.0;
    pkt->header.seq = 0;
    pkt->header.source_node = source_node;
    return &pkt->data;
}

static inline fly_up_request_wire_t* fly_up_request_packet_init(
        fly_up_request_packet_t* pkt,
        uint16_t source_node)
{
    pkt->header.schema_hash = FLY_UP_REQUEST_SCHEMA_HASH;
    pkt->header.timestamp = 0.0;
    pkt->header.seq = 0;
    pkt->header.source_node = source_node;
    return &pkt->data;
}

static inline fly_up_response_wire_t* fly_up_response_packet_init(
        fly_up_response_packet_t* pkt,
        uint16_t source_node)
{
    pkt->header.schema_hash = FLY_UP_RESPONSE_SCHEMA_HASH;
    pkt->header.timestamp = 0.0;
    pkt->header.seq = 0;
    pkt->header.source_node = source_node;
    return &pkt->data;
}

static inline fly_down_request_wire_t* fly_down_request_packet_init(
        fly_down_request_packet_t* pkt,
        uint16_t source_node)
{
    pkt->header.schema_hash = FLY_DOWN_REQUEST_SCHEMA_HASH;
    pkt->header.timestamp = 0.0;
    pkt->header.seq = 0;
    pkt->header.source_node = source_node;
    return &pkt->data;
}

static inline fly_down_response_wire_t* fly_down_response_packet_init(
        fly_down_response_packet_t* pkt,
        uint16_t source_node)
{
    pkt->header.schema_hash = FLY_DOWN_RESPONSE_SCHEMA_HASH;
    pkt->header.timestamp = 0.0;
    pkt->header.seq = 0;
    pkt->header.source_node = source_node;
    return &pkt->data;
}

// Packet verify helpers - validate per-record schema hash, return wire data pointer

static inline const fly_straight_request_wire_t* fly_straight_request_packet_verify(
        const fly_straight_request_packet_t* pkt)
{
    if (pkt->header.schema_hash != FLY_STRAIGHT_REQUEST_SCHEMA_HASH) return NULL;
    return &pkt->data;
}

static inline const fly_straight_response_wire_t* fly_straight_response_packet_verify(
        const fly_straight_response_packet_t* pkt)
{
    if (pkt->header.schema_hash != FLY_STRAIGHT_RESPONSE_SCHEMA_HASH) return NULL;
    return &pkt->data;
}

static inline const fly_arc_request_wire_t* fly_arc_request_packet_verify(
        const fly_arc_request_packet_t* pkt)
{
    if (pkt->header.schema_hash != FLY_ARC_REQUEST_SCHEMA_HASH) return NULL;
    return &pkt->data;
}

static inline const fly_arc_response_wire_t* fly_arc_response_packet_verify(
        const fly_arc_response_packet_t* pkt)
{
    if (pkt->header.schema_hash != FLY_ARC_RESPONSE_SCHEMA_HASH) return NULL;
    return &pkt->data;
}

static inline const fly_up_request_wire_t* fly_up_request_packet_verify(
        const fly_up_request_packet_t* pkt)
{
    if (pkt->header.schema_hash != FLY_UP_REQUEST_SCHEMA_HASH) return NULL;
    return &pkt->data;
}

static inline const fly_up_response_wire_t* fly_up_response_packet_verify(
        const fly_up_response_packet_t* pkt)
{
    if (pkt->header.schema_hash != FLY_UP_RESPONSE_SCHEMA_HASH) return NULL;
    return &pkt->data;
}

static inline const fly_down_request_wire_t* fly_down_request_packet_verify(
        const fly_down_request_packet_t* pkt)
{
    if (pkt->header.schema_hash != FLY_DOWN_REQUEST_SCHEMA_HASH) return NULL;
    return &pkt->data;
}

static inline const fly_down_response_wire_t* fly_down_response_packet_verify(
        const fly_down_response_packet_t* pkt)
{
    if (pkt->header.schema_hash != FLY_DOWN_RESPONSE_SCHEMA_HASH) return NULL;
    return &pkt->data;
}

// Generic packet dispatch - returns record index or -1 on error
// Matches per-record schema hash to determine record type
static inline int drone_control_packet_dispatch(
        const void* packet_buffer,
        uint16_t* source_node_out,
        const void** data_out)
{
    const drone_control_wire_header_t* hdr = (const drone_control_wire_header_t*)packet_buffer;
    if (source_node_out) *source_node_out = hdr->source_node;
    if (data_out) *data_out = ((const uint8_t*)packet_buffer) + sizeof(drone_control_wire_header_t);
    if (hdr->schema_hash == FLY_STRAIGHT_REQUEST_SCHEMA_HASH) return 0;
    if (hdr->schema_hash == FLY_STRAIGHT_RESPONSE_SCHEMA_HASH) return 1;
    if (hdr->schema_hash == FLY_ARC_REQUEST_SCHEMA_HASH) return 2;
    if (hdr->schema_hash == FLY_ARC_RESPONSE_SCHEMA_HASH) return 3;
    if (hdr->schema_hash == FLY_UP_REQUEST_SCHEMA_HASH) return 4;
    if (hdr->schema_hash == FLY_UP_RESPONSE_SCHEMA_HASH) return 5;
    if (hdr->schema_hash == FLY_DOWN_REQUEST_SCHEMA_HASH) return 6;
    if (hdr->schema_hash == FLY_DOWN_RESPONSE_SCHEMA_HASH) return 7;
    return -1;
}

// Wire record payload sizes (for buffer allocation)
static const uint16_t drone_control_wire_sizes[DRONE_CONTROL_RECORD_COUNT] = {
    sizeof(fly_straight_request_wire_t),  // fly_straight_request
    sizeof(fly_straight_response_wire_t),  // fly_straight_response
    sizeof(fly_arc_request_wire_t),  // fly_arc_request
    sizeof(fly_arc_response_wire_t),  // fly_arc_response
    sizeof(fly_up_request_wire_t),  // fly_up_request
    sizeof(fly_up_response_wire_t),  // fly_up_response
    sizeof(fly_down_request_wire_t),  // fly_down_request
    sizeof(fly_down_response_wire_t),  // fly_down_response
};

// Full packet sizes including header (for socket send/recv)
static const uint16_t drone_control_packet_sizes[DRONE_CONTROL_RECORD_COUNT] = {
    sizeof(fly_straight_request_packet_t),  // fly_straight_request
    sizeof(fly_straight_response_packet_t),  // fly_straight_response
    sizeof(fly_arc_request_packet_t),  // fly_arc_request
    sizeof(fly_arc_response_packet_t),  // fly_arc_response
    sizeof(fly_up_request_packet_t),  // fly_up_request
    sizeof(fly_up_response_packet_t),  // fly_up_response
    sizeof(fly_down_request_packet_t),  // fly_down_request
    sizeof(fly_down_response_packet_t),  // fly_down_response
};

// Per-record schema hashes (for runtime dispatch tables)
static const uint32_t drone_control_record_hashes[DRONE_CONTROL_RECORD_COUNT] = {
    FLY_STRAIGHT_REQUEST_SCHEMA_HASH,  // fly_straight_request
    FLY_STRAIGHT_RESPONSE_SCHEMA_HASH,  // fly_straight_response
    FLY_ARC_REQUEST_SCHEMA_HASH,  // fly_arc_request
    FLY_ARC_RESPONSE_SCHEMA_HASH,  // fly_arc_response
    FLY_UP_REQUEST_SCHEMA_HASH,  // fly_up_request
    FLY_UP_RESPONSE_SCHEMA_HASH,  // fly_up_response
    FLY_DOWN_REQUEST_SCHEMA_HASH,  // fly_down_request
    FLY_DOWN_RESPONSE_SCHEMA_HASH,  // fly_down_response
};

#ifdef __cplusplus
}
#endif
