// stream_test_1.h
// Generated by avro_dsl.lua - DO NOT EDIT
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "avro_common.h"

#ifdef __cplusplus
extern "C" {
#endif

// ============ FILE METADATA ============
#define STREAM_TEST_1_RECORD_COUNT  2
#define STREAM_TEST_1_SCHEMA_FILE   "stream_test_1.h"

// Per-record schema hashes: FNV-1a of "<file>.h:<record>"
#define ACCELEROMETER_READING_SCHEMA_HASH   0x29A015D4U
#define ACCELEROMETER_READING_FILTERED_SCHEMA_HASH   0x90C9FC22U

// ============ RECORDS ============
// Note: For cross-platform wire safety, use the _wire_t variants

typedef struct {
    float x;
    float y;
    float z;
} accelerometer_reading_t;

typedef struct {
    float x;
    float y;
    float z;
} accelerometer_reading_filtered_t;

// ============ WIRE-SAFE RECORDS ============
// Packed structs with fixed-size enums for cross-platform compatibility
// Use these for 32-bit <-> 64-bit communication

#pragma pack(push, 1)
typedef struct {
    float x;
    float y;
    float z;
} accelerometer_reading_wire_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    float x;
    float y;
    float z;
} accelerometer_reading_filtered_wire_t;
#pragma pack(pop)

// ============ WIRE CONVERSION HELPERS ============

static inline void accelerometer_reading_to_wire(const accelerometer_reading_t* src, accelerometer_reading_wire_t* dst) {
    dst->x = src->x;
    dst->y = src->y;
    dst->z = src->z;
}

static inline void accelerometer_reading_from_wire(const accelerometer_reading_wire_t* src, accelerometer_reading_t* dst) {
    dst->x = src->x;
    dst->y = src->y;
    dst->z = src->z;
}

static inline void accelerometer_reading_filtered_to_wire(const accelerometer_reading_filtered_t* src, accelerometer_reading_filtered_wire_t* dst) {
    dst->x = src->x;
    dst->y = src->y;
    dst->z = src->z;
}

static inline void accelerometer_reading_filtered_from_wire(const accelerometer_reading_filtered_wire_t* src, accelerometer_reading_filtered_t* dst) {
    dst->x = src->x;
    dst->y = src->y;
    dst->z = src->z;
}

// ============ WIRE HEADER ============
// Common header for all wire packets (16 bytes, packed)
// schema_hash is per-record: FNV-1a of "<file>.h:<record>"

#pragma pack(push, 1)
typedef struct {
    double      timestamp;     // 8: message timestamp (set by transport)
    uint32_t    schema_hash;   // 4: per-record FNV-1a hash
    uint16_t    seq;           // 2: sequence number (set by transport)
    uint16_t    source_node;   // 2: originating node ID
} stream_test_1_wire_header_t;
#pragma pack(pop)

_Static_assert(sizeof(stream_test_1_wire_header_t) == 16, "Wire header must be 16 bytes");

// ============ WIRE PACKETS ============
// Per-record packet types with unified header
// Socket-safe: no pointers, fixed size, per-record hash identification

#pragma pack(push, 1)
typedef struct {
    stream_test_1_wire_header_t header;
    accelerometer_reading_wire_t        data;
} accelerometer_reading_packet_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    stream_test_1_wire_header_t header;
    accelerometer_reading_filtered_wire_t        data;
} accelerometer_reading_filtered_packet_t;
#pragma pack(pop)

// Static assertions for wire format sizes
_Static_assert(sizeof(accelerometer_reading_wire_t) == 12, "accelerometer_reading_wire_t size mismatch");
_Static_assert(sizeof(accelerometer_reading_filtered_wire_t) == 12, "accelerometer_reading_filtered_wire_t size mismatch");

// Packet encode helpers - populate header and return pointer to wire data
// Note: seq and timestamp are zeroed; set by transport layer before sending

static inline accelerometer_reading_wire_t* accelerometer_reading_packet_init(
        accelerometer_reading_packet_t* pkt,
        uint16_t source_node)
{
    pkt->header.schema_hash = ACCELEROMETER_READING_SCHEMA_HASH;
    pkt->header.timestamp = 0.0;
    pkt->header.seq = 0;
    pkt->header.source_node = source_node;
    return &pkt->data;
}

static inline accelerometer_reading_filtered_wire_t* accelerometer_reading_filtered_packet_init(
        accelerometer_reading_filtered_packet_t* pkt,
        uint16_t source_node)
{
    pkt->header.schema_hash = ACCELEROMETER_READING_FILTERED_SCHEMA_HASH;
    pkt->header.timestamp = 0.0;
    pkt->header.seq = 0;
    pkt->header.source_node = source_node;
    return &pkt->data;
}

// Packet verify helpers - validate per-record schema hash, return wire data pointer

static inline const accelerometer_reading_wire_t* accelerometer_reading_packet_verify(
        const accelerometer_reading_packet_t* pkt)
{
    if (pkt->header.schema_hash != ACCELEROMETER_READING_SCHEMA_HASH) return NULL;
    return &pkt->data;
}

static inline const accelerometer_reading_filtered_wire_t* accelerometer_reading_filtered_packet_verify(
        const accelerometer_reading_filtered_packet_t* pkt)
{
    if (pkt->header.schema_hash != ACCELEROMETER_READING_FILTERED_SCHEMA_HASH) return NULL;
    return &pkt->data;
}

// Generic packet dispatch - returns record index or -1 on error
// Matches per-record schema hash to determine record type
static inline int stream_test_1_packet_dispatch(
        const void* packet_buffer,
        uint16_t* source_node_out,
        const void** data_out)
{
    const stream_test_1_wire_header_t* hdr = (const stream_test_1_wire_header_t*)packet_buffer;
    if (source_node_out) *source_node_out = hdr->source_node;
    if (data_out) *data_out = ((const uint8_t*)packet_buffer) + sizeof(stream_test_1_wire_header_t);
    if (hdr->schema_hash == ACCELEROMETER_READING_SCHEMA_HASH) return 0;
    if (hdr->schema_hash == ACCELEROMETER_READING_FILTERED_SCHEMA_HASH) return 1;
    return -1;
}

// Wire record payload sizes (for buffer allocation)
static const uint16_t stream_test_1_wire_sizes[STREAM_TEST_1_RECORD_COUNT] = {
    sizeof(accelerometer_reading_wire_t),  // accelerometer_reading
    sizeof(accelerometer_reading_filtered_wire_t),  // accelerometer_reading_filtered
};

// Full packet sizes including header (for socket send/recv)
static const uint16_t stream_test_1_packet_sizes[STREAM_TEST_1_RECORD_COUNT] = {
    sizeof(accelerometer_reading_packet_t),  // accelerometer_reading
    sizeof(accelerometer_reading_filtered_packet_t),  // accelerometer_reading_filtered
};

// Per-record schema hashes (for runtime dispatch tables)
static const uint32_t stream_test_1_record_hashes[STREAM_TEST_1_RECORD_COUNT] = {
    ACCELEROMETER_READING_SCHEMA_HASH,  // accelerometer_reading
    ACCELEROMETER_READING_FILTERED_SCHEMA_HASH,  // accelerometer_reading_filtered
};

#ifdef __cplusplus
}
#endif
